using System;
using System.IO;
using System.Linq;
using System.Text;

namespace PowerForge;

/// <summary>
/// Generates a patched script module that loads selected binary module assemblies through an isolated context.
/// </summary>
public sealed class ModuleIsolationScriptPatcher
{
    /// <summary>Creates a patched script body from a source script and isolation profile.</summary>
    public string CreatePatchedScript(string sourceScript, ModuleIsolationProfile profile)
    {
        if (sourceScript is null)
            throw new ArgumentNullException(nameof(sourceScript));
        if (profile is null)
            throw new ArgumentNullException(nameof(profile));

        var body = GetSourceBodyLines(sourceScript, profile);

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by PowerForge Import-IsolatedModule. Do not edit this file.");
        builder.AppendLine(CreateLoaderBlock(profile));
        if (profile.IncludeSourceScriptBody)
            builder.AppendLine(string.Join(Environment.NewLine, body));
        if (profile.AdditionalScriptLines.Length > 0)
            builder.AppendLine(string.Join(Environment.NewLine, profile.AdditionalScriptLines));
        return builder.ToString();
    }

    /// <summary>Patches a script file and writes the generated script to the target path.</summary>
    public void PatchFile(string sourceScriptPath, string targetScriptPath, ModuleIsolationProfile profile)
    {
        if (string.IsNullOrWhiteSpace(sourceScriptPath))
            throw new ArgumentException("Source script path is required.", nameof(sourceScriptPath));
        if (string.IsNullOrWhiteSpace(targetScriptPath))
            throw new ArgumentException("Target script path is required.", nameof(targetScriptPath));

        var source = File.ReadAllText(sourceScriptPath, Encoding.UTF8);
        var patched = CreatePatchedScript(source, profile);
        Directory.CreateDirectory(Path.GetDirectoryName(targetScriptPath) ?? ".");
        File.WriteAllText(targetScriptPath, patched, Encoding.UTF8);
    }

    private static string CreateLoaderBlock(ModuleIsolationProfile profile)
    {
        var binaryImports = string.Join(", ", profile.BinaryImports.Select(static value => "'" + EscapePowerShellString(value) + "'"));
        var dependencyImports = string.Join(", ", profile.DependencyAssemblyImports.Select(static value => "'" + EscapePowerShellString(value) + "'"));
        var namespaces = string.Join(", ", profile.TypeAcceleratorNamespaces.Select(static value => "'" + EscapePowerShellString(value) + "'"));
        var contextName = EscapePowerShellString(string.IsNullOrWhiteSpace(profile.ContextName) ? profile.Name + ".ALC" : profile.ContextName);

        return $$"""
if (-not ('PowerForge.ModuleIsolation.ModuleLoadContext' -as [type])) {
    Add-Type -TypeDefinition @"
using System;
using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;

namespace PowerForge.ModuleIsolation
{
    public sealed class ModuleLoadContext : AssemblyLoadContext
    {
        private static readonly object Sync = new object();
        private static readonly Dictionary<string, ModuleLoadContext> Contexts = new Dictionary<string, ModuleLoadContext>(StringComparer.OrdinalIgnoreCase);
        private readonly List<string> assemblyDirectories = new List<string>();
        private readonly List<AssemblyDependencyResolver> resolvers = new List<AssemblyDependencyResolver>();
        private readonly Dictionary<string, Assembly> loadedAssemblies = new Dictionary<string, Assembly>(StringComparer.OrdinalIgnoreCase);

        private ModuleLoadContext(string mainAssemblyPath, string contextName)
            : base(contextName, isCollectible: false)
        {
            AddProbePath(mainAssemblyPath);
        }

        public ReadOnlyCollection<Assembly> LoadedModuleAssemblies
        {
            get { return loadedAssemblies.Values.ToList().AsReadOnly(); }
        }

        public static Assembly LoadModule(string assemblyPath, string contextName)
        {
            if (string.IsNullOrWhiteSpace(assemblyPath))
            {
                throw new ArgumentException("Assembly path is required.", nameof(assemblyPath));
            }

            var fullPath = Path.GetFullPath(assemblyPath);
            if (!File.Exists(fullPath))
            {
                throw new FileNotFoundException("Assembly was not found.", fullPath);
            }

            lock (Sync)
            {
                if (!Contexts.TryGetValue(contextName, out var context))
                {
                    context = new ModuleLoadContext(fullPath, contextName);
                    Contexts[contextName] = context;
                }
                else
                {
                    context.AddProbePath(fullPath);
                }

                return context.LoadAssemblyFromPath(fullPath);
            }
        }

        private Assembly LoadAssemblyFromPath(string fullPath)
        {
            if (!loadedAssemblies.TryGetValue(fullPath, out var assembly))
            {
                assembly = LoadFromAssemblyPath(fullPath);
                loadedAssemblies[fullPath] = assembly;
            }

            return assembly;
        }

        private void AddProbePath(string assemblyPath)
        {
            var directory = Path.GetDirectoryName(assemblyPath) ?? string.Empty;
            if (!assemblyDirectories.Contains(directory, StringComparer.OrdinalIgnoreCase))
            {
                assemblyDirectories.Add(directory);
            }

            var resolver = TryCreateResolver(assemblyPath);
            if (resolver != null)
            {
                resolvers.Add(resolver);
            }
        }

        private static AssemblyDependencyResolver TryCreateResolver(string assemblyPath)
        {
            try
            {
                return new AssemblyDependencyResolver(assemblyPath);
            }
            catch (InvalidOperationException)
            {
                return null;
            }
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            if (assemblyName == null || string.IsNullOrWhiteSpace(assemblyName.Name))
            {
                return null;
            }

            var loaderAssembly = typeof(ModuleLoadContext).Assembly.GetName();
            if (AssemblyName.ReferenceMatchesDefinition(loaderAssembly, assemblyName))
            {
                return typeof(ModuleLoadContext).Assembly;
            }

            if (assemblyName.Name.Equals("System.Management.Automation", StringComparison.OrdinalIgnoreCase))
            {
                return typeof(System.Management.Automation.PSObject).Assembly;
            }

            foreach (var resolver in resolvers)
            {
                var resolvedPath = resolver.ResolveAssemblyToPath(assemblyName);
                if (!string.IsNullOrWhiteSpace(resolvedPath) && File.Exists(resolvedPath))
                {
                    return LoadAssemblyFromPath(resolvedPath);
                }
            }

            foreach (var directory in assemblyDirectories)
            {
                var candidatePath = Path.Combine(directory, assemblyName.Name + ".dll");
                if (File.Exists(candidatePath))
                {
                    return LoadAssemblyFromPath(candidatePath);
                }
            }

            return AssemblyLoadContext.Default.Assemblies.FirstOrDefault(a =>
                AssemblyName.ReferenceMatchesDefinition(a.GetName(), assemblyName));
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            foreach (var resolver in resolvers)
            {
                var resolvedPath = resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
                if (!string.IsNullOrWhiteSpace(resolvedPath) && File.Exists(resolvedPath))
                {
                    return LoadUnmanagedDllFromPath(resolvedPath);
                }
            }

            return IntPtr.Zero;
        }
    }
}
"@ -ErrorAction Stop
}

$PowerForgeIsolationContextName = '{{contextName}}'
$PowerForgeIsolationDependencyAssemblies = foreach ($PowerForgeIsolationDependency in @({{dependencyImports}})) {
    $PowerForgeIsolationDependencyPath = [System.IO.Path]::Combine($PSScriptRoot, $PowerForgeIsolationDependency)
    [PowerForge.ModuleIsolation.ModuleLoadContext]::LoadModule($PowerForgeIsolationDependencyPath, $PowerForgeIsolationContextName)
}

$PowerForgeIsolationAssemblies = foreach ($PowerForgeIsolationBinary in @({{binaryImports}})) {
    $PowerForgeIsolationPath = [System.IO.Path]::Combine($PSScriptRoot, $PowerForgeIsolationBinary)
    [PowerForge.ModuleIsolation.ModuleLoadContext]::LoadModule($PowerForgeIsolationPath, $PowerForgeIsolationContextName)
}

foreach ($PowerForgeIsolationAssembly in $PowerForgeIsolationAssemblies) {
    Import-Module -Assembly $PowerForgeIsolationAssembly -Force
}

$PowerForgeIsolationTypeNamespaces = @({{namespaces}})
if ($PowerForgeIsolationTypeNamespaces.Count -gt 0) {
    $PowerForgeIsolationContext = [System.Runtime.Loader.AssemblyLoadContext]::GetLoadContext($PowerForgeIsolationAssemblies[0])
    $PowerForgeIsolationAssemblies = $PowerForgeIsolationContext.LoadedModuleAssemblies
    $PowerForgeTypeAccelerators = [psobject].Assembly.GetType('System.Management.Automation.TypeAccelerators')
    $PowerForgeGetAccelerators = $PowerForgeTypeAccelerators.GetProperty('Get').GetValue($null)
    $PowerForgeAddAccelerator = $PowerForgeTypeAccelerators.GetMethod('Add')
    $PowerForgeRemoveAccelerator = $PowerForgeTypeAccelerators.GetMethod('Remove')

    foreach ($PowerForgeIsolationAssembly in @($PowerForgeIsolationContext.Assemblies)) {
        try {
            $PowerForgeIsolationTypes = $PowerForgeIsolationAssembly.GetTypes()
        } catch [System.Reflection.ReflectionTypeLoadException] {
            $PowerForgeIsolationTypes = $_.Exception.Types | Where-Object { $null -ne $_ }
        }

        foreach ($PowerForgeIsolationType in $PowerForgeIsolationTypes) {
            if (-not $PowerForgeIsolationType.FullName) {
                continue
            }

            $PowerForgeExposeType = $false
            foreach ($PowerForgeNamespace in $PowerForgeIsolationTypeNamespaces) {
                if ($PowerForgeIsolationType.FullName.StartsWith($PowerForgeNamespace, [StringComparison]::OrdinalIgnoreCase)) {
                    $PowerForgeExposeType = $true
                    break
                }
            }

            if (-not $PowerForgeExposeType) {
                continue
            }

            try {
                if ($PowerForgeGetAccelerators.ContainsKey($PowerForgeIsolationType.FullName)) {
                    [void] $PowerForgeRemoveAccelerator.Invoke($null, @($PowerForgeIsolationType.FullName))
                }

                [void] $PowerForgeAddAccelerator.Invoke($null, @($PowerForgeIsolationType.FullName, $PowerForgeIsolationType))
            } catch {
                Write-Verbose "Failed to register isolated type '$($PowerForgeIsolationType.FullName)': $($_.Exception.Message)"
            }
        }
    }
}
""";
    }

    private static string EscapePowerShellString(string value)
        => (value ?? string.Empty).Replace("'", "''");

    private static string[] GetSourceBodyLines(string sourceScript, ModuleIsolationProfile profile)
    {
        var lines = sourceScript
            .Replace("\r\n", "\n")
            .Replace('\r', '\n')
            .Split('\n')
            .Skip(Math.Max(0, profile.SourceLinesToSkip))
            .Where(line => !ShouldSkipSourceLine(line, profile));

        if (!profile.RemoveSourceSignatureBlock)
            return lines.ToArray();

        return RemoveSignatureBlock(lines).ToArray();
    }

    private static IEnumerable<string> RemoveSignatureBlock(IEnumerable<string> lines)
    {
        var skippingSignature = false;

        foreach (var line in lines)
        {
            if (line.StartsWith("# SIG # Begin signature block", StringComparison.Ordinal))
            {
                skippingSignature = true;
                continue;
            }

            if (skippingSignature)
            {
                if (line.StartsWith("# SIG # End signature block", StringComparison.Ordinal))
                    skippingSignature = false;

                continue;
            }

            yield return line;
        }
    }

    private static bool ShouldSkipSourceLine(string line, ModuleIsolationProfile profile)
        => profile.SourceLineContainsToSkip.Any(fragment =>
            !string.IsNullOrWhiteSpace(fragment) &&
            line.IndexOf(fragment, StringComparison.OrdinalIgnoreCase) >= 0);
}
