namespace PowerForge;

internal sealed class BuildConfigurationRequest
{
    public bool EnableSpecified { get; set; }
    public bool Enable { get; set; }
    public bool DeleteTargetModuleBeforeBuildSpecified { get; set; }
    public bool DeleteTargetModuleBeforeBuild { get; set; }
    public bool MergeModuleOnBuildSpecified { get; set; }
    public bool MergeModuleOnBuild { get; set; }
    public bool MergeFunctionsFromApprovedModulesSpecified { get; set; }
    public bool MergeFunctionsFromApprovedModules { get; set; }
    public bool SignModuleSpecified { get; set; }
    public bool SignModule { get; set; }
    public bool DotSourceClassesSpecified { get; set; }
    public bool DotSourceClasses { get; set; }
    public bool DotSourceLibrariesSpecified { get; set; }
    public bool DotSourceLibraries { get; set; }
    public bool SeparateFileLibrariesSpecified { get; set; }
    public bool SeparateFileLibraries { get; set; }
    public bool RefreshPSD1OnlySpecified { get; set; }
    public bool RefreshPSD1Only { get; set; }
    public bool UseWildcardForFunctionsSpecified { get; set; }
    public bool UseWildcardForFunctions { get; set; }
    public bool LocalVersioningSpecified { get; set; }
    public bool LocalVersioning { get; set; }
    public bool SyncNETProjectVersionSpecified { get; set; }
    public bool SyncNETProjectVersion { get; set; }
    public bool VersionedInstallStrategySpecified { get; set; }
    public InstallationStrategy? VersionedInstallStrategy { get; set; }
    public bool VersionedInstallKeepSpecified { get; set; }
    public int VersionedInstallKeep { get; set; }
    public bool VersionedInstallLegacyFlatHandlingSpecified { get; set; }
    public LegacyFlatModuleHandling? VersionedInstallLegacyFlatHandling { get; set; }
    public bool VersionedInstallPreserveVersionsSpecified { get; set; }
    public string[]? VersionedInstallPreserveVersions { get; set; }
    public bool InstallMissingModulesSpecified { get; set; }
    public bool InstallMissingModules { get; set; }
    public bool InstallMissingModulesForceSpecified { get; set; }
    public bool InstallMissingModulesForce { get; set; }
    public bool InstallMissingModulesPrereleaseSpecified { get; set; }
    public bool InstallMissingModulesPrerelease { get; set; }
    public bool ResolveMissingModulesOnlineSpecified { get; set; }
    public bool ResolveMissingModulesOnline { get; set; }
    public bool WarnIfRequiredModulesOutdatedSpecified { get; set; }
    public bool WarnIfRequiredModulesOutdated { get; set; }
    public bool InstallMissingModulesRepositorySpecified { get; set; }
    public string? InstallMissingModulesRepository { get; set; }
    public bool InstallMissingModulesCredentialUserNameSpecified { get; set; }
    public string? InstallMissingModulesCredentialUserName { get; set; }
    public bool InstallMissingModulesCredentialSecretSpecified { get; set; }
    public string? InstallMissingModulesCredentialSecret { get; set; }
    public bool InstallMissingModulesCredentialSecretFilePathSpecified { get; set; }
    public string? InstallMissingModulesCredentialSecretFilePath { get; set; }
    public bool SkipBuiltinReplacementsSpecified { get; set; }
    public bool SkipBuiltinReplacements { get; set; }
    public bool DoNotAttemptToFixRelativePathsSpecified { get; set; }
    public bool DoNotAttemptToFixRelativePaths { get; set; }
    public bool CertificateThumbprintSpecified { get; set; }
    public string? CertificateThumbprint { get; set; }
    public bool CertificatePFXPathSpecified { get; set; }
    public string? CertificatePFXPath { get; set; }
    public bool CertificatePFXBase64Specified { get; set; }
    public string? CertificatePFXBase64 { get; set; }
    public bool CertificatePFXPasswordSpecified { get; set; }
    public string? CertificatePFXPassword { get; set; }
    public bool NETProjectPathSpecified { get; set; }
    public string? NETProjectPath { get; set; }
    public bool NETConfigurationSpecified { get; set; }
    public string? NETConfiguration { get; set; }
    public bool NETFrameworkSpecified { get; set; }
    public string[]? NETFramework { get; set; }
    public bool NETProjectNameSpecified { get; set; }
    public string? NETProjectName { get; set; }
    public bool NETExcludeMainLibrarySpecified { get; set; }
    public bool NETExcludeMainLibrary { get; set; }
    public bool NETExcludeLibraryFilterSpecified { get; set; }
    public string[]? NETExcludeLibraryFilter { get; set; }
    public bool NETIgnoreLibraryOnLoadSpecified { get; set; }
    public string[]? NETIgnoreLibraryOnLoad { get; set; }
    public bool NETBinaryModuleSpecified { get; set; }
    public string[]? NETBinaryModule { get; set; }
    public bool NETHandleAssemblyWithSameNameSpecified { get; set; }
    public bool NETHandleAssemblyWithSameName { get; set; }
    public bool NETLineByLineAddTypeSpecified { get; set; }
    public bool NETLineByLineAddType { get; set; }
    public bool NETBinaryModuleCmdletScanDisabledSpecified { get; set; }
    public bool NETBinaryModuleCmdletScanDisabled { get; set; }
    public bool NETMergeLibraryDebuggingSpecified { get; set; }
    public bool NETMergeLibraryDebugging { get; set; }
    public bool NETResolveBinaryConflictsSpecified { get; set; }
    public bool NETResolveBinaryConflicts { get; set; }
    public bool NETResolveBinaryConflictsNameSpecified { get; set; }
    public string? NETResolveBinaryConflictsName { get; set; }
    public bool NETBinaryModuleDocumentationSpecified { get; set; }
    public bool NETBinaryModuleDocumentation { get; set; }
    public bool NETDoNotCopyLibrariesRecursivelySpecified { get; set; }
    public bool NETDoNotCopyLibrariesRecursively { get; set; }
    public bool NETSearchClassSpecified { get; set; }
    public string? NETSearchClass { get; set; }
    public bool NETHandleRuntimesSpecified { get; set; }
    public bool NETHandleRuntimes { get; set; }
    public bool KillLockersBeforeInstallSpecified { get; set; }
    public bool KillLockersBeforeInstall { get; set; }
    public bool KillLockersForceSpecified { get; set; }
    public bool KillLockersForce { get; set; }
    public bool AutoSwitchExactOnPublishSpecified { get; set; }
    public bool AutoSwitchExactOnPublish { get; set; }
    public bool SignIncludeInternalsSpecified { get; set; }
    public bool SignIncludeInternals { get; set; }
    public bool SignIncludeBinariesSpecified { get; set; }
    public bool SignIncludeBinaries { get; set; }
    public bool SignIncludeExeSpecified { get; set; }
    public bool SignIncludeExe { get; set; }
    public bool SignCustomIncludeSpecified { get; set; }
    public string[]? SignCustomInclude { get; set; }
    public bool SignExcludePathsSpecified { get; set; }
    public string[]? SignExcludePaths { get; set; }
    public bool SignOverwriteSignedSpecified { get; set; }
    public bool SignOverwriteSigned { get; set; }
}
