using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace PowerForge.Web;

/// <summary>Apache export operations for the PowerForge.Web link service.</summary>
public static partial class WebLinkService
{
    /// <summary>Exports enabled redirect and shortlink rules as an Apache rewrite include.</summary>
    public static WebLinkApacheExportResult ExportApache(WebLinkDataSet dataSet, WebLinkApacheExportOptions options)
    {
        ArgumentNullException.ThrowIfNull(dataSet);
        ArgumentNullException.ThrowIfNull(options);

        if (string.IsNullOrWhiteSpace(options.OutputPath))
            throw new InvalidOperationException("Apache export requires an output path.");

        var lines = new List<string>();
        if (options.IncludeHeader)
        {
            lines.Add("# Auto-generated by PowerForge.Web link service");
            lines.Add("# Include this file from your Apache vhost before static file fallback.");
        }

        if (options.IncludeErrorDocument404)
            lines.Add("ErrorDocument 404 /404.html");

        lines.Add("RewriteEngine On");
        lines.Add(string.Empty);

        var rules = BuildExportRedirects(dataSet, options)
            .OrderByDescending(static rule => rule.Priority)
            .ThenBy(static rule => MatchTypeOrder(rule.MatchType))
            .ThenBy(static rule => rule.SourceHost ?? string.Empty, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static rule => rule.SourcePath, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static rule => rule.SourceQuery ?? string.Empty, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        var ruleCount = 0;
        foreach (var rule in rules)
        {
            if (!TryAppendApacheRule(lines, rule, options.LanguageRootHosts))
                continue;
            ruleCount++;
        }

        var outputDirectory = Path.GetDirectoryName(options.OutputPath);
        if (!string.IsNullOrWhiteSpace(outputDirectory))
            Directory.CreateDirectory(outputDirectory);

        File.WriteAllText(options.OutputPath, string.Join(Environment.NewLine, lines), Utf8NoBom);

        return new WebLinkApacheExportResult
        {
            OutputPath = Path.GetFullPath(options.OutputPath),
            RuleCount = ruleCount
        };
    }

    private static LinkRedirectRule[] BuildExportRedirects(WebLinkDataSet dataSet, WebLinkApacheExportOptions options)
    {
        var redirects = new List<LinkRedirectRule>();
        redirects.AddRange(dataSet.Redirects.Where(static redirect => redirect is not null && redirect.Enabled));

        foreach (var shortlink in dataSet.Shortlinks.Where(static item => item is not null && item.Enabled))
        {
            redirects.Add(new LinkRedirectRule
            {
                Id = "shortlink:" + shortlink.Slug,
                Enabled = true,
                SourceHost = shortlink.Host,
                SourcePath = NormalizeShortlinkPath(shortlink, options.Hosts),
                MatchType = LinkRedirectMatchType.Exact,
                TargetUrl = AppendUtm(shortlink.TargetUrl, shortlink.Utm),
                Status = shortlink.Status <= 0 ? 302 : shortlink.Status,
                PreserveQuery = false,
                Priority = 1000,
                Group = "shortlinks",
                Source = "shortlink",
                Notes = shortlink.Title,
                AllowExternal = shortlink.AllowExternal
            });
        }

        return redirects
            .GroupBy(BuildRedirectKey, StringComparer.OrdinalIgnoreCase)
            .Select(group => group
                .OrderByDescending(static rule => rule.Priority)
                .ThenBy(static rule => SourceRank(rule.Source))
                .ThenBy(static rule => string.IsNullOrWhiteSpace(rule.OriginPath) ? string.Empty : rule.OriginPath, StringComparer.OrdinalIgnoreCase)
                .ThenBy(static rule => rule.OriginLine)
                .ThenBy(rule => NormalizeTargetForCompare(rule.TargetUrl, rule.SourceHost, options.LanguageRootHosts), StringComparer.OrdinalIgnoreCase)
                .First())
            .ToArray();
    }

    private static bool TryAppendApacheRule(
        List<string> lines,
        LinkRedirectRule rule,
        IReadOnlyDictionary<string, string>? languageRootHosts)
    {
        if (rule.Status == 410)
        {
            if (!TryBuildApachePattern(rule, out var gonePattern, out _))
                return false;

            AppendHostCondition(lines, rule.SourceHost);
            AppendQueryCondition(lines, rule.SourceQuery);
            lines.Add($"RewriteRule {gonePattern} - [G,L]");
            lines.Add(string.Empty);
            return true;
        }

        if (!TryBuildApachePattern(rule, out var pattern, out var destination))
            return false;

        destination = NormalizeApacheDestination(destination, rule.SourceHost, languageRootHosts);

        AppendHostCondition(lines, rule.SourceHost);
        AppendQueryCondition(lines, rule.SourceQuery);

        var hasSourceQuery = !string.IsNullOrWhiteSpace(rule.SourceQuery);
        var flags = new List<string>
        {
            $"R={ResolveStatus(rule.Status, defaultStatus: 301)}",
            "L",
            rule.PreserveQuery && !hasSourceQuery ? "QSA" : "QSD"
        };
        lines.Add($"RewriteRule {pattern} {destination} [{string.Join(",", flags)}]");
        lines.Add(string.Empty);
        return true;
    }

    private static string NormalizeApacheDestination(
        string destination,
        string? sourceHost,
        IReadOnlyDictionary<string, string>? languageRootHosts)
    {
        if (string.IsNullOrWhiteSpace(destination) ||
            string.IsNullOrWhiteSpace(sourceHost) ||
            languageRootHosts is null ||
            !languageRootHosts.TryGetValue(sourceHost.Trim(), out var language) ||
            string.IsNullOrWhiteSpace(language))
        {
            return destination;
        }

        if (!IsHttpUrl(destination))
            return StripLanguageRootPrefix(destination, language);

        if (!Uri.TryCreate(destination, UriKind.Absolute, out var uri) ||
            !uri.Host.Equals(sourceHost.Trim(), StringComparison.OrdinalIgnoreCase))
        {
            return destination;
        }

        var strippedPath = StripLanguageRootPrefix(uri.AbsolutePath, language);
        if (strippedPath.Equals(uri.AbsolutePath, StringComparison.Ordinal))
            return destination;

        var builder = new UriBuilder(uri)
        {
            Path = strippedPath
        };
        return builder.Uri.ToString();
    }

    private static bool TryBuildApachePattern(LinkRedirectRule rule, out string pattern, out string destination)
    {
        pattern = string.Empty;
        destination = string.Empty;
        if (rule is null || string.IsNullOrWhiteSpace(rule.SourcePath))
            return false;

        switch (rule.MatchType)
        {
            case LinkRedirectMatchType.Prefix:
            {
                var prefix = NormalizeSourcePath(rule.SourcePath);
                var starIndex = prefix.IndexOf('*');
                if (starIndex >= 0)
                    prefix = prefix.Substring(0, starIndex);
                prefix = prefix.Trim('/');
                pattern = string.IsNullOrWhiteSpace(prefix)
                    ? "^(.*)$"
                    : $"^{Regex.Escape(prefix)}(?:/(.*))?$";
                destination = NormalizeDestination(rule.TargetUrl).Replace("{path}", "$1", StringComparison.OrdinalIgnoreCase);
                return rule.Status == 410 || !string.IsNullOrWhiteSpace(destination);
            }
            case LinkRedirectMatchType.Regex:
            {
                var regex = rule.SourcePath.Trim();
                if (regex.StartsWith("/", StringComparison.Ordinal))
                    regex = regex.TrimStart('/');
                pattern = regex.StartsWith("^", StringComparison.Ordinal) ? regex : "^" + regex;
                destination = NormalizeDestination(rule.TargetUrl).Replace("{path}", "$1", StringComparison.OrdinalIgnoreCase);
                return rule.Status == 410 || !string.IsNullOrWhiteSpace(destination);
            }
            case LinkRedirectMatchType.Query:
            case LinkRedirectMatchType.Exact:
            default:
            {
                var exact = NormalizeSourcePath(rule.SourcePath).Trim('/');
                pattern = string.IsNullOrWhiteSpace(exact) ? "^$" : $"^{Regex.Escape(exact)}/?$";
                destination = NormalizeDestination(rule.TargetUrl);
                return rule.Status == 410 || !string.IsNullOrWhiteSpace(destination);
            }
        }
    }

    private static void AppendHostCondition(List<string> lines, string? host)
    {
        if (string.IsNullOrWhiteSpace(host) || host.Trim().Equals("*", StringComparison.Ordinal))
            return;

        lines.Add($"RewriteCond %{{HTTP_HOST}} ^(.+\\.)?{Regex.Escape(host.Trim())}$ [NC]");
    }

    private static void AppendQueryCondition(List<string> lines, string? query)
    {
        if (string.IsNullOrWhiteSpace(query))
            return;

        var trimmed = query.Trim().TrimStart('?');
        var postMatch = LegacyPostIdRegex.Match("/?" + trimmed);
        if (postMatch.Success)
        {
            lines.Add($"RewriteCond %{{QUERY_STRING}} (^|&)p={postMatch.Groups[1].Value}(&|$)");
            return;
        }

        var pageMatch = LegacyPageIdRegex.Match("/?" + trimmed);
        if (pageMatch.Success)
        {
            lines.Add($"RewriteCond %{{QUERY_STRING}} (^|&)page_id={pageMatch.Groups[1].Value}(&|$)");
            return;
        }

        lines.Add($"RewriteCond %{{QUERY_STRING}} ^{Regex.Escape(trimmed)}$");
    }
}
