using System.Text.Json;

namespace PowerForge.Web;

/// <summary>Scaffolds a starter site with content and theme.</summary>
public static partial class WebSiteScaffolder
{
    private const string DefaultSchemaBaseUrl = "https://raw.githubusercontent.com/EvotecIT/PSPublishModule/main/Schemas/";

    private sealed class SuiteStarterProjectSeed
    {
        public string Slug { get; init; } = string.Empty;
        public string Name { get; init; } = string.Empty;
        public string Surface { get; init; } = string.Empty;
        public string SurfaceCatalogKey { get; init; } = string.Empty;
        public string QuickStartType { get; init; } = string.Empty;
        public string QuickStartTarget { get; init; } = string.Empty;
        public string RelatedContentFileName { get; init; } = string.Empty;
    }

    /// <summary>Creates a new site scaffold.</summary>
    /// <param name="outputPath">Output directory.</param>
    /// <param name="siteName">Optional site name.</param>
    /// <param name="baseUrl">Optional base URL.</param>
    /// <param name="themeEngine">Template engine identifier.</param>
    /// <param name="maintenanceProfileName">Maintenance profile (`conservative`, `balanced`, `aggressive`).</param>
    /// <param name="starterProfileName">Starter profile (`standard`, `multi-project-api-suite`).</param>
    /// <param name="suiteProjectSlug">Optional first suite project slug to materialize for the multi-project API suite starter.</param>
    /// <param name="suiteProjectName">Optional first suite project display name to materialize for the multi-project API suite starter.</param>
    /// <param name="suiteProjectSurface">Optional first suite project API surface (`powershell`, `dotnet`).</param>
    /// <returns>Result payload describing created files.</returns>
    public static WebScaffoldResult Scaffold(string outputPath, string? siteName, string? baseUrl, string? themeEngine, string? maintenanceProfileName = null, string? starterProfileName = null, string? suiteProjectSlug = null, string? suiteProjectName = null, string? suiteProjectSurface = null)
    {
        if (string.IsNullOrWhiteSpace(outputPath))
            throw new ArgumentException("Output path is required.", nameof(outputPath));

        var fullOutput = Path.GetFullPath(outputPath);
        if (Directory.Exists(fullOutput) && Directory.EnumerateFileSystemEntries(fullOutput).Any())
            throw new InvalidOperationException($"Output path is not empty: {fullOutput}");

        Directory.CreateDirectory(fullOutput);

        var name = string.IsNullOrWhiteSpace(siteName) ? "MySite" : siteName.Trim();
        var url = string.IsNullOrWhiteSpace(baseUrl) ? "https://example.com" : baseUrl.Trim();
        var engine = string.IsNullOrWhiteSpace(themeEngine) ? "simple" : themeEngine.Trim();
        var isScriban = engine.Equals("scriban", StringComparison.OrdinalIgnoreCase);
        var themeName = isScriban ? "nova" : "base";
        var maintenanceProfile = NormalizeMaintenanceProfile(maintenanceProfileName);
        var maintenanceBudgets = ResolveMaintenanceBudgets(maintenanceProfile);
        var starterProfile = NormalizeStarterProfile(starterProfileName);
        var multiProjectApiSuiteStarter = starterProfile.Equals("multi-project-api-suite", StringComparison.OrdinalIgnoreCase);
        var firstSuiteProject = ResolveSuiteStarterProjectSeed(multiProjectApiSuiteStarter, suiteProjectSlug, suiteProjectName, suiteProjectSurface);

        var created = 0;

        var contentPagesRoot = Path.Combine(fullOutput, "content", "pages");
        Directory.CreateDirectory(contentPagesRoot);
        created += WriteFile(Path.Combine(contentPagesRoot, "index.md"),
@"---
title: Welcome
description: Starter page generated by PowerForge.Web.
---

# Welcome

This site was scaffolded by PowerForge.Web.
");

        if (multiProjectApiSuiteStarter)
        {
            var suitePagesRoot = Path.Combine(contentPagesRoot, "projects");
            Directory.CreateDirectory(suitePagesRoot);
            created += WriteFile(Path.Combine(suitePagesRoot, "api-suite.md"),
@"---
title: API Suite
description: Placeholder landing page for the multi-project API suite.
---

# API Suite

This starter reserves `/projects/api-suite/` for the engine-owned API suite portal.

Next steps:

- add project entries in `data/projects/catalog.json`
- place generated API sources under `projects-sources/`
- run `powerforge-web pipeline --config .\pipeline.json --mode dev`

Once `project-apidocs` has real inputs, it will replace this placeholder route with the generated suite portal.
");
        }

        var contentDocsRoot = Path.Combine(fullOutput, "content", "docs");
        Directory.CreateDirectory(contentDocsRoot);
        created += WriteFile(Path.Combine(contentDocsRoot, "index.md"),
@"---
title: Documentation
description: Getting started guides and references.
layout: docs
meta.eyebrow: Documentation
---

# Documentation

Start here to learn how the engine works, then expand your docs and API references.
");

        if (multiProjectApiSuiteStarter)
        {
            created += WriteFile(Path.Combine(contentDocsRoot, "api-suite.md"),
@"---
title: API Suite Setup
description: How to configure the scaffolded multi-project API suite.
layout: docs
meta.eyebrow: API Docs
---

# API Suite Setup

This starter configures `project-apidocs` plus the recommended suite metadata files.

## Fill in the catalog

Edit `data/projects/catalog.json` and add one entry per project/module.

## Add project sources

Place generated XML/help assets under `projects-sources/` so `project-apidocs` can resolve them.

## Add curated guidance

- use `apiDocs.quickStartTypes` for the main entry points of each project
- use `apiDocs.relatedContentManifest` or `apiDocs.relatedContentManifests` to attach authored guides and samples
- update `data/projects/api-suite-narrative.json` so the suite portal has a strong `Start Here` path
");

            var docsProjectsRoot = Path.Combine(contentDocsRoot, "projects");
            Directory.CreateDirectory(docsProjectsRoot);
            created += WriteFile(Path.Combine(docsProjectsRoot, "api-guide-template.md"),
@"---
title: Project API Guide Template
description: Duplicate this guide when attaching curated related content to a project API.
layout: docs
meta.eyebrow: API Guides
---

# Project API Guide Template

Duplicate this page for a real project guide, then point a project related-content manifest entry at the new route.

Checklist:

- rename the file to match the project and workflow
- explain which type or command should be opened first
- include a short example or setup flow
- add the final URL to the related-content manifest you attach in `apiDocs.relatedContentManifest`
");

            if (firstSuiteProject is not null)
            {
                created += WriteFile(Path.Combine(docsProjectsRoot, $"{firstSuiteProject.Slug}-quick-start.md"),
$@"---
title: {firstSuiteProject.Name} Quick Start
description: Starter quick-start guide for the first scaffolded suite project.
layout: docs
meta.eyebrow: API Guides
---

# {firstSuiteProject.Name} Quick Start

This page was generated from the suite starter so the first project already has a real guide target.

## Start with the main API entry point

- surface: `{firstSuiteProject.Surface}`
- suggested quick-start symbol: `{firstSuiteProject.QuickStartTarget}`

## Next steps

- replace this starter text with a real onboarding flow
- add a practical example for `{firstSuiteProject.QuickStartTarget}`
- keep `data/projects/{firstSuiteProject.RelatedContentFileName}` aligned with the final guide URLs
");
            }
        }

        var contentBlogRoot = Path.Combine(fullOutput, "content", "blog");
        Directory.CreateDirectory(contentBlogRoot);
        created += WriteFile(Path.Combine(contentBlogRoot, "_index.md"),
@"---
title: Blog
description: Product updates and release notes.
meta.eyebrow: Blog
---

# Blog

Latest updates from the project.
");
        created += WriteFile(Path.Combine(contentBlogRoot, "hello-world.md"),
@"---
title: Hello from PowerForge.Web
description: First blog post generated by the scaffold.
date: 2026-01-01
layout: post
tags:
  - release
  - announcement
categories:
  - updates
---

# Hello from PowerForge.Web

Use this post as a starting point for changelogs, release notes, and engineering updates.
");
        created += WriteFile(Path.Combine(contentBlogRoot, "roadmap-update.md"),
@"---
title: Roadmap update
description: A short sample update post for pagination and list previews.
date: 2026-01-08
layout: post
tags:
  - roadmap
  - planning
categories:
  - updates
---

# Roadmap update

This second sample entry helps verify list layouts, pagination, and feeds.
");

        var contentNewsRoot = Path.Combine(fullOutput, "content", "news");
        Directory.CreateDirectory(contentNewsRoot);
        created += WriteFile(Path.Combine(contentNewsRoot, "_index.md"),
@"---
title: News
description: Product announcements and company updates.
meta.eyebrow: News
---

# News

Official announcements and release milestones.
");
        created += WriteFile(Path.Combine(contentNewsRoot, "release-1-0.md"),
@"---
title: Version 1.0 announced
description: First stable release announcement generated by the scaffold.
date: 2026-01-10
layout: post
tags:
  - release
  - stable
categories:
  - announcements
---

# Version 1.0 announced

Use this sample news post to publish release announcements and milestones.
");

        var dataRoot = Path.Combine(fullOutput, "data");
        Directory.CreateDirectory(dataRoot);
        created += WriteFile(Path.Combine(dataRoot, "sections.json"),
@"{
  ""features"": {
    ""label"": ""Features"",
    ""title"": ""Built for modern teams"",
    ""description"": ""Use JSON data for repeatable blocks.""
  }
}
");

        if (multiProjectApiSuiteStarter)
        {
            var projectsDataRoot = Path.Combine(dataRoot, "projects");
            Directory.CreateDirectory(projectsDataRoot);
            created += WriteFile(Path.Combine(projectsDataRoot, "catalog.json"),
firstSuiteProject is null
? @"{
  ""projects"": []
}
"
: $@"{{
  ""projects"": [
    {{
      ""slug"": ""{firstSuiteProject.Slug}"",
      ""name"": ""{firstSuiteProject.Name}"",
      ""summary"": ""Replace this with the public summary shown in the suite portal."",
      ""hubPath"": ""/projects/{firstSuiteProject.Slug}/"",
      ""surfaces"": {{
        ""{firstSuiteProject.SurfaceCatalogKey}"": true
      }},
      ""apiDocs"": {{
        ""quickStartTypes"": ""{firstSuiteProject.QuickStartType}"",
        ""relatedContentManifest"": ""./data/projects/{firstSuiteProject.RelatedContentFileName}""
      }}
    }}
  ]
}}
");
            created += WriteFile(Path.Combine(projectsDataRoot, "catalog.project-template.json"),
@"{
  ""slug"": ""sample-project"",
  ""name"": ""Sample Project"",
  ""summary"": ""Replace this with the public summary shown in the suite portal."",
  ""hubPath"": ""/projects/sample-project/"",
  ""surfaces"": {
    ""apiPowerShell"": true
  },
  ""apiDocs"": {
    ""quickStartTypes"": ""Invoke-SampleProjectAction"",
    ""relatedContentManifest"": ""./data/projects/sample-project-api-guides.json""
  }
}
");
            created += WriteFile(Path.Combine(projectsDataRoot, "api-suite-narrative.json"),
firstSuiteProject is null
? @"{
  ""summary"": ""Use this suite portal to choose the right project API and follow the main onboarding flow."",
  ""sections"": [
    {
      ""title"": ""Start Here"",
      ""summary"": ""Wire your project catalog, then attach curated guides and quick-start entry points."",
      ""items"": [
        {
          ""title"": ""Configure the scaffolded API suite"",
          ""url"": ""/docs/api-suite/"",
          ""kind"": ""workflow"",
          ""audience"": ""Maintainers"",
          ""estimatedTime"": ""10 min""
        }
      ]
    }
  ]
}
"
: $@"{{
  ""summary"": ""Use this suite portal to choose the right project API and start with {firstSuiteProject.Name}."",
  ""sections"": [
    {{
      ""title"": ""Start Here"",
      ""summary"": ""Begin with the first scaffolded project, then expand the suite as more APIs are added."",
      ""items"": [
        {{
          ""title"": ""Open the {firstSuiteProject.Name} quick start"",
          ""url"": ""/docs/projects/{firstSuiteProject.Slug}-quick-start/"",
          ""kind"": ""workflow"",
          ""audience"": ""Maintainers"",
          ""estimatedTime"": ""10 min"",
          ""projects"": [ ""{firstSuiteProject.Slug}"" ]
        }}
      ]
    }}
  ]
}}
");
            created += WriteFile(Path.Combine(projectsDataRoot, "sample-project-api-guides.json"),
@"{
  ""entries"": [
    {
      ""title"": ""Sample Project quick start"",
      ""url"": ""/docs/projects/api-guide-template/"",
      ""summary"": ""Start with [[xref:ps:Invoke-SampleProjectAction]] before exploring the full reference."",
      ""kind"": ""guide"",
      ""targets"": [ ""ps:Invoke-SampleProjectAction"" ]
    }
  ]
}
");
            if (firstSuiteProject is not null)
            {
                created += WriteFile(Path.Combine(projectsDataRoot, firstSuiteProject.RelatedContentFileName),
$@"{{
  ""entries"": [
    {{
      ""title"": ""{firstSuiteProject.Name} quick start"",
      ""url"": ""/docs/projects/{firstSuiteProject.Slug}-quick-start/"",
      ""summary"": ""Start with [[xref:{firstSuiteProject.QuickStartTarget}]] before exploring the full reference."",
      ""kind"": ""guide"",
      ""targets"": [ ""{firstSuiteProject.QuickStartTarget}"" ]
    }}
  ]
}}
");
            }
        }

        var themeRoot = Path.Combine(fullOutput, "themes", themeName);
        var layoutsRoot = Path.Combine(themeRoot, "layouts");
        var partialsRoot = Path.Combine(themeRoot, "partials");
        var assetsRoot = Path.Combine(themeRoot, "assets");
        var scriptsRoot = Path.Combine(themeRoot, "scripts");
        Directory.CreateDirectory(layoutsRoot);
        Directory.CreateDirectory(partialsRoot);
        Directory.CreateDirectory(assetsRoot);
        Directory.CreateDirectory(scriptsRoot);

        var themeFeatures = new List<string> { "docs", "blog", "news" };
        if (multiProjectApiSuiteStarter)
            themeFeatures.Add("apiDocs");

        var featureContracts = new Dictionary<string, ThemeFeatureContractSpec>(StringComparer.OrdinalIgnoreCase)
        {
            ["docs"] = new ThemeFeatureContractSpec
            {
                RequiredLayouts = new[] { "docs" }
            }
        };

        if (multiProjectApiSuiteStarter)
        {
            featureContracts["apiDocs"] = new ThemeFeatureContractSpec
            {
                RequiredPartials = new[] { "api-header", "api-footer", "theme-tokens" },
                CssHrefs = new[]
                {
                    $"/themes/{themeName}/assets/app.css",
                    $"/themes/{themeName}/assets/api.css"
                },
                RequiredCssSelectors = new[]
                {
                    ".pf-api-header",
                    ".pf-api-footer",
                    ".pf-api-shell",
                    ".pf-api-suite-hero",
                    ".pf-api-related-content"
                }
            };
        }

        var manifest = new ThemeManifest
        {
            Name = themeName,
            SchemaVersion = 2,
            Engine = engine,
            Features = themeFeatures.ToArray(),
            FeatureContracts = featureContracts,
            DefaultLayout = "base",
            LayoutsPath = "layouts",
            PartialsPath = "partials",
            AssetsPath = "assets",
            ScriptsPath = "scripts",
            Slots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["site-header"] = "header",
                ["site-footer"] = "footer",
                ["theme-tokens"] = "theme-tokens"
            },
            Tokens = isScriban
                ? new Dictionary<string, object?>
                {
                    ["color"] = new Dictionary<string, object?>
                    {
                        ["bg"] = "#0f172a",
                        ["panel"] = "rgba(15, 23, 42, 0.85)",
                        ["ink"] = "#e2e8f0",
                        ["muted"] = "#94a3b8",
                        ["accent"] = "#38bdf8",
                        ["border"] = "rgba(148, 163, 184, 0.2)"
                    },
                    ["radius"] = new Dictionary<string, object?>
                    {
                        ["base"] = "18px",
                        ["sm"] = "12px"
                    },
                    ["font"] = new Dictionary<string, object?>
                    {
                        ["body"] = "Inter, Segoe UI, sans-serif",
                        ["display"] = "Space Grotesk, Segoe UI, sans-serif",
                        ["mono"] = "JetBrains Mono, Consolas, monospace"
                    },
                    ["layout"] = new Dictionary<string, object?>
                    {
                        ["maxWidth"] = "1080px"
                    }
                }
                : null
        };
        var manifestJson = JsonSerializer.Serialize(manifest, WebJson.Options);
        manifestJson = InsertSchema(manifestJson, DefaultSchemaBaseUrl + "powerforge.web.themespec.schema.json");
        created += WriteFile(Path.Combine(themeRoot, "theme.manifest.json"), manifestJson);

        var layout = isScriban
            ? ScribanLayoutTemplate
            : SimpleLayoutTemplate;
        created += WriteFile(Path.Combine(layoutsRoot, "base.html"), layout);
        created += WriteFile(Path.Combine(layoutsRoot, "page.html"), layout);
        created += WriteFile(Path.Combine(layoutsRoot, "docs.html"), layout);
        created += WriteFile(Path.Combine(layoutsRoot, "list.html"), isScriban ? ScribanListLayoutTemplate : layout);
        created += WriteFile(Path.Combine(layoutsRoot, "post.html"), isScriban ? ScribanPostLayoutTemplate : layout);
        created += WriteFile(Path.Combine(layoutsRoot, "taxonomy.html"), isScriban ? ScribanTaxonomyLayoutTemplate : layout);
        created += WriteFile(Path.Combine(layoutsRoot, "term.html"), isScriban ? ScribanTermLayoutTemplate : layout);

        if (isScriban)
        {
            created += WriteFile(Path.Combine(partialsRoot, "header.html"),
@"<header class=""pf-header"">
  <div class=""pf-container pf-header-inner"">
    <div class=""pf-brand"">{{ site.name }}</div>
    <nav class=""pf-nav"">
      {{ pf.nav_links ""main"" }}
    </nav>
  </div>
</header>
");
            created += WriteFile(Path.Combine(partialsRoot, "footer.html"),
@"<footer class=""pf-footer"">
  <div class=""pf-container"">
    <span>Powered by PowerForge.Web</span>
  </div>
</footer>
");
            created += WriteFile(Path.Combine(partialsRoot, "theme-tokens.html"),
@"<style>
:root {
  --pf-bg: {{ data.theme.tokens.color.bg }};
  --pf-panel: {{ data.theme.tokens.color.panel }};
  --pf-ink: {{ data.theme.tokens.color.ink }};
  --pf-muted: {{ data.theme.tokens.color.muted }};
  --pf-accent: {{ data.theme.tokens.color.accent }};
  --pf-border: {{ data.theme.tokens.color.border }};
  --pf-radius: {{ data.theme.tokens.radius.base }};
  --pf-radius-sm: {{ data.theme.tokens.radius.sm }};
  --pf-font-body: {{ data.theme.tokens.font.body }};
  --pf-font-display: {{ data.theme.tokens.font.display }};
  --pf-font-mono: {{ data.theme.tokens.font.mono }};
  --pf-max-width: {{ data.theme.tokens.layout.maxWidth }};
}
</style>
");

            if (multiProjectApiSuiteStarter)
            {
                created += WriteFile(Path.Combine(partialsRoot, "api-header.html"),
@"<header class=""pf-header pf-api-header"">
  <div class=""pf-container pf-header-inner pf-api-shell"">
    <div class=""pf-brand"">{{ site.name }}</div>
    <nav class=""pf-nav"" aria-label=""API navigation"">
      {{ pf.nav_links ""main"" }}
    </nav>
  </div>
</header>
");
                created += WriteFile(Path.Combine(partialsRoot, "api-footer.html"),
@"<footer class=""pf-footer pf-api-footer"">
  <div class=""pf-container pf-api-shell"">
    <span>Powered by PowerForge.Web</span>
  </div>
</footer>
");
            }
        }
        else
        {
            var simpleNavLinks = multiProjectApiSuiteStarter
                ? @"      <a href=""/"">Home</a>
      <a href=""/docs/"">Docs</a>
      <a href=""/projects/api-suite/"">API</a>
      <a href=""/blog/"">Blog</a>
      <a href=""/news/"">News</a>"
                : @"      <a href=""/"">Home</a>
      <a href=""/docs/"">Docs</a>
      <a href=""/blog/"">Blog</a>
      <a href=""/news/"">News</a>";

            created += WriteFile(Path.Combine(partialsRoot, "header.html"),
@"<header class=""pf-header"">
  <div class=""pf-container pf-header-inner"">
    <div class=""pf-brand"">{{SITE_NAME}}</div>
    <nav class=""pf-nav"">
      <!-- Simple engine: use hard-coded links or migrate to Scriban for full navigation runtime. -->
" + simpleNavLinks + @"
    </nav>
  </div>
</header>
");
            created += WriteFile(Path.Combine(partialsRoot, "footer.html"),
@"<footer class=""pf-footer"">
  <div class=""pf-container"">
    <span>Powered by PowerForge.Web</span>
  </div>
</footer>
");
            created += WriteFile(Path.Combine(partialsRoot, "theme-tokens.html"),
@"<style>
:root {
  --pf-bg: #0f172a;
  --pf-panel: rgba(15, 23, 42, 0.85);
  --pf-ink: #e2e8f0;
  --pf-muted: #94a3b8;
  --pf-accent: #38bdf8;
  --pf-border: rgba(148, 163, 184, 0.2);
  --pf-radius: 18px;
  --pf-radius-sm: 12px;
  --pf-font-body: Segoe UI, sans-serif;
  --pf-font-display: Segoe UI, sans-serif;
  --pf-font-mono: Consolas, monospace;
  --pf-max-width: 1080px;
}
</style>
");

            if (multiProjectApiSuiteStarter)
            {
                created += WriteFile(Path.Combine(partialsRoot, "api-header.html"),
@"<header class=""pf-header pf-api-header"">
  <div class=""pf-container pf-header-inner pf-api-shell"">
    <div class=""pf-brand"">{{SITE_NAME}}</div>
    <nav class=""pf-nav"" aria-label=""API navigation"">
" + simpleNavLinks + @"
    </nav>
  </div>
</header>
");
                created += WriteFile(Path.Combine(partialsRoot, "api-footer.html"),
@"<footer class=""pf-footer pf-api-footer"">
  <div class=""pf-container pf-api-shell"">
    <span>Powered by PowerForge.Web</span>
  </div>
</footer>
");
            }
        }

        created += WriteFile(Path.Combine(themeRoot, "critical.css"),
@"body { font-family: var(--pf-font-body, system-ui, sans-serif); margin: 0; background: var(--pf-bg, #0f172a); color: var(--pf-ink, #e2e8f0); }
.pf-header, .pf-footer { padding: 16px 24px; background: rgba(15, 23, 42, 0.8); border-bottom: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); }
.pf-nav a { margin-right: 12px; text-decoration: none; color: var(--pf-muted, #94a3b8); }
.pf-web-content { padding: 24px; }
");

        created += WriteFile(Path.Combine(assetsRoot, "app.css"),
@"* { box-sizing: border-box; }
body { margin: 0; font-family: var(--pf-font-body, system-ui, sans-serif); background: var(--pf-bg, #0f172a); color: var(--pf-ink, #e2e8f0); }
a { color: inherit; text-decoration: none; }
.pf-container { max-width: var(--pf-max-width, 1080px); margin: 0 auto; padding: 0 24px; }
.pf-header-inner { display: flex; align-items: center; justify-content: space-between; gap: 16px; }
.pf-brand { font-family: var(--pf-font-display, system-ui, sans-serif); color: var(--pf-accent, #38bdf8); letter-spacing: 0.08em; text-transform: uppercase; }
.pf-nav { display: flex; gap: 16px; font-size: 0.95rem; color: var(--pf-muted, #94a3b8); }
.pf-web-content { padding: 32px 0 60px; }
.pf-content { background: var(--pf-panel, rgba(15, 23, 42, 0.85)); border: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); border-radius: var(--pf-radius, 18px); padding: 24px 28px; }
.pf-editorial-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 16px; margin-top: 18px; }
.pf-editorial-grid--hero .pf-editorial-card--hero { grid-column: 1 / -1; }
.pf-editorial-grid--compact { grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); }
.pf-editorial-grid--featured .pf-editorial-card--featured { border-color: rgba(56, 189, 248, 0.45); }
.pf-editorial-card { display: block; background: rgba(15, 23, 42, 0.72); border: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); border-radius: var(--pf-radius-sm, 12px); padding: 16px; color: inherit; transition: border-color .15s ease, transform .15s ease; }
.pf-editorial-card:hover { border-color: var(--pf-accent, #38bdf8); transform: translateY(-1px); }
.pf-editorial-card--compact .pf-editorial-summary { font-size: .92rem; }
.pf-editorial-card--hero h2,
.pf-editorial-card--hero h3 { font-size: 1.35rem; margin-top: 0; }
.pf-editorial-card--featured h2,
.pf-editorial-card--featured h3 { color: var(--pf-accent, #38bdf8); }
.pf-editorial-card-media { display: block; width: 100%; border-radius: 10px; overflow: hidden; margin-bottom: 12px; background: rgba(15, 23, 42, 0.5); }
.pf-editorial-card-image { width: 100%; height: 100%; object-fit: cover; display: block; }
.pf-editorial-meta { display: flex; gap: 10px; align-items: center; color: var(--pf-muted, #94a3b8); font-size: .85rem; margin-bottom: 10px; }
.pf-editorial-summary { color: var(--pf-muted, #94a3b8); margin: 0; }
.pf-editorial-tags { margin-top: 12px; display: flex; flex-wrap: wrap; gap: 8px; }
.pf-chip { border: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); border-radius: 999px; padding: 2px 8px; font-size: .78rem; color: var(--pf-muted, #94a3b8); }
.pf-pagination { margin-top: 18px; display: flex; justify-content: space-between; gap: 12px; }
.pf-pagination a { color: var(--pf-accent, #38bdf8); }
.pf-post-nav { margin-top: 28px; border-top: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); padding-top: 18px; display: grid; gap: 16px; }
.pf-post-nav-top { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 12px; align-items: center; }
.pf-post-nav-back { color: var(--pf-accent, #38bdf8); font-size: .92rem; }
.pf-post-nav-links { display: flex; flex-wrap: wrap; gap: 12px; }
.pf-post-nav-links a { color: var(--pf-muted, #94a3b8); font-size: .92rem; }
.pf-post-nav-links a:hover { color: var(--pf-accent, #38bdf8); }
.pf-post-nav-related h2 { margin: 0 0 8px; font-size: 1.05rem; }
.pf-post-nav-related ul { margin: 0; padding-left: 18px; display: grid; gap: 6px; }
.pf-post-nav-related a { color: var(--pf-muted, #94a3b8); }
.pf-post-nav-related a:hover { color: var(--pf-accent, #38bdf8); }
");

        if (multiProjectApiSuiteStarter)
        {
            created += WriteFile(Path.Combine(assetsRoot, "api.css"),
@"body.api-docs,
body.pf-api-body { background:
  radial-gradient(circle at top right, rgba(56, 189, 248, 0.14), transparent 30%),
  var(--pf-bg, #0f172a); }
.pf-api-header,
.pf-api-footer { background: rgba(15, 23, 42, 0.82); border-color: var(--pf-border, rgba(148, 163, 184, 0.2)); }
.pf-api-shell { width: 100%; }
.pf-api-suite-hero,
.pf-api-related-content,
.pf-api-narrative,
.pf-api-usage { background: rgba(15, 23, 42, 0.58); border: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); border-radius: var(--pf-radius, 18px); padding: 20px; }
.pf-api-suite-hero h1,
.pf-api-related-content h2,
.pf-api-narrative h2,
.pf-api-usage h2 { margin-top: 0; }
.pf-api-related-content a,
.pf-api-narrative a,
.pf-api-usage a { color: var(--pf-accent, #38bdf8); }
");
        }

        var siteFeatures = new List<string> { "docs", "blog", "news" };
        if (multiProjectApiSuiteStarter)
            siteFeatures.Add("apiDocs");

        var mainMenuItems = new List<MenuItemSpec>
        {
            new() { Title = "Home", Url = "/" },
            new() { Title = "Docs", Url = "/docs/" }
        };
        if (multiProjectApiSuiteStarter)
            mainMenuItems.Add(new MenuItemSpec { Title = "API", Url = "/projects/api-suite/" });
        mainMenuItems.Add(new MenuItemSpec { Title = "Blog", Url = "/blog/" });
        mainMenuItems.Add(new MenuItemSpec { Title = "News", Url = "/news/" });

        var siteSpec = new SiteSpec
        {
            SchemaVersion = 1,
            Name = name,
            BaseUrl = url,
            DefaultTheme = themeName,
            ThemeEngine = string.IsNullOrWhiteSpace(themeEngine) ? null : engine,
            TrailingSlash = TrailingSlashMode.Always,
            ContentRoot = "content",
            ThemesRoot = "themes",
            DataRoot = "data",
            Features = siteFeatures.ToArray(),
            Collections = new[]
            {
                new CollectionSpec
                {
                    Name = "pages",
                    Preset = "pages",
                    Input = "content/pages",
                    Output = "/",
                    DefaultLayout = "page",
                    Include = new[] { "*.md", "**/*.md" }
                },
                new CollectionSpec
                {
                    Name = "docs",
                    Preset = "docs",
                    Input = "content/docs",
                    Output = "/docs",
                    DefaultLayout = "docs",
                    Include = new[] { "*.md", "**/*.md" }
                },
                new CollectionSpec
                {
                    Name = "blog",
                    Preset = "blog",
                    Input = "content/blog",
                    Output = "/blog",
                    DefaultLayout = "post",
                    ListLayout = "list",
                    Include = new[] { "*.md", "**/*.md" },
                    EditorialCards = new EditorialCardsSpec
                    {
                        ImageAspect = "16/9",
                        Variant = "hero"
                    }
                },
                new CollectionSpec
                {
                    Name = "news",
                    Preset = "news",
                    Input = "content/news",
                    Output = "/news",
                    DefaultLayout = "post",
                    ListLayout = "list",
                    Include = new[] { "*.md", "**/*.md" },
                    EditorialCards = new EditorialCardsSpec
                    {
                        ImageAspect = "16/9",
                        Variant = "compact"
                    }
                }
            },
            Taxonomies = new[]
            {
                new TaxonomySpec
                {
                    Name = "tags",
                    BasePath = "/tags",
                    ListLayout = "taxonomy",
                    TermLayout = "term"
                },
                new TaxonomySpec
                {
                    Name = "categories",
                    BasePath = "/categories",
                    ListLayout = "taxonomy",
                    TermLayout = "term"
                }
            },
            Navigation = new NavigationSpec
            {
                Menus = new[]
                {
                    new MenuSpec
                    {
                        Name = "main",
                        Label = "Main",
                        Items = mainMenuItems.ToArray()
                    }
                },
                Auto = new[]
                {
                    new NavigationAutoSpec
                    {
                        Collection = "docs",
                        Menu = "docs",
                        MaxDepth = 3,
                        IncludeIndex = true
                    }
                }
            },
            AssetRegistry = new AssetRegistrySpec
            {
                Bundles = new[]
                {
                    new AssetBundleSpec
                    {
                        Name = "global",
                        Css = new[] { $"/themes/{themeName}/assets/app.css" },
                        Js = Array.Empty<string>()
                    }
                },
                RouteBundles = new[]
                {
                    new RouteBundleSpec
                    {
                        Match = "/**",
                        Bundles = new[] { "global" }
                    }
                },
                CriticalCss = new[]
                {
                    new CriticalCssSpec
                    {
                        Name = "base",
                        Path = $"themes/{themeName}/critical.css"
                    }
                }
            },
            A11y = new A11ySpec
            {
                SkipLinkLabel = "Skip to content",
                ExternalLinkLabel = "Opens in a new tab",
                NavToggleLabel = "Toggle navigation",
                SearchLabel = "Search"
            },
            LinkRules = new LinkRulesSpec
            {
                ExternalRel = "noopener",
                ExternalTarget = "_blank",
                AddExternalIcon = true
            }
        };

        var siteJson = JsonSerializer.Serialize(siteSpec, WebJson.Options);
        siteJson = InsertSchema(siteJson, DefaultSchemaBaseUrl + "powerforge.web.sitespec.schema.json");
        created += WriteFile(Path.Combine(fullOutput, "site.json"), siteJson);

        var configPresetsRoot = Path.Combine(fullOutput, "config", "presets");
        Directory.CreateDirectory(configPresetsRoot);

        // Keep the starter pipeline tiny and reusable by inheriting a preset.
        var projectApiDocsStepJson = multiProjectApiSuiteStarter
            ? $$"""
                { "task": "project-apidocs", "id": "project-apis", "dependsOn": "build-site", "catalog": "./data/projects/catalog.json", "sourcesRoot": "./projects-sources", "outRoot": "./_site/projects", "template": "docs", "format": "both", "suiteTitle": "Project APIs", "suiteNarrativeManifest": "./data/projects/api-suite-narrative.json", "css": "/themes/{{themeName}}/assets/app.css,/themes/{{themeName}}/assets/api.css" },

"""
            : string.Empty;

        var pipelinePresetJson = InsertSchema(
            $$"""
            {
              "cache": true,
              "cachePath": "./.powerforge/pipeline-cache.json",
              "profile": true,
              "profilePath": "./_reports/pipeline-profile.json",
              "steps": [
                { "task": "engine-lock", "id": "engine-lock-ci", "modes": ["ci"], "operation": "verify", "path": "./.powerforge/engine-lock.json", "failOnDrift": true, "requireImmutableRef": true, "reportPath": "./_reports/engine-lock.json", "summaryPath": "./_reports/engine-lock.md" },
                { "task": "build", "id": "build-site", "config": "./site.json", "out": "./_site", "clean": true },
                {{projectApiDocsStepJson}}                { "task": "sitemap", "id": "sitemap", "dependsOn": "build-site", "config": "./site.json", "siteRoot": "./_site", "baseUrl": "{{baseUrl}}", "json": true, "jsonOut": "./_site/sitemap/index.json" },
                { "task": "indexnow", "id": "indexnow-ci", "dependsOn": "sitemap", "modes": ["ci"], "sitemap": "./_site/sitemap.xml", "keyEnv": "INDEXNOW_KEY", "optionalKey": true, "continueOnError": true, "reportPath": "./_reports/indexnow.json", "summaryPath": "./_reports/indexnow.md" },
                { "task": "github-artifacts-prune", "id": "github-artifacts-hygiene-ci", "modes": ["ci"], "tokenEnv": "GITHUB_TOKEN", "optional": true, "dryRun": true, "reportPath": "./_reports/github-artifacts.json", "summaryPath": "./_reports/github-artifacts.md" },

                { "task": "verify", "id": "verify-dev", "dependsOn": "build-site", "config": "./site.json", "skipModes": ["ci"], "warningPreviewCount": 5, "errorPreviewCount": 5 },
                { "task": "verify", "id": "verify-ci", "dependsOn": "build-site", "config": "./site.json", "modes": ["ci"], "baseline": "./.powerforge/verify-baseline.json", "failOnNewWarnings": true, "failOnNavLint": true, "failOnThemeContract": true, "warningPreviewCount": 10, "errorPreviewCount": 10 },

                {
                  "task": "audit",
                  "id": "audit-ci",
                  "dependsOn": "build-site",
                  "siteRoot": "./_site",
                  "modes": ["ci"],
                  "summary": true,
                  "sarif": true,
                  "baseline": "./.powerforge/audit-baseline.json",
                  "failOnNewIssues": true,
                  "requiredRoutes": "/404.html,/",
                  "requireExplicitChecks": true,
                  "checkSeoMeta": false,
                  "checkNetworkHints": true,
                  "checkRenderBlockingResources": true,
                  "checkHeadingOrder": true,
                  "checkLinkPurposeConsistency": true,
                  "checkMediaEmbeds": true,
                  "rendered": true,
                  "renderedMaxPages": 2,
                  "renderedEnsureInstalled": true,
                  "renderedInclude": "index.html,404.html"
                }
              ]
            }
            """,
            DefaultSchemaBaseUrl + "powerforge.web.pipelinespec.schema.json");
        created += WriteFile(Path.Combine(configPresetsRoot, "pipeline.web-quality.json"), pipelinePresetJson);

        var maintenancePresetJson = InsertSchema(
            $$"""
            {
              "steps": [
                {
                  "task": "github-artifacts-prune",
                  "id": "github-artifacts-maintenance",
                  "tokenEnv": "GITHUB_TOKEN",
                  "optional": true,
                  "apply": true,
                  "continueOnError": true,
                  "keep": {{maintenanceBudgets.Keep}},
                  "maxAgeDays": {{maintenanceBudgets.MaxAgeDays}},
                  "maxDelete": {{maintenanceBudgets.MaxDelete}},
                  "reportPath": "./_reports/github-artifacts-maintenance.json",
                  "summaryPath": "./_reports/github-artifacts-maintenance.md"
                }
              ]
            }
            """,
            DefaultSchemaBaseUrl + "powerforge.web.pipelinespec.schema.json");
        created += WriteFile(Path.Combine(configPresetsRoot, "pipeline.web-maintenance.json"), maintenancePresetJson);

        var pipelineJson = InsertSchema(
            """
            {
              "extends": "./config/presets/pipeline.web-quality.json"
            }
            """,
            DefaultSchemaBaseUrl + "powerforge.web.pipelinespec.schema.json");
        created += WriteFile(Path.Combine(fullOutput, "pipeline.json"), pipelineJson);

        var maintenancePipelineJson = InsertSchema(
            """
            {
              "extends": "./config/presets/pipeline.web-maintenance.json"
            }
            """,
            DefaultSchemaBaseUrl + "powerforge.web.pipelinespec.schema.json");
        created += WriteFile(Path.Combine(fullOutput, "pipeline.maintenance.json"), maintenancePipelineJson);

        if (multiProjectApiSuiteStarter)
        {
            var projectsSourcesRoot = Path.Combine(fullOutput, "projects-sources");
            Directory.CreateDirectory(projectsSourcesRoot);
            created += WriteFile(Path.Combine(projectsSourcesRoot, "README.md"),
$@"# Project API Sources

Place generated API inputs for each project here.

Examples:

- C# projects: XML docs + assemblies that `project-apidocs` can map from the catalog
- PowerShell projects: external help XML, markdown examples, and any curated related-content manifests

Recommended next steps:

- edit `data/projects/catalog.json`
- copy `data/projects/catalog.project-template.json` into `catalog.json` and tailor it per project
- duplicate `data/projects/sample-project-api-guides.json` for each real project
- set `apiDocs.quickStartTypes` on each project entry
- set `apiDocs.relatedContentManifest` or `apiDocs.relatedContentManifests`
- update `data/projects/api-suite-narrative.json`
{(firstSuiteProject is null ? string.Empty : $@"

First scaffolded project:

- slug: `{firstSuiteProject.Slug}`
- surface: `{firstSuiteProject.Surface}`
- guide: `content/docs/projects/{firstSuiteProject.Slug}-quick-start.md`
- related content: `data/projects/{firstSuiteProject.RelatedContentFileName}`")}
");

            if (firstSuiteProject is not null)
            {
                var firstProjectSourcesRoot = Path.Combine(projectsSourcesRoot, firstSuiteProject.Slug);
                Directory.CreateDirectory(firstProjectSourcesRoot);
                created += WriteFile(Path.Combine(firstProjectSourcesRoot, "README.md"),
$@"# {firstSuiteProject.Name} API Sources

Place the generated `{firstSuiteProject.Surface}` API inputs for `{firstSuiteProject.Slug}` here.

Suggested starter contract:

- quick-start symbol: `{firstSuiteProject.QuickStartTarget}`
- related content manifest: `data/projects/{firstSuiteProject.RelatedContentFileName}`
- guide page: `content/docs/projects/{firstSuiteProject.Slug}-quick-start.md`
");

                if (firstSuiteProject.Surface.Equals("powershell", StringComparison.OrdinalIgnoreCase))
                {
                    var powerShellSourceRoot = Path.Combine(firstProjectSourcesRoot, "powershell");
                    var powerShellExamplesRoot = Path.Combine(powerShellSourceRoot, "examples");
                    var powerShellTemplatesRoot = Path.Combine(powerShellSourceRoot, "templates");
                    Directory.CreateDirectory(powerShellExamplesRoot);
                    Directory.CreateDirectory(powerShellTemplatesRoot);
                    created += WriteFile(Path.Combine(powerShellSourceRoot, "README.md"),
$@"# {firstSuiteProject.Name} PowerShell API Inputs

Place the generated PowerShell API inputs for `{firstSuiteProject.Slug}` here.

Expected files:

- `*-help.xml` external help
- `*.psd1` module manifest
- optional `command-metadata.json`
- optional example scripts under `examples/`

This folder shape matches the default `project-apidocs` discovery rules.

Safe starter templates live under `templates/` and intentionally do not use discoverable file extensions.
Use `promote-from-templates.ps1` when you want to materialize them into real API inputs.
");
                    created += WriteFile(Path.Combine(powerShellExamplesRoot, ".gitkeep"), string.Empty);
                    created += WriteFile(Path.Combine(powerShellTemplatesRoot, $"{firstSuiteProject.QuickStartType}.ps1.template"),
$@"# Starter example for {firstSuiteProject.QuickStartType}

{firstSuiteProject.QuickStartType} -Name 'Demo'
");
                    created += WriteFile(Path.Combine(powerShellTemplatesRoot, $"{firstSuiteProject.Slug}-help.xml.template"),
$@"<helpItems moduleName=""{firstSuiteProject.Name}"">
  <command:command xmlns:maml=""http://schemas.microsoft.com/maml/2004/10""
                   xmlns:command=""http://schemas.microsoft.com/maml/dev/command/2004/10""
                   xmlns:dev=""http://schemas.microsoft.com/maml/dev/2004/10"">
    <command:details>
      <command:name>{firstSuiteProject.QuickStartType}</command:name>
      <maml:description>
        <maml:para>Replace this starter text with real help content.</maml:para>
      </maml:description>
    </command:details>
  </command:command>
</helpItems>
");
                    created += WriteFile(Path.Combine(powerShellTemplatesRoot, $"{firstSuiteProject.Slug}.psd1.template"),
$@"@{{
    RootModule = '{firstSuiteProject.Slug}.psm1'
    ModuleVersion = '0.0.1'
    GUID = '00000000-0000-0000-0000-000000000000'
}}
");
                    created += WriteFile(Path.Combine(powerShellTemplatesRoot, "command-metadata.json.template"),
$@"{{
  ""commands"": [
    {{
      ""name"": ""{firstSuiteProject.QuickStartType}"",
      ""kind"": ""Function"",
      ""aliases"": []
    }}
  ]
}}
");
                    created += WriteFile(Path.Combine(powerShellSourceRoot, "promote-from-templates.ps1"),
$@"[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [string] $HelpOutputName = '{firstSuiteProject.Slug}-help.xml',
    [string] $ManifestOutputName = '{firstSuiteProject.Slug}.psd1',
    [string] $ExampleOutputName = '{firstSuiteProject.QuickStartType}.ps1'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$templates = Join-Path $root 'templates'
$examples = Join-Path $root 'examples'

if (-not (Test-Path -LiteralPath $templates)) {{
    throw ""Templates folder was not found: $templates""
}}

if (-not (Test-Path -LiteralPath $examples)) {{
    New-Item -ItemType Directory -Path $examples -Force | Out-Null
}}

$copyPlan = @(
    @{{
        Source = Join-Path $templates '{firstSuiteProject.Slug}-help.xml.template'
        Destination = Join-Path $root $HelpOutputName
    }}
    @{{
        Source = Join-Path $templates '{firstSuiteProject.Slug}.psd1.template'
        Destination = Join-Path $root $ManifestOutputName
    }}
    @{{
        Source = Join-Path $templates '{firstSuiteProject.QuickStartType}.ps1.template'
        Destination = Join-Path $examples $ExampleOutputName
    }}
    @{{
        Source = Join-Path $templates 'command-metadata.json.template'
        Destination = Join-Path $root 'command-metadata.json'
    }}
)

foreach ($item in $copyPlan) {{
    if (-not (Test-Path -LiteralPath $item.Source)) {{
        throw ""Template was not found: $($item.Source)""
    }}

    if ($PSCmdlet.ShouldProcess($item.Destination, 'Copy scaffold template')) {{
        Copy-Item -LiteralPath $item.Source -Destination $item.Destination -Force
    }}
}}

Write-Host 'Starter templates promoted into discoverable PowerShell API inputs.'
Write-Host 'Next step: replace scaffold text before relying on project-apidocs output.'
");
                }
                else
                {
                    var dotNetSourceRoot = Path.Combine(firstProjectSourcesRoot, "dotnet");
                    var dotNetTemplatesRoot = Path.Combine(dotNetSourceRoot, "templates");
                    Directory.CreateDirectory(dotNetSourceRoot);
                    Directory.CreateDirectory(dotNetTemplatesRoot);
                    created += WriteFile(Path.Combine(dotNetSourceRoot, "README.md"),
$@"# {firstSuiteProject.Name} .NET API Inputs

Place the generated .NET API inputs for `{firstSuiteProject.Slug}` here.

Expected files:

- XML documentation file (`*.xml`)
- matching assembly (`*.dll`)

This folder shape matches the default `project-apidocs` discovery rules.

Safe starter templates live under `templates/` and intentionally do not use discoverable file extensions.
Use `promote-from-build.ps1` to copy real build outputs into this folder when they are ready.
");
                    created += WriteFile(Path.Combine(dotNetTemplatesRoot, $"{firstSuiteProject.QuickStartType}.xml.template"),
$@"<doc>
  <assembly><name>{firstSuiteProject.QuickStartType}</name></assembly>
  <members>
    <member name=""{firstSuiteProject.QuickStartTarget}"">
      <summary>Replace this starter text with real XML documentation.</summary>
    </member>
  </members>
</doc>
");
                    created += WriteFile(Path.Combine(dotNetTemplatesRoot, $"{firstSuiteProject.QuickStartType}.dll.placeholder.txt"),
$@"Place the compiled assembly for {firstSuiteProject.QuickStartType} next to the final XML documentation file.

Expected runtime pair:
- {firstSuiteProject.QuickStartType}.xml
- {firstSuiteProject.QuickStartType}.dll
");
                    created += WriteFile(Path.Combine(dotNetSourceRoot, "promote-from-build.ps1"),
$@"[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter(Mandatory = $true)]
    [string] $XmlPath,

    [Parameter(Mandatory = $true)]
    [string] $AssemblyPath
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

$resolvedXmlPath = (Resolve-Path -LiteralPath $XmlPath).Path
$resolvedAssemblyPath = (Resolve-Path -LiteralPath $AssemblyPath).Path

$xmlName = Split-Path -Leaf $resolvedXmlPath
$assemblyName = Split-Path -Leaf $resolvedAssemblyPath

$copyPlan = @(
    @{{
        Source = $resolvedXmlPath
        Destination = Join-Path $root $xmlName
    }}
    @{{
        Source = $resolvedAssemblyPath
        Destination = Join-Path $root $assemblyName
    }}
)

foreach ($item in $copyPlan) {{
    if ($PSCmdlet.ShouldProcess($item.Destination, 'Copy compiled API input')) {{
        Copy-Item -LiteralPath $item.Source -Destination $item.Destination -Force
    }}
}}

Write-Host 'Build outputs promoted into discoverable .NET API inputs.'
Write-Host 'Next step: keep the XML and DLL names aligned so project-apidocs can match them.'
");
                }
            }
        }

        var powerforgeRoot = Path.Combine(fullOutput, ".powerforge");
        Directory.CreateDirectory(powerforgeRoot);
        var engineLock = WebEngineLockFile.CreateDefault();
        created += WriteFile(
            Path.Combine(powerforgeRoot, "engine-lock.json"),
            JsonSerializer.Serialize(engineLock, new JsonSerializerOptions(WebJson.Options) { WriteIndented = true }));

        var workflowsRoot = Path.Combine(fullOutput, ".github", "workflows");
        Directory.CreateDirectory(workflowsRoot);
        var workflowTemplate = """
name: Website CI

on:
  pull_request:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: website-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  POWERFORGE_LOCK_PATH: ./.powerforge/engine-lock.json

jobs:
  verify-site:
    uses: EvotecIT/PSPublishModule/.github/workflows/powerforge-website-ci.yml@main
    with:
      website_root: .
      pipeline_config: pipeline.json
      powerforge_lock_path: ./.powerforge/engine-lock.json
      powerforge_repository_override: ${{ vars.POWERFORGE_REPOSITORY }}
      powerforge_ref_override: ${{ vars.POWERFORGE_REF }}
    secrets: inherit
""";
        created += WriteFile(Path.Combine(workflowsRoot, "website-ci.yml"), workflowTemplate);

        var maintenanceWorkflowTemplate = """
name: Website Maintenance

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  actions: write

concurrency:
  group: website-maintenance-${{ github.ref }}
  cancel-in-progress: false

env:
  POWERFORGE_LOCK_PATH: ./.powerforge/engine-lock.json

jobs:
  maintenance:
    uses: EvotecIT/PSPublishModule/.github/workflows/powerforge-website-maintenance.yml@main
    with:
      website_root: .
      pipeline_config: pipeline.maintenance.json
      powerforge_lock_path: ./.powerforge/engine-lock.json
      powerforge_repository_override: ${{ vars.POWERFORGE_REPOSITORY }}
      powerforge_ref_override: ${{ vars.POWERFORGE_REF }}
    secrets: inherit
""";
        created += WriteFile(Path.Combine(workflowsRoot, "website-maintenance.yml"), maintenanceWorkflowTemplate);

created += WriteFile(Path.Combine(fullOutput, "README.md"),
$@"# {name}

Starter site scaffolded by PowerForge.Web.

Starter profile:
- `{starterProfile}`
{(firstSuiteProject is null ? string.Empty : $@"

First suite project:
- `{firstSuiteProject.Slug}` ({firstSuiteProject.Surface})")}

## Quick start

Local dev loop:

```powershell
powerforge-web pipeline --config .\pipeline.json --mode dev
```

CI mode (strict, but stable via baselines):

```powershell
powerforge-web pipeline --config .\pipeline.json --mode ci
```

Starter preset file:
- `config/presets/pipeline.web-quality.json`
- `config/presets/pipeline.web-maintenance.json`
- Edit this preset to tune shared verify/audit/cache/profile behavior for the whole site.

Maintenance pipeline:
- `pipeline.maintenance.json` (storage hygiene / scheduled maintenance)
- `.github/workflows/website-maintenance.yml` (weekly schedule + manual run)
- profile: `{maintenanceProfile}` (`keep: {maintenanceBudgets.Keep}`, `maxAgeDays: {maintenanceBudgets.MaxAgeDays}`, `maxDelete: {maintenanceBudgets.MaxDelete}`)

{(multiProjectApiSuiteStarter
? """
## Multi-project API suite

This starter includes a safe `project-apidocs` setup for multi-project sites.

- placeholder route: `/projects/api-suite/`
- project catalog: `data/projects/catalog.json`
- project entry template: `data/projects/catalog.project-template.json`
- suite narrative: `data/projects/api-suite-narrative.json`
- per-project related-content template: `data/projects/sample-project-api-guides.json`
- project source staging: `projects-sources/`
- theme API fragments: `themes/<theme>/partials/api-header.html` and `api-footer.html`
- theme API CSS: `themes/<theme>/assets/api.css`

Recommended next steps:

```powershell
powerforge-web pipeline --config .\pipeline.json --mode dev
```

Then:

- add projects to `data/projects/catalog.json`
- start from `data/projects/catalog.project-template.json`
- duplicate `data/projects/sample-project-api-guides.json` per real project
- add `apiDocs.quickStartTypes`
- add `apiDocs.relatedContentManifest` or `apiDocs.relatedContentManifests`
- update the suite onboarding in `data/projects/api-suite-narrative.json`

{(firstSuiteProject is null ? string.Empty : $@"The scaffold already materialized a first project entry for `{firstSuiteProject.Slug}`. Replace the starter text in:

- `content/docs/projects/{firstSuiteProject.Slug}-quick-start.md`
- `data/projects/{firstSuiteProject.RelatedContentFileName}`
- `projects-sources/{firstSuiteProject.Slug}/README.md`")}

The scaffolded `/projects/api-suite/` page is a placeholder route that `project-apidocs` will replace once real project APIs are generated.
"""
: string.Empty)}

## Baselines (recommended workflow)

Generate baselines once the site is in a good state:

```powershell
powerforge-web verify --config .\site.json --baseline-generate
powerforge-web audit --site-root .\_site --baseline .\.powerforge\audit-baseline.json --baseline-generate
```

Commit the generated files under `.powerforge/` so CI can run `failOnNewWarnings` / `failOnNewIssues`.

## Engine pinning

The scaffold includes `.powerforge/engine-lock.json` and CI resolves engine checkout from this lock by default.

Upgrade the lock intentionally:

```powershell
powerforge-web engine-lock --mode update --path .\.powerforge\engine-lock.json --ref <new-sha>
```

Canary override (optional):
- set GitHub variables `POWERFORGE_REPOSITORY` and/or `POWERFORGE_REF` in one repo to test candidate engine refs without editing the lock file.

Schema refs:
- The scaffold uses `$schema` URLs pointing at the PSPublishModule `main` branch so they work outside this repo.
");

        return new WebScaffoldResult
        {
            OutputPath = fullOutput,
            CreatedFileCount = created,
            ThemeEngine = engine,
            MaintenanceProfile = maintenanceProfile,
            StarterProfile = starterProfile,
            FirstSuiteProjectSlug = firstSuiteProject?.Slug,
            FirstSuiteProjectSurface = firstSuiteProject?.Surface,
            SiteName = name,
            BaseUrl = url
        };
    }

    private static int WriteFile(string path, string content)
    {
        File.WriteAllText(path, content);
        return 1;
    }

    private static string InsertSchema(string json, string schema)
    {
        if (string.IsNullOrWhiteSpace(json)) return json;
        try
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;
            if (root.ValueKind != JsonValueKind.Object) return json;

            using var stream = new MemoryStream();
            using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }))
            {
                writer.WriteStartObject();
                writer.WriteString("$schema", schema);
                foreach (var prop in root.EnumerateObject())
                    prop.WriteTo(writer);
                writer.WriteEndObject();
            }
            return System.Text.Encoding.UTF8.GetString(stream.ToArray());
        }
        catch
        {
            return json;
        }
    }

    private static string NormalizeMaintenanceProfile(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "balanced";

        var normalized = value.Trim().ToLowerInvariant();
        return normalized switch
        {
            "conservative" => "conservative",
            "balanced" => "balanced",
            "aggressive" => "aggressive",
            _ => throw new ArgumentException($"Unsupported maintenance profile '{value}'. Use conservative, balanced, or aggressive.", nameof(value))
        };
    }

    private static (int Keep, int MaxAgeDays, int MaxDelete) ResolveMaintenanceBudgets(string maintenanceProfile)
    {
        return maintenanceProfile switch
        {
            "conservative" => (Keep: 14, MaxAgeDays: 30, MaxDelete: 50),
            "aggressive" => (Keep: 3, MaxAgeDays: 7, MaxDelete: 250),
            _ => (Keep: 7, MaxAgeDays: 14, MaxDelete: 100)
        };
    }

    private static string NormalizeStarterProfile(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "standard";

        var normalized = value.Trim().ToLowerInvariant();
        return normalized switch
        {
            "standard" => "standard",
            "multi-project-api-suite" => "multi-project-api-suite",
            _ => throw new ArgumentException($"Unsupported starter profile '{value}'. Use standard or multi-project-api-suite.", nameof(value))
        };
    }

    private static SuiteStarterProjectSeed? ResolveSuiteStarterProjectSeed(bool multiProjectApiSuiteStarter, string? slug, string? name, string? surface)
    {
        var hasProjectInput = !string.IsNullOrWhiteSpace(slug) || !string.IsNullOrWhiteSpace(name) || !string.IsNullOrWhiteSpace(surface);
        if (!hasProjectInput)
            return null;

        if (!multiProjectApiSuiteStarter)
            throw new ArgumentException("Suite project seed options require starterProfile 'multi-project-api-suite'.", nameof(slug));

        var resolvedSurface = NormalizeSuiteStarterProjectSurface(surface);
        var resolvedSlug = NormalizeSuiteStarterProjectSlug(slug);
        var resolvedName = string.IsNullOrWhiteSpace(name) ? null : name.Trim();

        if (string.IsNullOrWhiteSpace(resolvedSlug) && string.IsNullOrWhiteSpace(resolvedName))
            throw new ArgumentException("Provide --suite-project-slug, --suite-project-name, or both when materializing the first suite project.");

        resolvedSlug ??= BuildSuiteStarterProjectSlugFromName(resolvedName!);
        resolvedName ??= BuildSuiteStarterProjectNameFromSlug(resolvedSlug);

        var identifierSuffix = BuildSuiteStarterIdentifierSuffix(resolvedName, resolvedSlug);
        return new SuiteStarterProjectSeed
        {
            Slug = resolvedSlug,
            Name = resolvedName,
            Surface = resolvedSurface,
            SurfaceCatalogKey = resolvedSurface.Equals("dotnet", StringComparison.OrdinalIgnoreCase) ? "apiDotNet" : "apiPowerShell",
            QuickStartType = resolvedSurface.Equals("dotnet", StringComparison.OrdinalIgnoreCase)
                ? $"{identifierSuffix}Client"
                : $"Invoke-{identifierSuffix}Action",
            QuickStartTarget = resolvedSurface.Equals("dotnet", StringComparison.OrdinalIgnoreCase)
                ? $"T:{identifierSuffix}Client"
                : $"ps:Invoke-{identifierSuffix}Action",
            RelatedContentFileName = $"{resolvedSlug}-api-guides.json"
        };
    }

    private static string NormalizeSuiteStarterProjectSurface(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "powershell";

        var normalized = value.Trim().ToLowerInvariant();
        return normalized switch
        {
            "powershell" => "powershell",
            "pwsh" => "powershell",
            "ps" => "powershell",
            "dotnet" => "dotnet",
            ".net" => "dotnet",
            "csharp" => "dotnet",
            "cs" => "dotnet",
            _ => throw new ArgumentException($"Unsupported suite project surface '{value}'. Use powershell or dotnet.", nameof(value))
        };
    }

    private static string? NormalizeSuiteStarterProjectSlug(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return null;

        var trimmed = value.Trim().ToLowerInvariant();
        var buffer = new List<char>(trimmed.Length);
        var previousDash = false;
        foreach (var character in trimmed)
        {
            if (char.IsLetterOrDigit(character))
            {
                buffer.Add(character);
                previousDash = false;
                continue;
            }

            if (character is '-' or '_' or ' ' or '.')
            {
                if (!previousDash && buffer.Count > 0)
                {
                    buffer.Add('-');
                    previousDash = true;
                }
            }
        }

        var normalized = new string(buffer.ToArray()).Trim('-');
        return string.IsNullOrWhiteSpace(normalized) ? null : normalized;
    }

    private static string BuildSuiteStarterProjectSlugFromName(string value)
    {
        return NormalizeSuiteStarterProjectSlug(value)
               ?? throw new ArgumentException($"Unable to derive a suite project slug from '{value}'.", nameof(value));
    }

    private static string BuildSuiteStarterProjectNameFromSlug(string slug)
    {
        var parts = slug.Split(new[] { '-', '_' }, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (parts.Length == 0)
            return "Sample Project";

        return string.Join(" ", parts.Select(static part =>
        {
            if (part.Length == 1)
                return part.ToUpperInvariant();
            return char.ToUpperInvariant(part[0]) + part[1..];
        }));
    }

    private static string BuildSuiteStarterIdentifierSuffix(string name, string slug)
    {
        var source = !string.IsNullOrWhiteSpace(name) ? name : slug;
        var builder = new List<char>(source.Length);
        foreach (var character in source)
        {
            if (char.IsLetterOrDigit(character))
                builder.Add(character);
        }

        var compact = new string(builder.ToArray());
        if (string.IsNullOrWhiteSpace(compact))
            return "SampleProject";

        return compact;
    }
}
