using System.Text.Json;

namespace PowerForge.Web;

/// <summary>Scaffolds a starter site with content and theme.</summary>
public static partial class WebSiteScaffolder
{
    private const string DefaultSchemaBaseUrl = "https://raw.githubusercontent.com/EvotecIT/PSPublishModule/main/Schemas/";
    /// <summary>Creates a new site scaffold.</summary>
    /// <param name="outputPath">Output directory.</param>
    /// <param name="siteName">Optional site name.</param>
    /// <param name="baseUrl">Optional base URL.</param>
    /// <param name="themeEngine">Template engine identifier.</param>
    /// <returns>Result payload describing created files.</returns>
    public static WebScaffoldResult Scaffold(string outputPath, string? siteName, string? baseUrl, string? themeEngine)
    {
        if (string.IsNullOrWhiteSpace(outputPath))
            throw new ArgumentException("Output path is required.", nameof(outputPath));

        var fullOutput = Path.GetFullPath(outputPath);
        if (Directory.Exists(fullOutput) && Directory.EnumerateFileSystemEntries(fullOutput).Any())
            throw new InvalidOperationException($"Output path is not empty: {fullOutput}");

        Directory.CreateDirectory(fullOutput);

        var name = string.IsNullOrWhiteSpace(siteName) ? "MySite" : siteName.Trim();
        var url = string.IsNullOrWhiteSpace(baseUrl) ? "https://example.com" : baseUrl.Trim();
        var engine = string.IsNullOrWhiteSpace(themeEngine) ? "simple" : themeEngine.Trim();
        var isScriban = engine.Equals("scriban", StringComparison.OrdinalIgnoreCase);
        var themeName = isScriban ? "nova" : "base";

        var created = 0;

        var contentPagesRoot = Path.Combine(fullOutput, "content", "pages");
        Directory.CreateDirectory(contentPagesRoot);
        created += WriteFile(Path.Combine(contentPagesRoot, "index.md"),
@"---
title: Welcome
description: Starter page generated by PowerForge.Web.
---

# Welcome

This site was scaffolded by PowerForge.Web.
");

        var contentDocsRoot = Path.Combine(fullOutput, "content", "docs");
        Directory.CreateDirectory(contentDocsRoot);
        created += WriteFile(Path.Combine(contentDocsRoot, "index.md"),
@"---
title: Documentation
description: Getting started guides and references.
layout: docs
meta.eyebrow: Documentation
---

# Documentation

Start here to learn how the engine works, then expand your docs and API references.
");

        var contentBlogRoot = Path.Combine(fullOutput, "content", "blog");
        Directory.CreateDirectory(contentBlogRoot);
        created += WriteFile(Path.Combine(contentBlogRoot, "_index.md"),
@"---
title: Blog
description: Product updates and release notes.
meta.eyebrow: Blog
---

# Blog

Latest updates from the project.
");
        created += WriteFile(Path.Combine(contentBlogRoot, "hello-world.md"),
@"---
title: Hello from PowerForge.Web
description: First blog post generated by the scaffold.
date: 2026-01-01
layout: post
tags:
  - release
  - announcement
categories:
  - updates
---

# Hello from PowerForge.Web

Use this post as a starting point for changelogs, release notes, and engineering updates.
");
        created += WriteFile(Path.Combine(contentBlogRoot, "roadmap-update.md"),
@"---
title: Roadmap update
description: A short sample update post for pagination and list previews.
date: 2026-01-08
layout: post
tags:
  - roadmap
  - planning
categories:
  - updates
---

# Roadmap update

This second sample entry helps verify list layouts, pagination, and feeds.
");

        var contentNewsRoot = Path.Combine(fullOutput, "content", "news");
        Directory.CreateDirectory(contentNewsRoot);
        created += WriteFile(Path.Combine(contentNewsRoot, "_index.md"),
@"---
title: News
description: Product announcements and company updates.
meta.eyebrow: News
---

# News

Official announcements and release milestones.
");
        created += WriteFile(Path.Combine(contentNewsRoot, "release-1-0.md"),
@"---
title: Version 1.0 announced
description: First stable release announcement generated by the scaffold.
date: 2026-01-10
layout: post
tags:
  - release
  - stable
categories:
  - announcements
---

# Version 1.0 announced

Use this sample news post to publish release announcements and milestones.
");

        var dataRoot = Path.Combine(fullOutput, "data");
        Directory.CreateDirectory(dataRoot);
        created += WriteFile(Path.Combine(dataRoot, "sections.json"),
@"{
  ""features"": {
    ""label"": ""Features"",
    ""title"": ""Built for modern teams"",
    ""description"": ""Use JSON data for repeatable blocks.""
  }
}
");

        var themeRoot = Path.Combine(fullOutput, "themes", themeName);
        var layoutsRoot = Path.Combine(themeRoot, "layouts");
        var partialsRoot = Path.Combine(themeRoot, "partials");
        var assetsRoot = Path.Combine(themeRoot, "assets");
        var scriptsRoot = Path.Combine(themeRoot, "scripts");
        Directory.CreateDirectory(layoutsRoot);
        Directory.CreateDirectory(partialsRoot);
        Directory.CreateDirectory(assetsRoot);
        Directory.CreateDirectory(scriptsRoot);

        var manifest = new ThemeManifest
        {
            Name = themeName,
            SchemaVersion = 2,
            Engine = engine,
            Features = new[] { "docs", "blog", "news" },
            FeatureContracts = new Dictionary<string, ThemeFeatureContractSpec>(StringComparer.OrdinalIgnoreCase)
            {
                ["docs"] = new ThemeFeatureContractSpec
                {
                    RequiredLayouts = new[] { "docs" }
                }
            },
            DefaultLayout = "base",
            LayoutsPath = "layouts",
            PartialsPath = "partials",
            AssetsPath = "assets",
            ScriptsPath = "scripts",
            Slots = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["site-header"] = "header",
                ["site-footer"] = "footer",
                ["theme-tokens"] = "theme-tokens"
            },
            Tokens = isScriban
                ? new Dictionary<string, object?>
                {
                    ["color"] = new Dictionary<string, object?>
                    {
                        ["bg"] = "#0f172a",
                        ["panel"] = "rgba(15, 23, 42, 0.85)",
                        ["ink"] = "#e2e8f0",
                        ["muted"] = "#94a3b8",
                        ["accent"] = "#38bdf8",
                        ["border"] = "rgba(148, 163, 184, 0.2)"
                    },
                    ["radius"] = new Dictionary<string, object?>
                    {
                        ["base"] = "18px",
                        ["sm"] = "12px"
                    },
                    ["font"] = new Dictionary<string, object?>
                    {
                        ["body"] = "Inter, Segoe UI, sans-serif",
                        ["display"] = "Space Grotesk, Segoe UI, sans-serif",
                        ["mono"] = "JetBrains Mono, Consolas, monospace"
                    },
                    ["layout"] = new Dictionary<string, object?>
                    {
                        ["maxWidth"] = "1080px"
                    }
                }
                : null
        };
        var manifestJson = JsonSerializer.Serialize(manifest, WebJson.Options);
        manifestJson = InsertSchema(manifestJson, DefaultSchemaBaseUrl + "powerforge.web.themespec.schema.json");
        created += WriteFile(Path.Combine(themeRoot, "theme.manifest.json"), manifestJson);

        var layout = isScriban
            ? ScribanLayoutTemplate
            : SimpleLayoutTemplate;
        created += WriteFile(Path.Combine(layoutsRoot, "base.html"), layout);
        created += WriteFile(Path.Combine(layoutsRoot, "page.html"), layout);
        created += WriteFile(Path.Combine(layoutsRoot, "docs.html"), layout);
        created += WriteFile(Path.Combine(layoutsRoot, "list.html"), isScriban ? ScribanListLayoutTemplate : layout);
        created += WriteFile(Path.Combine(layoutsRoot, "post.html"), isScriban ? ScribanPostLayoutTemplate : layout);
        created += WriteFile(Path.Combine(layoutsRoot, "taxonomy.html"), isScriban ? ScribanTaxonomyLayoutTemplate : layout);
        created += WriteFile(Path.Combine(layoutsRoot, "term.html"), isScriban ? ScribanTermLayoutTemplate : layout);

        if (isScriban)
        {
            created += WriteFile(Path.Combine(partialsRoot, "header.html"),
@"<header class=""pf-header"">
  <div class=""pf-container pf-header-inner"">
    <div class=""pf-brand"">{{ site.name }}</div>
    <nav class=""pf-nav"">
      {{ pf.nav_links ""main"" }}
    </nav>
  </div>
</header>
");
            created += WriteFile(Path.Combine(partialsRoot, "footer.html"),
@"<footer class=""pf-footer"">
  <div class=""pf-container"">
    <span>Powered by PowerForge.Web</span>
  </div>
</footer>
");
            created += WriteFile(Path.Combine(partialsRoot, "theme-tokens.html"),
@"<style>
:root {
  --pf-bg: {{ data.theme.tokens.color.bg }};
  --pf-panel: {{ data.theme.tokens.color.panel }};
  --pf-ink: {{ data.theme.tokens.color.ink }};
  --pf-muted: {{ data.theme.tokens.color.muted }};
  --pf-accent: {{ data.theme.tokens.color.accent }};
  --pf-border: {{ data.theme.tokens.color.border }};
  --pf-radius: {{ data.theme.tokens.radius.base }};
  --pf-radius-sm: {{ data.theme.tokens.radius.sm }};
  --pf-font-body: {{ data.theme.tokens.font.body }};
  --pf-font-display: {{ data.theme.tokens.font.display }};
  --pf-font-mono: {{ data.theme.tokens.font.mono }};
  --pf-max-width: {{ data.theme.tokens.layout.maxWidth }};
}
</style>
");
        }
        else
        {
            created += WriteFile(Path.Combine(partialsRoot, "header.html"),
@"<header class=""pf-header"">
  <div class=""pf-container pf-header-inner"">
    <div class=""pf-brand"">{{SITE_NAME}}</div>
    <nav class=""pf-nav"">
      <!-- Simple engine: use hard-coded links or migrate to Scriban for full navigation runtime. -->
      <a href=""/"">Home</a>
      <a href=""/docs/"">Docs</a>
      <a href=""/blog/"">Blog</a>
      <a href=""/news/"">News</a>
    </nav>
  </div>
</header>
");
            created += WriteFile(Path.Combine(partialsRoot, "footer.html"),
@"<footer class=""pf-footer"">
  <div class=""pf-container"">
    <span>Powered by PowerForge.Web</span>
  </div>
</footer>
");
            created += WriteFile(Path.Combine(partialsRoot, "theme-tokens.html"),
@"<style>
:root {
  --pf-bg: #0f172a;
  --pf-panel: rgba(15, 23, 42, 0.85);
  --pf-ink: #e2e8f0;
  --pf-muted: #94a3b8;
  --pf-accent: #38bdf8;
  --pf-border: rgba(148, 163, 184, 0.2);
  --pf-radius: 18px;
  --pf-radius-sm: 12px;
  --pf-font-body: Segoe UI, sans-serif;
  --pf-font-display: Segoe UI, sans-serif;
  --pf-font-mono: Consolas, monospace;
  --pf-max-width: 1080px;
}
</style>
");
        }

        created += WriteFile(Path.Combine(themeRoot, "critical.css"),
@"body { font-family: var(--pf-font-body, system-ui, sans-serif); margin: 0; background: var(--pf-bg, #0f172a); color: var(--pf-ink, #e2e8f0); }
.pf-header, .pf-footer { padding: 16px 24px; background: rgba(15, 23, 42, 0.8); border-bottom: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); }
.pf-nav a { margin-right: 12px; text-decoration: none; color: var(--pf-muted, #94a3b8); }
.pf-web-content { padding: 24px; }
");

        created += WriteFile(Path.Combine(assetsRoot, "app.css"),
@"* { box-sizing: border-box; }
body { margin: 0; font-family: var(--pf-font-body, system-ui, sans-serif); background: var(--pf-bg, #0f172a); color: var(--pf-ink, #e2e8f0); }
a { color: inherit; text-decoration: none; }
.pf-container { max-width: var(--pf-max-width, 1080px); margin: 0 auto; padding: 0 24px; }
.pf-header-inner { display: flex; align-items: center; justify-content: space-between; gap: 16px; }
.pf-brand { font-family: var(--pf-font-display, system-ui, sans-serif); color: var(--pf-accent, #38bdf8); letter-spacing: 0.08em; text-transform: uppercase; }
.pf-nav { display: flex; gap: 16px; font-size: 0.95rem; color: var(--pf-muted, #94a3b8); }
.pf-web-content { padding: 32px 0 60px; }
.pf-content { background: var(--pf-panel, rgba(15, 23, 42, 0.85)); border: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); border-radius: var(--pf-radius, 18px); padding: 24px 28px; }
.pf-editorial-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 16px; margin-top: 18px; }
.pf-editorial-grid--hero .pf-editorial-card--hero { grid-column: 1 / -1; }
.pf-editorial-grid--compact { grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); }
.pf-editorial-grid--featured .pf-editorial-card--featured { border-color: rgba(56, 189, 248, 0.45); }
.pf-editorial-card { display: block; background: rgba(15, 23, 42, 0.72); border: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); border-radius: var(--pf-radius-sm, 12px); padding: 16px; color: inherit; transition: border-color .15s ease, transform .15s ease; }
.pf-editorial-card:hover { border-color: var(--pf-accent, #38bdf8); transform: translateY(-1px); }
.pf-editorial-card--compact .pf-editorial-summary { font-size: .92rem; }
.pf-editorial-card--hero h3 { font-size: 1.35rem; margin-top: 0; }
.pf-editorial-card--featured h3 { color: var(--pf-accent, #38bdf8); }
.pf-editorial-card-media { display: block; width: 100%; border-radius: 10px; overflow: hidden; margin-bottom: 12px; background: rgba(15, 23, 42, 0.5); }
.pf-editorial-card-image { width: 100%; height: 100%; object-fit: cover; display: block; }
.pf-editorial-meta { display: flex; gap: 10px; align-items: center; color: var(--pf-muted, #94a3b8); font-size: .85rem; margin-bottom: 10px; }
.pf-editorial-summary { color: var(--pf-muted, #94a3b8); margin: 0; }
.pf-editorial-tags { margin-top: 12px; display: flex; flex-wrap: wrap; gap: 8px; }
.pf-chip { border: 1px solid var(--pf-border, rgba(148, 163, 184, 0.2)); border-radius: 999px; padding: 2px 8px; font-size: .78rem; color: var(--pf-muted, #94a3b8); }
.pf-pagination { margin-top: 18px; display: flex; justify-content: space-between; gap: 12px; }
.pf-pagination a { color: var(--pf-accent, #38bdf8); }
");

        var siteSpec = new SiteSpec
        {
            SchemaVersion = 1,
            Name = name,
            BaseUrl = url,
            DefaultTheme = themeName,
            ThemeEngine = string.IsNullOrWhiteSpace(themeEngine) ? null : engine,
            TrailingSlash = TrailingSlashMode.Always,
            ContentRoot = "content",
            ThemesRoot = "themes",
            DataRoot = "data",
            Features = new[] { "docs", "blog", "news" },
            Collections = new[]
            {
                new CollectionSpec
                {
                    Name = "pages",
                    Input = "content/pages",
                    Output = "/",
                    DefaultLayout = "page",
                    Include = new[] { "*.md", "**/*.md" }
                },
                new CollectionSpec
                {
                    Name = "docs",
                    Input = "content/docs",
                    Output = "/docs",
                    DefaultLayout = "docs",
                    Include = new[] { "*.md", "**/*.md" }
                },
                new CollectionSpec
                {
                    Name = "blog",
                    Input = "content/blog",
                    Output = "/blog",
                    DefaultLayout = "post",
                    ListLayout = "list",
                    Include = new[] { "*.md", "**/*.md" }
                },
                new CollectionSpec
                {
                    Name = "news",
                    Input = "content/news",
                    Output = "/news",
                    DefaultLayout = "post",
                    ListLayout = "list",
                    Include = new[] { "*.md", "**/*.md" }
                }
            },
            Taxonomies = new[]
            {
                new TaxonomySpec
                {
                    Name = "tags",
                    BasePath = "/tags",
                    ListLayout = "taxonomy",
                    TermLayout = "term"
                },
                new TaxonomySpec
                {
                    Name = "categories",
                    BasePath = "/categories",
                    ListLayout = "taxonomy",
                    TermLayout = "term"
                }
            },
            Navigation = new NavigationSpec
            {
                Menus = new[]
                {
                    new MenuSpec
                    {
                        Name = "main",
                        Label = "Main",
                        Items = new[]
                        {
                            new MenuItemSpec { Title = "Home", Url = "/" },
                            new MenuItemSpec { Title = "Docs", Url = "/docs/" },
                            new MenuItemSpec { Title = "Blog", Url = "/blog/" },
                            new MenuItemSpec { Title = "News", Url = "/news/" }
                        }
                    }
                },
                Auto = new[]
                {
                    new NavigationAutoSpec
                    {
                        Collection = "docs",
                        Menu = "docs",
                        MaxDepth = 3,
                        IncludeIndex = true
                    }
                }
            },
            AssetRegistry = new AssetRegistrySpec
            {
                Bundles = new[]
                {
                    new AssetBundleSpec
                    {
                        Name = "global",
                        Css = new[] { $"/themes/{themeName}/assets/app.css" },
                        Js = Array.Empty<string>()
                    }
                },
                RouteBundles = new[]
                {
                    new RouteBundleSpec
                    {
                        Match = "/**",
                        Bundles = new[] { "global" }
                    }
                },
                CriticalCss = new[]
                {
                    new CriticalCssSpec
                    {
                        Name = "base",
                        Path = $"themes/{themeName}/critical.css"
                    }
                }
            },
            A11y = new A11ySpec
            {
                SkipLinkLabel = "Skip to content",
                ExternalLinkLabel = "Opens in a new tab",
                NavToggleLabel = "Toggle navigation",
                SearchLabel = "Search"
            },
            LinkRules = new LinkRulesSpec
            {
                ExternalRel = "noopener",
                ExternalTarget = "_blank",
                AddExternalIcon = true
            }
        };

        var siteJson = JsonSerializer.Serialize(siteSpec, WebJson.Options);
        siteJson = InsertSchema(siteJson, DefaultSchemaBaseUrl + "powerforge.web.sitespec.schema.json");
        created += WriteFile(Path.Combine(fullOutput, "site.json"), siteJson);

        var configPresetsRoot = Path.Combine(fullOutput, "config", "presets");
        Directory.CreateDirectory(configPresetsRoot);

        // Keep the starter pipeline tiny and reusable by inheriting a preset.
        var pipelinePresetJson = InsertSchema(
            """
            {
              "cache": true,
              "cachePath": "./.powerforge/pipeline-cache.json",
              "profile": true,
              "profilePath": "./_reports/pipeline-profile.json",
              "steps": [
                { "task": "build", "id": "build-site", "config": "./site.json", "out": "./_site", "clean": true },

                { "task": "verify", "id": "verify-dev", "dependsOn": "build-site", "config": "./site.json", "skipModes": ["ci"], "warningPreviewCount": 5, "errorPreviewCount": 5 },
                { "task": "verify", "id": "verify-ci", "dependsOn": "build-site", "config": "./site.json", "modes": ["ci"], "baseline": "./.powerforge/verify-baseline.json", "failOnNewWarnings": true, "failOnNavLint": true, "failOnThemeContract": true, "warningPreviewCount": 10, "errorPreviewCount": 10 },

                {
                  "task": "audit",
                  "id": "audit-ci",
                  "dependsOn": "build-site",
                  "siteRoot": "./_site",
                  "modes": ["ci"],
                  "summary": true,
                  "sarif": true,
                  "baseline": "./.powerforge/audit-baseline.json",
                  "failOnNewIssues": true,
                  "requireExplicitChecks": true,
                  "checkSeoMeta": false,
                  "checkNetworkHints": true,
                  "checkRenderBlockingResources": true,
                  "checkHeadingOrder": true,
                  "checkLinkPurposeConsistency": true,
                  "checkMediaEmbeds": true
                }
              ]
            }
            """,
            DefaultSchemaBaseUrl + "powerforge.web.pipelinespec.schema.json");
        created += WriteFile(Path.Combine(configPresetsRoot, "pipeline.web-quality.json"), pipelinePresetJson);

        var pipelineJson = InsertSchema(
            """
            {
              "extends": "./config/presets/pipeline.web-quality.json"
            }
            """,
            DefaultSchemaBaseUrl + "powerforge.web.pipelinespec.schema.json");
        created += WriteFile(Path.Combine(fullOutput, "pipeline.json"), pipelineJson);

        var powerforgeRoot = Path.Combine(fullOutput, ".powerforge");
        Directory.CreateDirectory(powerforgeRoot);

        created += WriteFile(Path.Combine(fullOutput, "README.md"),
@$"# {name}

Starter site scaffolded by PowerForge.Web.

## Quick start

Local dev loop:

```powershell
powerforge-web pipeline --config .\pipeline.json --mode dev
```

CI mode (strict, but stable via baselines):

```powershell
powerforge-web pipeline --config .\pipeline.json --mode ci
```

Starter preset file:
- `config/presets/pipeline.web-quality.json`
- Edit this preset to tune shared verify/audit/cache/profile behavior for the whole site.

## Baselines (recommended workflow)

Generate baselines once the site is in a good state:

```powershell
powerforge-web verify --config .\site.json --baseline-generate
powerforge-web audit --site-root .\_site --baseline .\.powerforge\audit-baseline.json --baseline-generate
```

Commit the generated files under `.powerforge/` so CI can run `failOnNewWarnings` / `failOnNewIssues`.

Schema refs:
- The scaffold uses `$schema` URLs pointing at the PSPublishModule `main` branch so they work outside this repo.
");

        return new WebScaffoldResult
        {
            OutputPath = fullOutput,
            CreatedFileCount = created,
            ThemeEngine = engine,
            SiteName = name,
            BaseUrl = url
        };
    }

    private static int WriteFile(string path, string content)
    {
        File.WriteAllText(path, content);
        return 1;
    }

    private static string InsertSchema(string json, string schema)
    {
        if (string.IsNullOrWhiteSpace(json)) return json;
        try
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;
            if (root.ValueKind != JsonValueKind.Object) return json;

            using var stream = new MemoryStream();
            using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }))
            {
                writer.WriteStartObject();
                writer.WriteString("$schema", schema);
                foreach (var prop in root.EnumerateObject())
                    prop.WriteTo(writer);
                writer.WriteEndObject();
            }
            return System.Text.Encoding.UTF8.GetString(stream.ToArray());
        }
        catch
        {
            return json;
        }
    }

}
