using PowerForge;

namespace PowerForge.Web;

public static partial class WebSiteScaffolder
{
    private static string BuildWelcomePageMarkdown()
        => BuildScaffoldMarkdownPage(
            "Welcome",
            "Starter page generated by PowerForge.Web.",
            static doc =>
            {
                doc.Heading(1, "Welcome");
                doc.Paragraph("This site was scaffolded by PowerForge.Web.");
            });

    private static string BuildApiSuitePlaceholderPageMarkdown()
        => BuildScaffoldMarkdownPage(
            "API Suite",
            "Placeholder landing page for the multi-project API suite.",
            static doc =>
            {
                doc.Heading(1, "API Suite");
                doc.Paragraph("This starter reserves `/projects/api-suite/` for the engine-owned API suite portal.");
                doc.Paragraph("Next steps:");
                doc.Bullets(new[]
                {
                    "add project entries in `data/projects/catalog.json`",
                    "place generated API sources under `projects-sources/`",
                    @"run `powerforge-web pipeline --config .\pipeline.json --mode dev`"
                });
                doc.Paragraph("Once `project-apidocs` has real inputs, it will replace this placeholder route with the generated suite portal.");
            });

    private static string BuildDocumentationIndexMarkdown()
        => BuildScaffoldMarkdownPage(
            "Documentation",
            "Getting started guides and references.",
            static doc =>
            {
                doc.Heading(1, "Documentation");
                doc.Paragraph("Start here to learn how the engine works, then expand your docs and API references.");
            },
            layout: "docs",
            eyebrow: "Documentation");

    private static string BuildApiSuiteSetupMarkdown()
        => BuildScaffoldMarkdownPage(
            "API Suite Setup",
            "How to configure the scaffolded multi-project API suite.",
            static doc =>
            {
                doc.Heading(1, "API Suite Setup");
                doc.Paragraph("This starter configures `project-apidocs` plus the recommended suite metadata files.");
                doc.Heading(2, "Fill in the catalog");
                doc.Paragraph("Edit `data/projects/catalog.json` and add one entry per project/module.");
                doc.Heading(2, "Add project sources");
                doc.Paragraph("Place generated XML/help assets under `projects-sources/` so `project-apidocs` can resolve them.");
                doc.Heading(2, "Add curated guidance");
                doc.Bullets(new[]
                {
                    "use `apiDocs.quickStartTypes` for the main entry points of each project",
                    "use `apiDocs.relatedContentManifest` or `apiDocs.relatedContentManifests` to attach authored guides and samples",
                    "update `data/projects/api-suite-narrative.json` so the suite portal has a strong `Start Here` path"
                });
            },
            layout: "docs",
            eyebrow: "API Docs");

    private static string BuildApiGuideTemplateMarkdown()
        => BuildScaffoldMarkdownPage(
            "Project API Guide Template",
            "Duplicate this guide when attaching curated related content to a project API.",
            static doc =>
            {
                doc.Heading(1, "Project API Guide Template");
                doc.Paragraph("Duplicate this page for a real project guide, then point a project related-content manifest entry at the new route.");
                doc.Paragraph("Checklist:");
                doc.Bullets(new[]
                {
                    "rename the file to match the project and workflow",
                    "explain which type or command should be opened first",
                    "include a short example or setup flow",
                    "add the final URL to the related-content manifest you attach in `apiDocs.relatedContentManifest`"
                });
            },
            layout: "docs",
            eyebrow: "API Guides");

    private static string BuildSuiteQuickStartMarkdown(SuiteStarterProjectSeed project)
        => BuildScaffoldMarkdownPage(
            $"{project.Name} Quick Start",
            "Starter quick-start guide for the first scaffolded suite project.",
            doc =>
            {
                doc.Heading(1, $"{project.Name} Quick Start");
                doc.Paragraph("This page was generated from the suite starter so the first project already has a real guide target.");
                doc.Heading(2, "Start with the main API entry point");
                doc.Bullets(new[]
                {
                    $"surface: `{project.Surface}`",
                    $"suggested quick-start symbol: `{project.QuickStartTarget}`"
                });
                doc.Heading(2, "Next steps");
                doc.Bullets(new[]
                {
                    "replace this starter text with a real onboarding flow",
                    $"add a practical example for `{project.QuickStartTarget}`",
                    $"keep `data/projects/{project.RelatedContentFileName}` aligned with the final guide URLs"
                });
            },
            layout: "docs",
            eyebrow: "API Guides");

    private static string BuildBlogIndexMarkdown()
        => BuildScaffoldMarkdownPage(
            "Blog",
            "Product updates and release notes.",
            static doc =>
            {
                doc.Heading(1, "Blog");
                doc.Paragraph("Latest updates from the project.");
            },
            eyebrow: "Blog");

    private static string BuildHelloWorldPostMarkdown()
        => BuildScaffoldMarkdownPage(
            "Hello from PowerForge.Web",
            "First blog post generated by the scaffold.",
            static doc =>
            {
                doc.Heading(1, "Hello from PowerForge.Web");
                doc.Paragraph("Use this post as a starting point for changelogs, release notes, and engineering updates.");
            },
            layout: "post",
            date: "2026-01-01",
            tags: new[] { "release", "announcement" },
            categories: new[] { "updates" });

    private static string BuildRoadmapUpdatePostMarkdown()
        => BuildScaffoldMarkdownPage(
            "Roadmap update",
            "A short sample update post for pagination and list previews.",
            static doc =>
            {
                doc.Heading(1, "Roadmap update");
                doc.Paragraph("This second sample entry helps verify list layouts, pagination, and feeds.");
            },
            layout: "post",
            date: "2026-01-08",
            tags: new[] { "roadmap", "planning" },
            categories: new[] { "updates" });

    private static string BuildNewsIndexMarkdown()
        => BuildScaffoldMarkdownPage(
            "News",
            "Product announcements and company updates.",
            static doc =>
            {
                doc.Heading(1, "News");
                doc.Paragraph("Official announcements and release milestones.");
            },
            eyebrow: "News");

    private static string BuildReleaseAnnouncementMarkdown()
        => BuildScaffoldMarkdownPage(
            "Version 1.0 announced",
            "First stable release announcement generated by the scaffold.",
            static doc =>
            {
                doc.Heading(1, "Version 1.0 announced");
                doc.Paragraph("Use this sample news post to publish release announcements and milestones.");
            },
            layout: "post",
            date: "2026-01-10",
            tags: new[] { "release", "stable" },
            categories: new[] { "announcements" });

    private static string BuildScaffoldMarkdownPage(
        string title,
        string description,
        Action<MarkdownDocumentBuilder> buildBody,
        string? layout = null,
        string? eyebrow = null,
        string? date = null,
        IReadOnlyList<string>? tags = null,
        IReadOnlyList<string>? categories = null)
    {
        var doc = new MarkdownDocumentBuilder();
        doc.FrontMatter("title", title);
        doc.FrontMatter("description", description);
        if (!string.IsNullOrWhiteSpace(layout))
            doc.FrontMatter("layout", layout!);
        if (!string.IsNullOrWhiteSpace(eyebrow))
            doc.FrontMatter("meta.eyebrow", eyebrow!);
        if (!string.IsNullOrWhiteSpace(date))
            doc.FrontMatter("date", date!);
        doc.FrontMatter("tags", tags);
        doc.FrontMatter("categories", categories);
        buildBody(doc);
        return doc.ToString();
    }
}
