using System.Text.Json;

namespace PowerForge.Web;

public static class WebSiteScaffolder
{
    public static WebScaffoldResult Scaffold(string outputPath, string? siteName, string? baseUrl, string? themeEngine)
    {
        if (string.IsNullOrWhiteSpace(outputPath))
            throw new ArgumentException("Output path is required.", nameof(outputPath));

        var fullOutput = Path.GetFullPath(outputPath);
        if (Directory.Exists(fullOutput) && Directory.EnumerateFileSystemEntries(fullOutput).Any())
            throw new InvalidOperationException($"Output path is not empty: {fullOutput}");

        Directory.CreateDirectory(fullOutput);

        var name = string.IsNullOrWhiteSpace(siteName) ? "MySite" : siteName.Trim();
        var url = string.IsNullOrWhiteSpace(baseUrl) ? "https://example.com" : baseUrl.Trim();
        var engine = string.IsNullOrWhiteSpace(themeEngine) ? "simple" : themeEngine.Trim();

        var created = 0;

        var contentRoot = Path.Combine(fullOutput, "content", "pages");
        Directory.CreateDirectory(contentRoot);
        created += WriteFile(Path.Combine(contentRoot, "index.md"),
@"---
title: Welcome
description: Starter page generated by PowerForge.Web.
---

# Welcome

This site was scaffolded by PowerForge.Web.
");

        var themeRoot = Path.Combine(fullOutput, "themes", "base");
        var layoutsRoot = Path.Combine(themeRoot, "layouts");
        var partialsRoot = Path.Combine(themeRoot, "partials");
        Directory.CreateDirectory(layoutsRoot);
        Directory.CreateDirectory(partialsRoot);

        var manifest = new ThemeManifest
        {
            Name = "base",
            Engine = engine,
            LayoutsPath = "layouts",
            PartialsPath = "partials",
            AssetsPath = "assets"
        };
        created += WriteFile(Path.Combine(themeRoot, "theme.json"), JsonSerializer.Serialize(manifest, WebJson.Options));

        var layout = engine.Equals("scriban", StringComparison.OrdinalIgnoreCase)
            ? ScribanLayoutTemplate
            : SimpleLayoutTemplate;
        created += WriteFile(Path.Combine(layoutsRoot, "base.html"), layout);
        created += WriteFile(Path.Combine(layoutsRoot, "page.html"), layout);

        created += WriteFile(Path.Combine(partialsRoot, "header.html"),
@"<header class=""pf-header"">
  <div class=""pf-container"">
    <div class=""pf-brand"">Site</div>
    <nav class=""pf-nav"">
      <a href=""/"">Home</a>
      <a href=""/docs/"">Docs</a>
      <a href=""/blog/"">Blog</a>
    </nav>
  </div>
</header>
");

        created += WriteFile(Path.Combine(partialsRoot, "footer.html"),
@"<footer class=""pf-footer"">
  <div class=""pf-container"">
    <span>Powered by PowerForge.Web</span>
  </div>
</footer>
");

        created += WriteFile(Path.Combine(themeRoot, "critical.css"),
@"body { font-family: system-ui, sans-serif; margin: 0; }
.pf-header, .pf-footer { padding: 16px 24px; background: #f5f5f5; }
.pf-nav a { margin-right: 12px; text-decoration: none; }
.pf-web-content { padding: 24px; }
");

        var siteSpec = new SiteSpec
        {
            SchemaVersion = 1,
            Name = name,
            BaseUrl = url,
            DefaultTheme = "base",
            ThemeEngine = string.IsNullOrWhiteSpace(themeEngine) ? null : engine,
            TrailingSlash = TrailingSlashMode.Always,
            ContentRoot = "content",
            ThemesRoot = "themes",
            Collections = new[]
            {
                new CollectionSpec
                {
                    Name = "pages",
                    Input = "content/pages",
                    Output = "/",
                    DefaultLayout = "page",
                    Include = new[] { "**/*.md" }
                }
            }
        };

        created += WriteFile(Path.Combine(fullOutput, "site.json"), JsonSerializer.Serialize(siteSpec, WebJson.Options));

        return new WebScaffoldResult
        {
            OutputPath = fullOutput,
            CreatedFileCount = created,
            ThemeEngine = engine,
            SiteName = name,
            BaseUrl = url
        };
    }

    private static int WriteFile(string path, string content)
    {
        File.WriteAllText(path, content);
        return 1;
    }

    private const string SimpleLayoutTemplate =
@"<!doctype html>
<html lang=""en"">
<head>
  <meta charset=""utf-8"" />
  <meta name=""viewport"" content=""width=device-width, initial-scale=1"" />
  <title>{{TITLE}}</title>
  {{DESCRIPTION_META}}
  {{CANONICAL}}
  {{PRELOADS}}
  {{CRITICAL_CSS}}
  {{ASSET_CSS}}
</head>
<body>
  {{> header}}
  <main class=""pf-web-content"">
    {{CONTENT}}
  </main>
  {{> footer}}
  {{ASSET_JS}}
</body>
</html>
";

    private const string ScribanLayoutTemplate =
@"<!doctype html>
<html lang=""en"">
<head>
  <meta charset=""utf-8"" />
  <meta name=""viewport"" content=""width=device-width, initial-scale=1"" />
  <title>{{ page.title }}</title>
  {{ description_meta_html }}
  {{ canonical_html }}
  {{ assets.preloads_html }}
  {{ assets.critical_css_html }}
  {{ assets.css_html }}
</head>
<body>
  {{ include ""header"" }}
  <main class=""pf-web-content"">
    {{ content }}
  </main>
  {{ include ""footer"" }}
  {{ assets.js_html }}
</body>
</html>
";
}
