using System.Text;
using System.Xml.Linq;

namespace PowerForge.Web;

public static partial class WebSitemapGenerator
{
    private const int SitemapUrlLimit = 50_000;
    private const long SitemapByteLimit = 50L * 1024 * 1024;
    private const string PartitionOwnershipComment = "Generated by PowerForge.Web sitemap partitioning.";

    private static string[] WritePartitionedSitemap(string siteRoot, string baseUrl, string outputPath,
        string? stylesheet, IReadOnlyList<XElement> entries, IReadOnlyList<object> attributes, int entryLimit = SitemapUrlLimit)
    {
        XDocument Document(IEnumerable<XElement> children) => CreateSitemapDocument(stylesheet,
            new XElement(SitemapNs + "urlset", attributes, children));
        var envelopeBytes = Encoding.UTF8.GetByteCount(Document(Array.Empty<XElement>()).ToString(SaveOptions.DisableFormatting)) + 128L;
        var partitions = new List<List<XElement>> { new() };
        var bytes = envelopeBytes;
        foreach (var entry in entries)
        {
            var entryBytes = Encoding.UTF8.GetByteCount(entry.ToString(SaveOptions.DisableFormatting));
            if (entryBytes + envelopeBytes > SitemapByteLimit)
                throw new InvalidDataException("A sitemap entry exceeds the uncompressed sitemap size limit.");
            var current = partitions[^1];
            if (current.Count >= entryLimit || bytes + entryBytes > SitemapByteLimit)
            {
                current = new List<XElement>();
                partitions.Add(current);
                bytes = envelopeBytes;
            }
            current.Add(entry);
            bytes += entryBytes;
        }
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        var paths = new List<string>();
        if (partitions.Count == 1)
        {
            SaveSitemapDocument(Document(partitions[0]), outputPath);
            paths.Add(outputPath);
        }
        else
        {
            // The original path remains the discovery endpoint and becomes an index.
            for (var index = 0; index < partitions.Count; index++)
            {
                var path = Path.Combine(Path.GetDirectoryName(outputPath)!,
                    Path.GetFileNameWithoutExtension(outputPath) + $".part-{index + 1:D4}.xml");
                var document = Document(partitions[index]);
                document.AddFirst(new XComment(PartitionOwnershipComment));
                SaveSitemapDocument(document, path);
                paths.Add(path);
            }
            WriteSitemapIndex(siteRoot, baseUrl, outputPath, stylesheet,
                DateTime.UtcNow.ToString("yyyy-MM-dd"), paths.Cast<string?>().ToArray());
        }
        var retained = paths.ToHashSet(StringComparer.Ordinal);
        var prefix = Path.GetFileNameWithoutExtension(outputPath) + ".part-";
        foreach (var oldPath in Directory.EnumerateFiles(Path.GetDirectoryName(outputPath)!, "*.xml"))
        {
            if (retained.Contains(oldPath)) continue;
            var name = Path.GetFileNameWithoutExtension(oldPath);
            if (!name.StartsWith(prefix, StringComparison.Ordinal) ||
                name.Length <= prefix.Length || !name[prefix.Length..].All(char.IsAsciiDigit)) continue;
            using var reader = new StreamReader(oldPath);
            var header = new char[512];
            var read = reader.ReadBlock(header, 0, header.Length);
            if (!new string(header, 0, read).Contains(PartitionOwnershipComment, StringComparison.Ordinal)) continue;
            reader.Dispose();
            File.Delete(oldPath);
        }
        return paths.ToArray();
    }

    private static void SaveSitemapDocument(XDocument document, string outputPath)
    {
        // Compact XML keeps the byte budget equivalent to the measured payload.
        using var stream = File.Create(outputPath);
        document.Save(stream, SaveOptions.DisableFormatting);
    }
}
