using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace PowerForge;

internal sealed class ModuleMergeSources
{
    internal ModuleMergeSources(string psm1Path, string[] scriptFiles, string mergedScriptContent, bool hasLib)
    {
        Psm1Path = psm1Path;
        ScriptFiles = scriptFiles ?? System.Array.Empty<string>();
        MergedScriptContent = mergedScriptContent ?? string.Empty;
        HasLib = hasLib;
    }

    internal string Psm1Path { get; }
    internal string[] ScriptFiles { get; }
    internal string MergedScriptContent { get; }
    internal bool HasLib { get; }
    internal bool HasScripts => ScriptFiles.Length > 0;
}

internal static class ModuleMergeComposer
{
    internal static ModuleMergeSources BuildSources(
        string rootPath,
        string moduleName,
        InformationConfiguration? information,
        ExportSet exports,
        bool fixRelativePaths,
        IReadOnlyDictionary<string, string[]>? conditionalFunctionDependencies = null)
    {
        var root = Path.GetFullPath(rootPath);
        var psm1 = Path.Combine(root, $"{moduleName}.psm1");

        var files = new List<string>();
        foreach (var dir in ResolveMergeDirectories(information))
        {
            if (string.IsNullOrWhiteSpace(dir))
                continue;

            var full = Path.Combine(root, dir);
            if (!Directory.Exists(full))
                continue;

            try
            {
                files.AddRange(Directory.EnumerateFiles(full, "*.ps1", SearchOption.AllDirectories));
            }
            catch
            {
                // best effort only
            }
        }

        var ordered = files
            .Where(static file => !string.IsNullOrWhiteSpace(file))
            .Select(Path.GetFullPath)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static file => file, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        var merged = ordered.Length > 0
            ? BuildMergedScriptContent(ordered, exports, fixRelativePaths, conditionalFunctionDependencies, moduleName)
            : string.Empty;
        var libRoot = Path.Combine(root, "Lib");
        var hasLib = Directory.Exists(libRoot) && Directory.EnumerateDirectories(libRoot).Any();

        return new ModuleMergeSources(psm1, ordered, merged, hasLib);
    }

    internal static void SyncMergedPsm1WithGeneratedScripts(
        string manifestPath,
        string stagingPath,
        string moduleName,
        IEnumerable<string> scriptPaths)
    {
        if (string.IsNullOrWhiteSpace(manifestPath) || string.IsNullOrWhiteSpace(stagingPath) || string.IsNullOrWhiteSpace(moduleName))
            return;

        var psm1Path = Path.Combine(stagingPath, $"{moduleName}.psm1");
        if (!File.Exists(psm1Path))
            return;

        var generatedScripts = (scriptPaths ?? System.Array.Empty<string>())
            .Where(static path => !string.IsNullOrWhiteSpace(path) && File.Exists(path))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Select(File.ReadAllText)
            .Where(static content => !string.IsNullOrWhiteSpace(content))
            .ToArray();

        if (generatedScripts.Length == 0)
            return;

        var existing = File.ReadAllText(psm1Path);
        var withoutExportBlock = RemoveTrailingExportBlock(existing).TrimEnd();

        var builder = new StringBuilder(withoutExportBlock);
        foreach (var script in generatedScripts)
        {
            if (builder.Length > 0)
                builder.AppendLine().AppendLine();

            builder.Append(script.TrimEnd());
        }

        var exportBlock = ModuleConditionalExportBlockBuilder.BuildExportBlock(ModuleManifestExportReader.ReadExports(manifestPath)).TrimEnd();
        if (!string.IsNullOrWhiteSpace(exportBlock))
        {
            if (builder.Length > 0)
                builder.AppendLine().AppendLine();
            builder.Append(exportBlock);
        }

        WriteMergedPsm1(psm1Path, builder.ToString());
    }

    internal static string PrependFunctions(string[] functions, string content)
    {
        var block = (functions ?? System.Array.Empty<string>())
            .Where(static function => !string.IsNullOrWhiteSpace(function))
            .ToArray();
        if (block.Length == 0)
            return content;

        var prefix = string.Join(System.Environment.NewLine, block);
        return string.IsNullOrWhiteSpace(content)
            ? prefix
            : prefix + System.Environment.NewLine + System.Environment.NewLine + content;
    }

    internal static void WriteMergedPsm1(string path, string content)
    {
        var normalized = NormalizeCrLf(content);
        File.WriteAllText(path, normalized, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
    }

    internal static bool IsAutoGeneratedPsm1(string content)
        => !string.IsNullOrWhiteSpace(content) &&
           content.IndexOf("Auto-generated by PowerForge", System.StringComparison.OrdinalIgnoreCase) >= 0;

    private static string[] ResolveMergeDirectories(InformationConfiguration? information)
    {
        var ordered = new List<string> { "Classes", "Enums", "Private", "Public" };

        if (information?.IncludePS1 is { Length: > 0 })
        {
            foreach (var entry in information.IncludePS1)
            {
                if (string.IsNullOrWhiteSpace(entry))
                    continue;
                if (ordered.Any(existing => string.Equals(existing, entry, System.StringComparison.OrdinalIgnoreCase)))
                    continue;
                ordered.Add(entry);
            }
        }

        return ordered.ToArray();
    }

    private static string BuildMergedScriptContent(
        IReadOnlyList<string> files,
        ExportSet exports,
        bool fixRelativePaths,
        IReadOnlyDictionary<string, string[]>? conditionalFunctionDependencies,
        string moduleName)
    {
        var requires = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var usingLines = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var body = new StringBuilder(8192);

        foreach (var file in files)
        {
            if (string.IsNullOrWhiteSpace(file) || !File.Exists(file))
                continue;

            string[] lines;
            try
            {
                lines = File.ReadAllLines(file);
            }
            catch
            {
                continue;
            }

            var block = new List<string>();
            foreach (var line in lines)
            {
                var trimmed = line.TrimStart();
                if (trimmed.StartsWith("#requires", System.StringComparison.OrdinalIgnoreCase))
                {
                    requires.Add(trimmed);
                    continue;
                }

                if (trimmed.StartsWith("using ", System.StringComparison.OrdinalIgnoreCase))
                {
                    usingLines.Add(trimmed);
                    continue;
                }

                block.Add(fixRelativePaths ? NormalizeMergedRelativePathReferences(line) : line);
            }

            if (block.Count == 0)
                continue;

            foreach (var line in block)
                body.AppendLine(line);

            body.AppendLine();
        }

        var header = new StringBuilder(1024);
        foreach (var require in requires.OrderBy(static line => line, StringComparer.OrdinalIgnoreCase))
            header.AppendLine(require);
        foreach (var usingLine in usingLines.OrderBy(static line => line, StringComparer.OrdinalIgnoreCase))
            header.AppendLine(usingLine);

        if (header.Length > 0)
            header.AppendLine();

        header.Append(body.ToString().TrimEnd());

        var merged = header.ToString().TrimEnd();
        var exportBlock = ModuleConditionalExportBlockBuilder.BuildExportBlock(
            exports,
            conditionalFunctionDependencies,
            moduleName);
        if (!string.IsNullOrWhiteSpace(exportBlock))
        {
            if (!string.IsNullOrWhiteSpace(merged))
                merged += System.Environment.NewLine + System.Environment.NewLine;
            merged += exportBlock.TrimEnd();
        }

        return merged;
    }

    private static string NormalizeMergedRelativePathReferences(string line)
    {
        if (string.IsNullOrEmpty(line))
            return line ?? string.Empty;

        var updated = line;
        // Legacy merged modules historically normalized both literal and evaluated parent-root references back to the
        // merged module root so inline script assets still resolve after the original folder hierarchy disappears.
        updated = updated.Replace("$PSScriptRoot\\..\\..\\", "$PSScriptRoot\\");
        updated = updated.Replace("$PSScriptRoot\\..\\", "$PSScriptRoot\\");
        updated = updated.Replace("$PSScriptRoot/../../", "$PSScriptRoot/");
        updated = updated.Replace("$PSScriptRoot/../", "$PSScriptRoot/");
        updated = updated.Replace("`$PSScriptRoot, '..',", "$PSScriptRoot,");
        updated = updated.Replace("`$PSScriptRoot,'..',", "$PSScriptRoot,");
        updated = updated.Replace("$PSScriptRoot, '..',", "$PSScriptRoot,");
        updated = updated.Replace("$PSScriptRoot,'..',", "$PSScriptRoot,");
        updated = updated.Replace("$PSScriptRoot, \"..\",", "$PSScriptRoot,");
        updated = updated.Replace("$PSScriptRoot,\"..\",", "$PSScriptRoot,");
        return updated;
    }

    private static string RemoveTrailingExportBlock(string content)
    {
        if (string.IsNullOrWhiteSpace(content))
            return content ?? string.Empty;

        var normalized = content.Replace("\r\n", "\n");
        // The generated export block is expected to be the tail of the merged PSM1, so syncing generated scripts
        // replaces that trailing block wholesale before appending a fresh one from the manifest.
        var exportStart = normalized.LastIndexOf("\n$FunctionsToExport = ", System.StringComparison.Ordinal);
        if (exportStart < 0 && normalized.StartsWith("$FunctionsToExport = ", System.StringComparison.Ordinal))
            exportStart = 0;

        if (exportStart < 0)
            return content;

        const string exportLine = "Export-ModuleMember -Function $FunctionsToExport -Alias $AliasesToExport -Cmdlet $CmdletsToExport";
        var exportLineIndex = normalized.IndexOf(exportLine, exportStart, System.StringComparison.Ordinal);
        if (exportLineIndex < 0)
            return content;

        return normalized.Substring(0, exportStart).TrimEnd('\n').Replace("\n", "\r\n");
    }

    private static string NormalizeCrLf(string text)
        => string.IsNullOrEmpty(text)
            ? string.Empty
            : text.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", "\r\n");
}
