using System.IO;

namespace PowerForge;

internal sealed class ModuleMergeApplicationOutcome
{
    internal ModuleMergeApplicationOutcome(
        bool mergedModule,
        bool usedExistingPsm1,
        int topLevelInlinedFunctions,
        int totalInlinedFunctions,
        int scriptFilesDetected,
        bool hasBinaryOutputs,
        bool hasScriptSources)
    {
        MergedModule = mergedModule;
        UsedExistingPsm1 = usedExistingPsm1;
        TopLevelInlinedFunctions = topLevelInlinedFunctions;
        TotalInlinedFunctions = totalInlinedFunctions;
        ScriptFilesDetected = scriptFilesDetected;
        HasBinaryOutputs = hasBinaryOutputs;
        HasScriptSources = hasScriptSources;
    }

    internal bool MergedModule { get; }
    internal bool UsedExistingPsm1 { get; }
    internal int TopLevelInlinedFunctions { get; }
    internal int TotalInlinedFunctions { get; }
    internal int ScriptFilesDetected { get; }
    internal bool HasBinaryOutputs { get; }
    internal bool HasScriptSources { get; }
}

internal static class ModuleMergeApplier
{
    internal static ModuleMergeApplicationOutcome Apply(
        ILogger logger,
        ModulePipelinePlan plan,
        ModuleMergeSources mergeSources,
        MissingFunctionAnalysisResult? missingReport)
    {
        if (logger is null)
            throw new ArgumentNullException(nameof(logger));
        if (plan is null)
            throw new ArgumentNullException(nameof(plan));
        if (mergeSources is null)
            throw new ArgumentNullException(nameof(mergeSources));

        if (!mergeSources.HasScripts && !File.Exists(mergeSources.Psm1Path))
        {
            logger.Warn("Merge requested but no script sources or PSM1 file were found.");
            return new ModuleMergeApplicationOutcome(
                mergedModule: false,
                usedExistingPsm1: false,
                topLevelInlinedFunctions: 0,
                totalInlinedFunctions: 0,
                scriptFilesDetected: 0,
                hasBinaryOutputs: mergeSources.HasLib,
                hasScriptSources: false);
        }

        var mergedModule = false;
        var usedExistingPsm1 = false;

        if (plan.MergeModule)
        {
            if (!mergeSources.HasScripts)
            {
                logger.Warn("MergeModuleOnBuild requested but no script sources were found. Skipping merge.");
                usedExistingPsm1 = File.Exists(mergeSources.Psm1Path);
            }
            else
            {
                if (File.Exists(mergeSources.Psm1Path))
                {
                    try
                    {
                        var existing = File.ReadAllText(mergeSources.Psm1Path);
                        if (!string.IsNullOrWhiteSpace(existing) && !ModuleMergeComposer.IsAutoGeneratedPsm1(existing))
                            logger.Warn("MergeModuleOnBuild will overwrite existing PSM1 content in staging.");
                    }
                    catch
                    {
                        // best effort only
                    }
                }

                var merged = mergeSources.MergedScriptContent;
                if (plan.MergeMissing && missingReport?.Functions is { Length: > 0 })
                    merged = ModuleMergeComposer.PrependFunctions(missingReport.Functions, merged);

                if (mergeSources.HasLib)
                {
                    ModuleBootstrapperGenerator.InlineMergedScriptPayload(mergeSources.Psm1Path, merged);
                    logger.Info("Merged script sources into the binary module bootstrapper PSM1.");
                }
                else
                {
                    ModuleMergeComposer.WriteMergedPsm1(mergeSources.Psm1Path, merged);
                }
                mergedModule = true;
            }
        }

        if (!mergedModule && plan.MergeMissing && missingReport?.Functions is { Length: > 0 } && File.Exists(mergeSources.Psm1Path))
        {
            var existing = File.ReadAllText(mergeSources.Psm1Path);
            var merged = ModuleMergeComposer.PrependFunctions(missingReport.Functions, existing);
            ModuleMergeComposer.WriteMergedPsm1(mergeSources.Psm1Path, merged);
        }

        usedExistingPsm1 |= !mergeSources.HasScripts && File.Exists(mergeSources.Psm1Path);

        return new ModuleMergeApplicationOutcome(
            mergedModule: mergedModule,
            usedExistingPsm1: usedExistingPsm1,
            topLevelInlinedFunctions: missingReport?.FunctionsTopLevelOnly?.Length ?? 0,
            totalInlinedFunctions: missingReport?.Functions?.Length ?? 0,
            scriptFilesDetected: mergeSources.ScriptFiles.Length,
            hasBinaryOutputs: mergeSources.HasLib,
            hasScriptSources: mergeSources.HasScripts);
    }
}
