using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace PowerForge;

internal sealed class ModuleMergeSources
{
    internal ModuleMergeSources(string psm1Path, string[] scriptFiles, string mergedScriptContent, bool hasLib)
    {
        Psm1Path = psm1Path;
        ScriptFiles = scriptFiles ?? System.Array.Empty<string>();
        MergedScriptContent = mergedScriptContent ?? string.Empty;
        HasLib = hasLib;
    }

    internal string Psm1Path { get; }
    internal string[] ScriptFiles { get; }
    internal string MergedScriptContent { get; }
    internal bool HasLib { get; }
    internal bool HasScripts => ScriptFiles.Length > 0;
}

internal static class ModuleMergeComposer
{
    internal static ModuleMergeSources BuildSources(
        string rootPath,
        string moduleName,
        InformationConfiguration? information,
        ExportSet exports,
        bool fixRelativePaths,
        IReadOnlyDictionary<string, string[]>? conditionalFunctionDependencies = null,
        IReadOnlyList<string>? scriptFiles = null)
    {
        var root = Path.GetFullPath(rootPath);
        var psm1 = Path.Combine(root, $"{moduleName}.psm1");
        var ordered = scriptFiles is null
            ? ResolveScriptFiles(root, information)
            : NormalizeScriptFiles(scriptFiles);

        var merged = ordered.Length > 0
            ? BuildMergedScriptContent(ordered, exports, fixRelativePaths, conditionalFunctionDependencies, moduleName)
            : string.Empty;
        var libRoot = Path.Combine(root, "Lib");
        var hasLib = Directory.Exists(libRoot) && Directory.EnumerateDirectories(libRoot).Any();

        return new ModuleMergeSources(psm1, ordered, merged, hasLib);
    }

    internal static void SyncMergedPsm1WithGeneratedScripts(
        string manifestPath,
        string stagingPath,
        string moduleName,
        IEnumerable<string> scriptPaths)
    {
        if (string.IsNullOrWhiteSpace(manifestPath) || string.IsNullOrWhiteSpace(stagingPath) || string.IsNullOrWhiteSpace(moduleName))
            return;

        var psm1Path = Path.Combine(stagingPath, $"{moduleName}.psm1");
        if (!File.Exists(psm1Path))
            return;

        var generatedScripts = (scriptPaths ?? System.Array.Empty<string>())
            .Where(static path => !string.IsNullOrWhiteSpace(path) && File.Exists(path))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Select(File.ReadAllText)
            .Where(static content => !string.IsNullOrWhiteSpace(content))
            .ToArray();

        if (generatedScripts.Length == 0)
            return;

        var existing = File.ReadAllText(psm1Path);
        var withoutExportBlock = RemoveTrailingExportBlock(existing).TrimEnd();

        var builder = new StringBuilder(withoutExportBlock);
        foreach (var script in generatedScripts)
        {
            if (builder.Length > 0)
                builder.AppendLine().AppendLine();

            builder.Append(script.TrimEnd());
        }

        var exportBlock = ModuleConditionalExportBlockBuilder.BuildExportBlock(ModuleManifestExportReader.ReadExports(manifestPath)).TrimEnd();
        if (!string.IsNullOrWhiteSpace(exportBlock))
        {
            if (builder.Length > 0)
                builder.AppendLine().AppendLine();
            builder.Append(exportBlock);
        }

        WriteMergedPsm1(psm1Path, builder.ToString());
    }

    internal static string PrependFunctions(string[] functions, string content)
    {
        var block = (functions ?? System.Array.Empty<string>())
            .Where(static function => !string.IsNullOrWhiteSpace(function))
            .ToArray();
        if (block.Length == 0)
            return content;

        var prefix = string.Join(System.Environment.NewLine, block);
        return string.IsNullOrWhiteSpace(content)
            ? prefix
            : prefix + System.Environment.NewLine + System.Environment.NewLine + content;
    }

    internal static void WriteMergedPsm1(string path, string content)
    {
        GeneratedTextNormalizer.WriteUtf8Bom(path, content);
    }

    internal static bool IsAutoGeneratedPsm1(string content)
        => !string.IsNullOrWhiteSpace(content) &&
           content.IndexOf("Auto-generated by PowerForge", System.StringComparison.OrdinalIgnoreCase) >= 0;

    internal static string[] ResolveScriptFiles(string rootPath, InformationConfiguration? information)
    {
        if (string.IsNullOrWhiteSpace(rootPath) || !Directory.Exists(rootPath))
            return Array.Empty<string>();

        var root = Path.GetFullPath(rootPath);
        var files = new List<string>();
        foreach (var dir in ResolveMergeDirectories(information))
        {
            if (string.IsNullOrWhiteSpace(dir))
                continue;

            var full = Path.Combine(root, dir);
            if (!Directory.Exists(full))
                continue;

            try
            {
                files.AddRange(Directory.EnumerateFiles(full, "*.ps1", SearchOption.AllDirectories));
            }
            catch
            {
                // best effort only
            }
        }

        return NormalizeScriptFiles(files);
    }

    private static string[] NormalizeScriptFiles(IEnumerable<string> files)
        => files
            .Where(static file => !string.IsNullOrWhiteSpace(file))
            .Select(Path.GetFullPath)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static file => file, StringComparer.OrdinalIgnoreCase)
            .ToArray();

    private static string[] ResolveMergeDirectories(InformationConfiguration? information)
    {
        var ordered = new List<string> { "Classes", "Enums", "Private", "Public" };

        if (information?.IncludePS1 is { Length: > 0 })
        {
            foreach (var entry in information.IncludePS1)
            {
                if (string.IsNullOrWhiteSpace(entry))
                    continue;
                if (ordered.Any(existing => string.Equals(existing, entry, System.StringComparison.OrdinalIgnoreCase)))
                    continue;
                ordered.Add(entry);
            }
        }

        return ordered.ToArray();
    }

    private static string BuildMergedScriptContent(
        IReadOnlyList<string> files,
        ExportSet exports,
        bool fixRelativePaths,
        IReadOnlyDictionary<string, string[]>? conditionalFunctionDependencies,
        string moduleName)
    {
        var requires = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var usingLines = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var body = new StringBuilder(8192);

        foreach (var file in files)
        {
            if (string.IsNullOrWhiteSpace(file) || !File.Exists(file))
                continue;

            string[] lines;
            try
            {
                lines = File.ReadAllLines(file);
            }
            catch
            {
                continue;
            }

            var block = new List<string>();
            var extractedDirectives = ExtractPreambleDirectives(lines, requires, usingLines);
            for (var lineIndex = 0; lineIndex < lines.Length; lineIndex++)
            {
                if (extractedDirectives.Contains(lineIndex))
                    continue;

                var line = lines[lineIndex];
                block.Add(fixRelativePaths ? NormalizeMergedRelativePathReferences(line) : line);
            }

            if (block.Count == 0)
                continue;

            foreach (var line in block)
                body.AppendLine(line);

            body.AppendLine();
        }

        var header = new StringBuilder(1024);
        foreach (var require in requires.OrderBy(static line => line, StringComparer.OrdinalIgnoreCase))
            header.AppendLine(require);
        foreach (var usingLine in usingLines.OrderBy(static line => line, StringComparer.OrdinalIgnoreCase))
            header.AppendLine(usingLine);

        if (header.Length > 0)
            header.AppendLine();

        header.Append(body.ToString().TrimEnd());

        var merged = header.ToString().TrimEnd();
        var exportBlock = ModuleConditionalExportBlockBuilder.BuildExportBlock(
            exports,
            conditionalFunctionDependencies,
            moduleName);
        if (!string.IsNullOrWhiteSpace(exportBlock))
        {
            if (!string.IsNullOrWhiteSpace(merged))
                merged += System.Environment.NewLine + System.Environment.NewLine;
            merged += exportBlock.TrimEnd();
        }

        return merged;
    }

    private static HashSet<int> ExtractPreambleDirectives(
        IReadOnlyList<string> lines,
        ISet<string> requires,
        ISet<string> usingLines)
    {
        // PowerShell using statements are valid only in the script preamble. Restricting extraction to that region
        // prevents embedded languages in here-strings and block comments from being mistaken for module directives.
        var extracted = new HashSet<int>();
        var blockCommentDepth = 0;

        for (var index = 0; index < lines.Count; index++)
        {
            var kind = ClassifyPreambleLine(lines[index], ref blockCommentDepth);
            if (kind == PreambleLineKind.Trivia)
                continue;

            if (kind == PreambleLineKind.Requires)
            {
                requires.Add(lines[index].TrimStart());
                extracted.Add(index);
                continue;
            }

            if (kind == PreambleLineKind.Using)
            {
                usingLines.Add(lines[index].TrimStart());
                extracted.Add(index);
                continue;
            }

            break;
        }

        return extracted;
    }

    private static PreambleLineKind ClassifyPreambleLine(string line, ref int blockCommentDepth)
    {
        var index = 0;
        var hasLeadingBlockComment = false;

        while (index < line.Length)
        {
            if (blockCommentDepth > 0)
            {
                var commentStart = line.IndexOf("<#", index, System.StringComparison.Ordinal);
                var commentEnd = line.IndexOf("#>", index, System.StringComparison.Ordinal);
                if (commentStart >= 0 && (commentEnd < 0 || commentStart < commentEnd))
                {
                    blockCommentDepth++;
                    index = commentStart + 2;
                    continue;
                }

                if (commentEnd < 0)
                    return PreambleLineKind.Trivia;

                blockCommentDepth--;
                hasLeadingBlockComment = true;
                index = commentEnd + 2;
                continue;
            }

            while (index < line.Length && char.IsWhiteSpace(line[index]))
                index++;

            if (index >= line.Length)
                return PreambleLineKind.Trivia;

            if (line.IndexOf("<#", index, System.StringComparison.Ordinal) == index)
            {
                blockCommentDepth++;
                hasLeadingBlockComment = true;
                index += 2;
                continue;
            }

            if (line[index] == '#')
            {
                return !hasLeadingBlockComment && StartsWithDirective(line, index, "#requires")
                    ? PreambleLineKind.Requires
                    : PreambleLineKind.Trivia;
            }

            if (!hasLeadingBlockComment && StartsWithDirective(line, index, "using"))
                return PreambleLineKind.Using;

            return PreambleLineKind.Code;
        }

        return PreambleLineKind.Trivia;
    }

    private static bool StartsWithDirective(string line, int index, string directive)
    {
        if (line.IndexOf(directive, index, System.StringComparison.OrdinalIgnoreCase) != index)
            return false;

        var boundary = index + directive.Length;
        return boundary == line.Length || char.IsWhiteSpace(line[boundary]);
    }

    private enum PreambleLineKind
    {
        Trivia,
        Requires,
        Using,
        Code
    }

    private static string NormalizeMergedRelativePathReferences(string line)
    {
        if (string.IsNullOrEmpty(line))
            return line ?? string.Empty;

        var updated = line;
        // Legacy merged modules historically normalized both literal and evaluated parent-root references back to the
        // merged module root so inline script assets still resolve after the original folder hierarchy disappears.
        updated = updated.Replace("$PSScriptRoot\\..\\..\\", "$PSScriptRoot\\");
        updated = updated.Replace("$PSScriptRoot\\..\\", "$PSScriptRoot\\");
        updated = updated.Replace("$PSScriptRoot/../../", "$PSScriptRoot/");
        updated = updated.Replace("$PSScriptRoot/../", "$PSScriptRoot/");
        updated = updated.Replace("`$PSScriptRoot, '..',", "$PSScriptRoot,");
        updated = updated.Replace("`$PSScriptRoot,'..',", "$PSScriptRoot,");
        updated = updated.Replace("$PSScriptRoot, '..',", "$PSScriptRoot,");
        updated = updated.Replace("$PSScriptRoot,'..',", "$PSScriptRoot,");
        updated = updated.Replace("$PSScriptRoot, \"..\",", "$PSScriptRoot,");
        updated = updated.Replace("$PSScriptRoot,\"..\",", "$PSScriptRoot,");
        return updated;
    }

    private static string RemoveTrailingExportBlock(string content)
    {
        if (string.IsNullOrWhiteSpace(content))
            return content ?? string.Empty;

        var normalized = content.Replace("\r\n", "\n");
        // The generated export block is expected to be the tail of the merged PSM1, so syncing generated scripts
        // replaces that trailing block wholesale before appending a fresh one from the manifest.
        var exportStart = normalized.LastIndexOf("\n$FunctionsToExport = ", System.StringComparison.Ordinal);
        if (exportStart < 0 && normalized.StartsWith("$FunctionsToExport = ", System.StringComparison.Ordinal))
            exportStart = 0;

        if (exportStart < 0)
            return content;

        const string exportLine = "Export-ModuleMember -Function $FunctionsToExport -Alias $AliasesToExport -Cmdlet $CmdletsToExport";
        var exportLineIndex = normalized.IndexOf(exportLine, exportStart, System.StringComparison.Ordinal);
        if (exportLineIndex < 0)
            return content;

        return normalized.Substring(0, exportStart).TrimEnd('\n');
    }
}
