using System.Text;

namespace PowerForge;

/// <summary>
/// Emits the versioned, AOT-safe compiler/runtime contract shared by Strict managed backends.
/// </summary>
internal static class PowerShellRuntimeFreeContractSource
{
    internal static string GeneratePublicAbiMetadata(PowerShellCompilationAbiManifest abi)
        => new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .Append("[assembly: global::System.Reflection.AssemblyMetadata(\"PowerForge.PublicAbiSha256\", ")
            .Append(PowerShellCSharpLiteral.QuoteString(abi.Sha256)).AppendLine(")]")
            .ToString();

    internal static string Generate(PowerShellCompilationSemanticProfile profile, PowerShellCompilationAbiManifest abi)
        => new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .Append("[assembly: global::System.Reflection.AssemblyMetadata(\"PowerForge.SemanticProfile\", ")
            .Append(PowerShellCSharpLiteral.QuoteString(profile.Name + "/" + profile.Version)).AppendLine(")]")
            .Append("[assembly: global::System.Reflection.AssemblyMetadata(\"PowerForge.CompilerRuntimeAbi\", ")
            .Append(PowerShellCSharpLiteral.QuoteString(profile.CompilerRuntimeAbiVersion)).AppendLine(")]")
            .Append("[assembly: global::System.Reflection.AssemblyMetadata(\"PowerForge.PublicAbiSha256\", ")
            .Append(PowerShellCSharpLiteral.QuoteString(abi.Sha256)).AppendLine(")]")
            .AppendLine()
            .AppendLine("namespace PowerForge.Compiled;")
            .AppendLine()
            .AppendLine("internal static class PowerForgeRuntimeFreeContract")
            .AppendLine("{")
            .Append("    internal const string SemanticProfile = ").Append(PowerShellCSharpLiteral.QuoteString(profile.Name)).AppendLine(";")
            .Append("    internal const string SemanticProfileVersion = ").Append(PowerShellCSharpLiteral.QuoteString(profile.Version)).AppendLine(";")
            .Append("    internal const string CompilerRuntimeAbiVersion = ").Append(PowerShellCSharpLiteral.QuoteString(profile.CompilerRuntimeAbiVersion)).AppendLine(";")
            .Append("    internal const string PublicAbiSha256 = ").Append(PowerShellCSharpLiteral.QuoteString(abi.Sha256)).AppendLine(";")
            .AppendLine("}")
            .ToString();
}
