using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Management.Automation;
using System.Management.Automation.Language;
using System.Management.Automation.Runspaces;
using System.Text;

namespace PowerForge.Tests;

public sealed class ModuleMergeApplierTests
{
    [Fact]
    public void Apply_WarnsAndReturnsWithoutMerge_WhenNoScriptsOrPsm1Exist()
    {
        var root = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            var logger = new CollectingLogger();
            var plan = CreatePlan(root.FullName, mergeModule: true, mergeMissing: false);
            var mergeSources = new ModuleMergeSources(
                psm1Path: Path.Combine(root.FullName, "Missing.psm1"),
                scriptFiles: Array.Empty<string>(),
                mergedScriptContent: string.Empty,
                hasLib: false);

            var outcome = ModuleMergeApplier.Apply(logger, plan, mergeSources, missingReport: null);

            Assert.False(outcome.MergedModule);
            Assert.False(outcome.UsedExistingPsm1);
            Assert.Contains(logger.Warnings, static warning => warning.Contains("no script sources or PSM1 file were found", StringComparison.OrdinalIgnoreCase));
        }
        finally
        {
            try { root.Delete(recursive: true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void Apply_InlinesMergedScriptsIntoBootstrapper_WhenBinaryOutputsAreDetected()
    {
        var root = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";
            var logger = new CollectingLogger();
            var plan = CreatePlan(root.FullName, mergeModule: true, mergeMissing: false);
            var exports = new ExportSet(new[] { "Get-Test" }, Array.Empty<string>(), Array.Empty<string>());
            var conditionalDependencies = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
            {
                ["Missing.Dependency"] = new[] { "Get-Test" }
            };
            Directory.CreateDirectory(Path.Combine(root.FullName, "Lib", "Core"));
            Directory.CreateDirectory(Path.Combine(root.FullName, "Public"));
            File.WriteAllText(Path.Combine(root.FullName, "Lib", "Core", moduleName + ".dll"), string.Empty);
            File.Copy(
                typeof(ExportSet).Assembly.Location,
                Path.Combine(root.FullName, "PowerForge.dll"),
                overwrite: true);
            File.WriteAllText(Path.Combine(root.FullName, "Public", "Get-Test.ps1"), "function Get-Test { 'ok' }");
            ModuleBootstrapperGenerator.Generate(
                root.FullName,
                moduleName,
                exports,
                new[] { moduleName + ".dll" },
                handleRuntimes: false,
                conditionalFunctionDependencies: conditionalDependencies);

            var psm1Path = Path.Combine(root.FullName, moduleName + ".psm1");
            var mergeSources = new ModuleMergeSources(
                psm1Path: psm1Path,
                scriptFiles: new[] { Path.Combine(root.FullName, "Public", "Get-Test.ps1") },
                mergedScriptContent: "#requires -Version 5.1" + Environment.NewLine +
                                     "using namespace System.Text" + Environment.NewLine + Environment.NewLine +
                                     "using assembly 'PowerForge.dll'" + Environment.NewLine + Environment.NewLine +
                                     "class BinaryBackedType { [TestModule.Models.Widget] $Value }" + Environment.NewLine +
                                     "function Get-Test { [StringBuilder]::new().Append('ok').ToString() }" + Environment.NewLine +
                                     "function Get-TestRoot { $PSScriptRoot }" + Environment.NewLine +
                                     "function Get-TestCommandPath { $PSCommandPath }" + Environment.NewLine +
                                     "function Get-TestInvocationPath { $MyInvocation.MyCommand.Path }" +
                                     Environment.NewLine + Environment.NewLine +
                                     ModuleConditionalExportBlockBuilder.BuildExportBlock(exports, conditionalDependencies, moduleName),
                hasLib: true);

            var outcome = ModuleMergeApplier.Apply(logger, plan, mergeSources, missingReport: null);
            var mergedBootstrapper = File.ReadAllText(psm1Path);
            var deferredPayload = DecodeDeferredPayload(mergedBootstrapper);

            Assert.True(outcome.MergedModule);
            Assert.Contains("Auto-generated by PowerForge", mergedBootstrapper, StringComparison.Ordinal);
            Assert.Contains("class BinaryBackedType { [TestModule.Models.Widget] $Value }", deferredPayload, StringComparison.Ordinal);
            Assert.Contains("function Get-Test { [StringBuilder]::new().Append('ok').ToString() }", deferredPayload, StringComparison.Ordinal);
            Assert.Contains("function Get-TestRoot { $PSScriptRoot }", deferredPayload, StringComparison.Ordinal);
            Assert.Contains("function Get-TestCommandPath { $PSCommandPath }", deferredPayload, StringComparison.Ordinal);
            Assert.Contains("function Get-TestInvocationPath { $MyInvocation.MyCommand.Path }", deferredPayload, StringComparison.Ordinal);
            Assert.StartsWith("#requires -Version 5.1" + Environment.NewLine + "using namespace System.Text", deferredPayload, StringComparison.Ordinal);
            Assert.DoesNotContain("class BinaryBackedType", mergedBootstrapper, StringComparison.Ordinal);
            Assert.Contains("$PowerForgeMergedScriptSegmentBlock = [scriptblock]::Create($PowerForgeMergedScriptSegment)", mergedBootstrapper, StringComparison.Ordinal);
            Assert.Contains("$PowerForgeMergedScriptAst.FindAll({", mergedBootstrapper, StringComparison.Ordinal);
            Assert.DoesNotContain("'Public', '*.ps1'", mergedBootstrapper, StringComparison.Ordinal);
            Assert.DoesNotContain("using namespace System.Text", mergedBootstrapper, StringComparison.Ordinal);
            Assert.True(
                mergedBootstrapper.IndexOf("$ImportModule = Get-Command", StringComparison.Ordinal) <
                mergedBootstrapper.IndexOf("$PowerForgeMergedScriptSegmentBlock = [scriptblock]::Create", StringComparison.Ordinal));
            Assert.Equal(1, CountOccurrences(mergedBootstrapper.Replace("\r\n", "\n"), "\n$FunctionsToExport = "));
            Assert.Equal(1, CountOccurrences(mergedBootstrapper, "Export-ModuleMember -Function $FunctionsToExport"));
            Assert.Equal(1, CountOccurrences(mergedBootstrapper, "$PowerForgeCommandModuleDependencies = @{"));
            Parser.ParseFile(psm1Path, out _, out var parseErrors);
            Assert.Empty(parseErrors);

            using var powerShell = PowerShell.Create();
            powerShell.AddScript("Add-Type -TypeDefinition 'namespace TestModule.Models { public sealed class Widget {} }'");
            _ = powerShell.Invoke();
            Assert.False(
                powerShell.HadErrors,
                string.Join(Environment.NewLine, powerShell.Streams.Error.Select(static error => error.ToString())));
            Assert.Empty(powerShell.Streams.Error);
            powerShell.Commands.Clear();
            powerShell.Streams.Error.Clear();
            var embeddedPayloadBlock = ExtractMarkedSection(
                mergedBootstrapper,
                "# PowerForge script payload begin",
                "# PowerForge script payload end");
            var expectedRoot = root.FullName.Replace("'", "''", StringComparison.Ordinal);
            var expectedModulePath = psm1Path.Replace("'", "''", StringComparison.Ordinal);
            var unrelatedLocation = Path.GetTempPath().Replace("'", "''", StringComparison.Ordinal);
            powerShell.AddScript(
                "$PowerForgeModuleRoot = '" + expectedRoot + "'" + Environment.NewLine +
                "$PowerForgeModulePath = '" + expectedModulePath + "'" + Environment.NewLine +
                "Set-Location -LiteralPath '" + unrelatedLocation + "'" + Environment.NewLine +
                embeddedPayloadBlock + Environment.NewLine +
                "@((Get-Test), (Get-TestRoot), (Get-TestCommandPath), (Get-TestInvocationPath))");
            var output = powerShell.Invoke();
            Assert.False(
                powerShell.HadErrors,
                string.Join(Environment.NewLine, powerShell.Streams.Error.Select(static error => error.ToString())));
            Assert.Empty(powerShell.Streams.Error);
            Assert.Equal(4, output.Count);
            Assert.Equal("ok", output[0].BaseObject);
            Assert.Equal(root.FullName, output[1].BaseObject);
            Assert.Equal(psm1Path, output[2].BaseObject);
            Assert.Equal(psm1Path, output[3].BaseObject);
            Assert.Contains(logger.Infos, static message => message.Contains("binary module bootstrapper", StringComparison.OrdinalIgnoreCase));
        }
        finally
        {
            try { root.Delete(recursive: true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void Apply_RewritesRelativeMultilineUsingModuleSpecificationForDeferredParsing()
    {
        var root = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";
            Directory.CreateDirectory(Path.Combine(root.FullName, "Lib", "Core"));
            File.WriteAllText(Path.Combine(root.FullName, "Lib", "Core", moduleName + ".dll"), string.Empty);
            File.WriteAllText(
                Path.Combine(root.FullName, "Types.psm1"),
                "class PathBackedType { [string] $Value = 'typed' }");
            File.WriteAllText(
                Path.Combine(root.FullName, "Types.psd1"),
                "@{" + Environment.NewLine +
                "    RootModule = 'Types.psm1'" + Environment.NewLine +
                "    ModuleVersion = '1.0.0'" + Environment.NewLine +
                "    GUID = '4e7d8656-c82d-4ad7-8ad0-79fc8b827b87'" + Environment.NewLine +
                "}");

            var exports = new ExportSet(new[] { "Get-TypedValue" }, Array.Empty<string>(), Array.Empty<string>());
            ModuleBootstrapperGenerator.Generate(
                root.FullName,
                moduleName,
                exports,
                new[] { moduleName + ".dll" },
                handleRuntimes: false);
            var psm1Path = Path.Combine(root.FullName, moduleName + ".psm1");
            var mergedContent =
                "using module @{" + Environment.NewLine +
                "    ModuleName = './Types.psd1'" + Environment.NewLine +
                "    ModuleVersion = '1.0.0'" + Environment.NewLine +
                "}" + Environment.NewLine + Environment.NewLine +
                "function Get-TypedValue { [PathBackedType]::new().Value }";

            var outcome = ModuleMergeApplier.Apply(
                new CollectingLogger(),
                CreatePlan(root.FullName, mergeModule: true, mergeMissing: false),
                new ModuleMergeSources(psm1Path, new[] { Path.Combine(root.FullName, "Public", "Get-TypedValue.ps1") }, mergedContent, hasLib: true),
                missingReport: null);
            var bootstrapper = File.ReadAllText(psm1Path);
            var embeddedPayloadBlock = ExtractMarkedSection(
                bootstrapper,
                "# PowerForge script payload begin",
                "# PowerForge script payload end");

            Assert.True(outcome.MergedModule);
            Assert.Contains("ModuleSpecification.KeyValuePairs", bootstrapper, StringComparison.Ordinal);
            var initialSessionState = InitialSessionState.CreateDefault();
            if (OperatingSystem.IsWindows())
                initialSessionState.ExecutionPolicy = Microsoft.PowerShell.ExecutionPolicy.Bypass;
            using var runspace = RunspaceFactory.CreateRunspace(initialSessionState);
            runspace.Open();
            using var powerShell = PowerShell.Create();
            powerShell.Runspace = runspace;
            var expectedRoot = root.FullName.Replace("'", "''", StringComparison.Ordinal);
            var expectedModulePath = psm1Path.Replace("'", "''", StringComparison.Ordinal);
            var unrelatedLocation = Path.GetTempPath().Replace("'", "''", StringComparison.Ordinal);
            powerShell.AddScript(
                "$PowerForgeModuleRoot = '" + expectedRoot + "'" + Environment.NewLine +
                "$PowerForgeModulePath = '" + expectedModulePath + "'" + Environment.NewLine +
                "Set-Location -LiteralPath '" + unrelatedLocation + "'" + Environment.NewLine +
                embeddedPayloadBlock + Environment.NewLine +
                "Get-TypedValue");
            var output = powerShell.Invoke();

            Assert.False(
                powerShell.HadErrors,
                string.Join(Environment.NewLine, powerShell.Streams.Error.Select(static error => error.ToString())));
            Assert.Empty(powerShell.Streams.Error);
            Assert.Equal("typed", output[0].BaseObject);
        }
        finally
        {
            try { root.Delete(recursive: true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void Apply_PreservesTopLevelReturnBoundaryBetweenMergedSourceFiles()
    {
        var root = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";
            var publicRoot = Directory.CreateDirectory(Path.Combine(root.FullName, "Public"));
            var libCore = Directory.CreateDirectory(Path.Combine(root.FullName, "Lib", "Core"));
            File.WriteAllText(Path.Combine(libCore.FullName, moduleName + ".dll"), string.Empty);
            File.WriteAllText(Path.Combine(publicRoot.FullName, "00-Guard.ps1"), "return" + Environment.NewLine + "function Get-NeverLoaded { 'no' }");
            File.WriteAllText(
                Path.Combine(publicRoot.FullName, "01-Later.ps1"),
                "$MarkerText = @'" + Environment.NewLine +
                ModuleMergeComposer.MergedSourceEndMarker + Environment.NewLine +
                "'@" + Environment.NewLine +
                "function Get-Later { 'later' }");

            var exports = new ExportSet(new[] { "Get-Later" }, Array.Empty<string>(), Array.Empty<string>());
            ModuleBootstrapperGenerator.Generate(
                root.FullName,
                moduleName,
                exports,
                new[] { moduleName + ".dll" },
                handleRuntimes: false);
            var sources = ModuleMergeComposer.BuildSources(
                root.FullName,
                moduleName,
                information: null,
                exports,
                fixRelativePaths: false,
                exportAssemblies: new[] { moduleName + ".dll" });

            var outcome = ModuleMergeApplier.Apply(
                new CollectingLogger(),
                CreatePlan(root.FullName, mergeModule: true, mergeMissing: false),
                sources,
                missingReport: null);
            var bootstrapper = File.ReadAllText(Path.Combine(root.FullName, moduleName + ".psm1"));
            var embeddedPayloadBlock = ExtractMarkedSection(
                bootstrapper,
                "# PowerForge script payload begin",
                "# PowerForge script payload end");

            Assert.True(outcome.MergedModule);
            Assert.Equal(2, CountOccurrences(DecodeDeferredPayload(bootstrapper), ModuleMergeComposer.MergedSourceStartMarker));
            using var powerShell = PowerShell.Create();
            var expectedRoot = root.FullName.Replace("'", "''", StringComparison.Ordinal);
            powerShell.AddScript(
                "$PowerForgeModuleRoot = '" + expectedRoot + "'" + Environment.NewLine +
                embeddedPayloadBlock + Environment.NewLine +
                "Get-Later");
            var output = powerShell.Invoke();

            Assert.False(powerShell.HadErrors);
            Assert.Empty(powerShell.Streams.Error);
            Assert.Equal("later", output[0].BaseObject);
        }
        finally
        {
            try { root.Delete(recursive: true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void Apply_LoadsEnumSegmentsBeforeDependentClassSegments()
    {
        var root = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";
            var enumRoot = Directory.CreateDirectory(Path.Combine(root.FullName, "Enums"));
            var classRoot = Directory.CreateDirectory(Path.Combine(root.FullName, "Classes"));
            var libCore = Directory.CreateDirectory(Path.Combine(root.FullName, "Lib", "Core"));
            File.WriteAllText(Path.Combine(libCore.FullName, moduleName + ".dll"), string.Empty);
            File.WriteAllText(Path.Combine(enumRoot.FullName, "SegmentKind.ps1"), "enum SegmentKind { Ready }");
            File.WriteAllText(Path.Combine(classRoot.FullName, "SegmentRecord.ps1"), "class SegmentRecord { [SegmentKind] $Kind = [SegmentKind]::Ready }");

            var exports = new ExportSet(Array.Empty<string>(), Array.Empty<string>(), Array.Empty<string>());
            ModuleBootstrapperGenerator.Generate(
                root.FullName,
                moduleName,
                exports,
                new[] { moduleName + ".dll" },
                handleRuntimes: false);
            var sources = ModuleMergeComposer.BuildSources(
                root.FullName,
                moduleName,
                information: null,
                exports,
                fixRelativePaths: false,
                exportAssemblies: new[] { moduleName + ".dll" });

            var outcome = ModuleMergeApplier.Apply(
                new CollectingLogger(),
                CreatePlan(root.FullName, mergeModule: true, mergeMissing: false),
                sources,
                missingReport: null);
            var bootstrapper = File.ReadAllText(Path.Combine(root.FullName, moduleName + ".psm1"));
            var embeddedPayloadBlock = ExtractMarkedSection(
                bootstrapper,
                "# PowerForge script payload begin",
                "# PowerForge script payload end");

            Assert.True(outcome.MergedModule);
            using var powerShell = PowerShell.Create();
            var expectedRoot = root.FullName.Replace("'", "''", StringComparison.Ordinal);
            powerShell.AddScript(
                "$PowerForgeModuleRoot = '" + expectedRoot + "'" + Environment.NewLine +
                embeddedPayloadBlock + Environment.NewLine +
                "[SegmentRecord]::new().Kind.ToString()");
            var output = powerShell.Invoke();

            Assert.False(powerShell.HadErrors);
            Assert.Empty(powerShell.Streams.Error);
            Assert.Equal("Ready", output[0].BaseObject);
        }
        finally
        {
            try { root.Delete(recursive: true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void Apply_PreservesPerSourceUsingNamespaceScopes()
    {
        var root = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";
            var publicRoot = Directory.CreateDirectory(Path.Combine(root.FullName, "Public"));
            var libCore = Directory.CreateDirectory(Path.Combine(root.FullName, "Lib", "Core"));
            File.WriteAllText(Path.Combine(libCore.FullName, moduleName + ".dll"), string.Empty);
            File.WriteAllText(
                Path.Combine(publicRoot.FullName, "Get-ThreadingTimerType.ps1"),
                "using namespace System.Threading" + Environment.NewLine +
                "function Get-ThreadingTimerType { [Timer].FullName }");
            File.WriteAllText(
                Path.Combine(publicRoot.FullName, "Get-TimersTimerType.ps1"),
                "using namespace System.Timers" + Environment.NewLine +
                "function Get-TimersTimerType { [Timer].FullName }");

            var exports = new ExportSet(
                new[] { "Get-ThreadingTimerType", "Get-TimersTimerType" },
                Array.Empty<string>(),
                Array.Empty<string>());
            ModuleBootstrapperGenerator.Generate(
                root.FullName,
                moduleName,
                exports,
                new[] { moduleName + ".dll" },
                handleRuntimes: false);
            var sources = ModuleMergeComposer.BuildSources(
                root.FullName,
                moduleName,
                information: null,
                exports,
                fixRelativePaths: false,
                exportAssemblies: new[] { moduleName + ".dll" });

            var outcome = ModuleMergeApplier.Apply(
                new CollectingLogger(),
                CreatePlan(root.FullName, mergeModule: true, mergeMissing: false),
                sources,
                missingReport: null);
            var bootstrapper = File.ReadAllText(Path.Combine(root.FullName, moduleName + ".psm1"));
            var embeddedPayloadBlock = ExtractMarkedSection(
                bootstrapper,
                "# PowerForge script payload begin",
                "# PowerForge script payload end");

            Assert.True(outcome.MergedModule);
            using var powerShell = PowerShell.Create();
            var expectedRoot = root.FullName.Replace("'", "''", StringComparison.Ordinal);
            powerShell.AddScript(
                "$PowerForgeModuleRoot = '" + expectedRoot + "'" + Environment.NewLine +
                embeddedPayloadBlock + Environment.NewLine +
                "@((Get-ThreadingTimerType), (Get-TimersTimerType))");
            var output = powerShell.Invoke();

            Assert.False(
                powerShell.HadErrors,
                string.Join(Environment.NewLine, powerShell.Streams.Error.Select(static error => error.ToString())));
            Assert.Equal("System.Threading.Timer", output[0].BaseObject);
            Assert.Equal("System.Timers.Timer", output[1].BaseObject);
        }
        finally
        {
            try { root.Delete(recursive: true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void Apply_WritesMergedPsm1AndPrependsMissingFunctions_WhenMergeMissingIsEnabled()
    {
        var root = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";
            const string psm1Name = moduleName + ".psm1";
            var logger = new CollectingLogger();
            var psm1Path = Path.Combine(root.FullName, psm1Name);

            File.WriteAllText(psm1Path, "function Old-Bootstrap { 'old' }");

            var plan = CreatePlan(root.FullName, mergeModule: true, mergeMissing: true);
            var mergeSources = new ModuleMergeSources(
                psm1Path: psm1Path,
                scriptFiles: new[] { Path.Combine(root.FullName, "Public", "Get-Test.ps1") },
                mergedScriptContent: "function Get-Test { 'ok' }",
                hasLib: false);
            var missingReport = new MissingFunctionAnalysisResult(
                summary: Array.Empty<MissingCommandReference>(),
                summaryFiltered: Array.Empty<MissingCommandReference>(),
                functions: new[] { "function Get-Helper { 'helper' }" },
                functionsTopLevelOnly: new[] { "function Get-Helper { 'helper' }" });

            var outcome = ModuleMergeApplier.Apply(logger, plan, mergeSources, missingReport);
            var merged = File.ReadAllText(psm1Path);

            Assert.True(outcome.MergedModule);
            Assert.Equal(1, outcome.TopLevelInlinedFunctions);
            Assert.Equal(1, outcome.TotalInlinedFunctions);
            Assert.StartsWith("function Get-Helper", merged, StringComparison.Ordinal);
            Assert.Contains("function Get-Test", merged, StringComparison.Ordinal);
            Assert.Contains(logger.Warnings, static warning => warning.Contains("overwrite existing PSM1 content", StringComparison.OrdinalIgnoreCase));
        }
        finally
        {
            try { root.Delete(recursive: true); } catch { /* best effort */ }
        }
    }

    private static string DecodeDeferredPayload(string bootstrapper)
    {
        const string startMarker = "$PowerForgeMergedScriptPayloadBase64 = @'";
        const string endMarker = "'@";
        var start = bootstrapper.IndexOf(startMarker, StringComparison.Ordinal);
        Assert.True(start >= 0);
        start += startMarker.Length;
        var end = bootstrapper.IndexOf(endMarker, start, StringComparison.Ordinal);
        Assert.True(end > start);
        var encoded = bootstrapper.Substring(start, end - start);
        return Encoding.UTF8.GetString(Convert.FromBase64String(encoded));
    }

    private static int CountOccurrences(string content, string value)
    {
        var count = 0;
        var index = 0;
        while ((index = content.IndexOf(value, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += value.Length;
        }
        return count;
    }

    private static string ExtractMarkedSection(string content, string startMarker, string endMarker)
    {
        var start = content.IndexOf(startMarker, StringComparison.Ordinal);
        Assert.True(start >= 0);
        start += startMarker.Length;
        var end = content.IndexOf(endMarker, start, StringComparison.Ordinal);
        Assert.True(end > start);
        return content.Substring(start, end - start).Trim();
    }

    private static ModulePipelinePlan CreatePlan(string projectRoot, bool mergeModule, bool mergeMissing)
    {
        return new ModulePipelinePlan(
            moduleName: "TestModule",
            projectRoot: projectRoot,
            expectedVersion: "1.0.0",
            resolvedVersion: "1.0.0",
            preRelease: null,
            manifest: null,
            buildSpec: new ModuleBuildSpec
            {
                Name = "TestModule",
                SourcePath = projectRoot,
                Version = "1.0.0"
            },
            resolvedCsprojPath: null,
            syncNETProjectVersion: false,
            compatiblePSEditions: Array.Empty<string>(),
            requiredModules: Array.Empty<RequiredModuleReference>(),
            externalModuleDependencies: Array.Empty<string>(),
            requiredModulesForPackaging: Array.Empty<RequiredModuleReference>(),
            information: null,
            documentation: null,
            delivery: null,
            documentationBuild: null,
            compatibilitySettings: null,
            fileConsistencySettings: null,
            validationSettings: null,
            formatting: null,
            importModules: null,
            placeHolders: Array.Empty<PlaceHolderReplacement>(),
            placeHolderOption: null,
            commandModuleDependencies: new Dictionary<string, string[]>(),
            testsAfterMerge: Array.Empty<TestConfiguration>(),
            actions: Array.Empty<ConfigurationActionSegment>(),
            mergeModule: mergeModule,
            mergeMissing: mergeMissing,
            doNotAttemptToFixRelativePaths: false,
            approvedModules: Array.Empty<string>(),
            moduleSkip: null,
            signModule: false,
            signing: null,
            publishes: Array.Empty<ConfigurationPublishSegment>(),
            artefacts: Array.Empty<ConfigurationArtefactSegment>(),
            installEnabled: false,
            installStrategy: InstallationStrategy.AutoRevision,
            installKeepVersions: 1,
            installRoots: Array.Empty<string>(),
            installLegacyFlatHandling: LegacyFlatModuleHandling.Warn,
            installPreserveVersions: Array.Empty<string>(),
            installMissingModules: false,
            installMissingModulesForce: false,
            installMissingModulesPrerelease: false,
            installMissingModulesRepository: null,
            installMissingModulesCredential: null,
            stagingWasGenerated: false,
            deleteGeneratedStagingAfterRun: false);
    }

    private sealed class CollectingLogger : ILogger
    {
        public List<string> Infos { get; } = new();
        public List<string> Warnings { get; } = new();

        public bool IsVerbose => false;

        public void Info(string message)
        {
            Infos.Add(message ?? string.Empty);
        }

        public void Success(string message)
        {
        }

        public void Warn(string message) => Warnings.Add(message ?? string.Empty);

        public void Error(string message)
        {
        }

        public void Verbose(string message)
        {
        }
    }
}
