using System;

namespace PowerForge.Tests;

public sealed class ModuleIsolationScriptPatcherTests
{
    [Fact]
    public void CreatePatchedScript_ReplacesProfileBootstrapAndKeepsRemainingBody()
    {
        var source = string.Join(Environment.NewLine, new[]
        {
            "# line 1",
            "$RestModule = 'old'",
            "$RestModulePath = 'old'",
            "Import-Module $RestModulePath",
            "",
            "$ExoPowershellModule = 'old'",
            "$ExoPowershellModulePath = 'old'",
            "Import-Module $ExoPowershellModulePath",
            "function Connect-ExchangeOnline { 'body' }"
        });

        var patched = new ModuleIsolationScriptPatcher().CreatePatchedScript(source, ModuleIsolationProfile.ExchangeOnlineManagement);

        Assert.Contains("Generated by PowerForge Import-IsolatedModule", patched, StringComparison.Ordinal);
        Assert.Contains("PowerForge.ModuleIsolation.ModuleLoadContext", patched, StringComparison.Ordinal);
        Assert.Contains("'Microsoft.Exchange.Management.RestApiClient.dll'", patched, StringComparison.Ordinal);
        Assert.Contains("'Microsoft.Exchange.Management.ExoPowershellGalleryModule.dll'", patched, StringComparison.Ordinal);
        Assert.Contains("'Microsoft.Exchange.Management.'", patched, StringComparison.Ordinal);
        Assert.Contains("function Connect-ExchangeOnline", patched, StringComparison.Ordinal);
        Assert.DoesNotContain("Import-Module $RestModulePath", patched, StringComparison.Ordinal);
        Assert.Contains("Contexts[contextName] = context", patched, StringComparison.Ordinal);
        Assert.Contains("LoadedModuleAssemblies", patched, StringComparison.Ordinal);
    }

    [Fact]
    public void CreatePatchedScript_BinaryOnlyProfile_DoesNotAppendSourceBody()
    {
        var source = string.Join(Environment.NewLine, new[]
        {
            "Import-Module './netcoreapp3.1/Microsoft.TeamsCmdlets.PowerShell.Connect.dll'",
            "function Invoke-OriginalTeamsBootstrap { 'body' }"
        });
        var profile = new ModuleIsolationProfile
        {
            Name = "BinaryOnly",
            ModuleName = "BinaryOnly",
            ScriptRelativePath = "BinaryOnly.psm1",
            IsolatedScriptName = "BinaryOnly.ALC.psm1",
            IncludeSourceScriptBody = false,
            BinaryImports = ModuleIsolationProfile.MicrosoftTeams.BinaryImports,
            TypeAcceleratorNamespaces = ModuleIsolationProfile.MicrosoftTeams.TypeAcceleratorNamespaces,
            ContextName = "BinaryOnly.ALC"
        };

        var patched = new ModuleIsolationScriptPatcher().CreatePatchedScript(source, profile);

        Assert.Contains("'netcoreapp3.1/Microsoft.TeamsCmdlets.PowerShell.Connect.dll'", patched, StringComparison.Ordinal);
        Assert.Contains("'bin/Microsoft.Teams.ConfigAPI.Cmdlets.private.dll'", patched, StringComparison.Ordinal);
        Assert.Contains("'Microsoft.Teams.'", patched, StringComparison.Ordinal);
        Assert.DoesNotContain("Invoke-OriginalTeamsBootstrap", patched, StringComparison.Ordinal);
        Assert.DoesNotContain("Import-Module './netcoreapp3.1/Microsoft.TeamsCmdlets.PowerShell.Connect.dll'", patched, StringComparison.Ordinal);
    }

    [Fact]
    public void CreatePatchedScript_GraphProfile_SkipsDefaultImportAndLoadsDependencies()
    {
        var source = string.Join(Environment.NewLine, new[]
        {
            "$ModulePath = (Join-Path $PSScriptRoot 'Microsoft.Graph.Authentication.dll')",
            "$null = Import-Module -Name $ModulePath",
            "Export-ModuleMember -Cmdlet (Get-ModuleCmdlet -ModulePath $ModulePath)",
            "# SIG # Begin signature block",
            "# signed payload",
            "# SIG # End signature block"
        });

        var patched = new ModuleIsolationScriptPatcher().CreatePatchedScript(source, ModuleIsolationProfile.MicrosoftGraphAuthentication);

        Assert.Contains("'Dependencies/Core/Azure.Core.dll'", patched, StringComparison.Ordinal);
        Assert.Contains("'Microsoft.Graph.Authentication.dll'", patched, StringComparison.Ordinal);
        Assert.Contains("$PowerForgeIsolationDependencyAssemblies", patched, StringComparison.Ordinal);
        Assert.Contains("$ModulePath = (Join-Path $PSScriptRoot 'Microsoft.Graph.Authentication.dll')", patched, StringComparison.Ordinal);
        Assert.Contains("Export-ModuleMember -Cmdlet @('Add-MgEnvironment'", patched, StringComparison.Ordinal);
        Assert.Contains("'Invoke-MgRestMethod'", patched, StringComparison.Ordinal);
        Assert.DoesNotContain("Export-ModuleMember -Cmdlet (Get-ModuleCmdlet -ModulePath $ModulePath)", patched, StringComparison.Ordinal);
        Assert.DoesNotContain("$null = Import-Module -Name $ModulePath", patched, StringComparison.Ordinal);
        Assert.DoesNotContain("# SIG # Begin signature block", patched, StringComparison.Ordinal);
        Assert.DoesNotContain("# signed payload", patched, StringComparison.Ordinal);
    }
}
