using System;
using System.IO;
using System.Text;
using Xunit;

namespace PowerForge.Tests;

public sealed class ModulePipelineDeliveryMergedTests
{
    [Fact]
    public void Run_MergedBinaryModule_InlinesScriptsAndExcludesSourceFoldersFromArtefact()
    {
        var tempRoot = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";
            var projectRoot = Directory.CreateDirectory(Path.Combine(tempRoot.FullName, "src"));
            var publicDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Public"));
            var privateDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Private"));
            var libDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Lib"));
            var artefactsDir = Path.Combine(tempRoot.FullName, "artefacts");

            File.WriteAllText(Path.Combine(projectRoot.FullName, $"{moduleName}.psd1"), "@{ ModuleVersion = '1.0.0'; RootModule = 'TestModule.psm1'; FunctionsToExport = @('Get-Test'); CmdletsToExport = @(); AliasesToExport = @() }");
            File.WriteAllText(Path.Combine(projectRoot.FullName, $"{moduleName}.psm1"), string.Empty);
            File.WriteAllText(Path.Combine(publicDir.FullName, "Get-Test.ps1"), "function Get-Test { Invoke-Hidden }");
            File.WriteAllText(Path.Combine(privateDir.FullName, "Invoke-Hidden.ps1"), "function Invoke-Hidden { 'ok' }");
            File.WriteAllText(Path.Combine(libDir.FullName, moduleName + ".DLL"), string.Empty);

            var spec = new ModulePipelineSpec
            {
                Build = new ModuleBuildSpec
                {
                    Name = moduleName,
                    SourcePath = projectRoot.FullName,
                    Version = "1.0.0",
                    SkipDotNetBuild = true,
                    DisableBinaryCmdletScan = true,
                    ExportAssemblies = new[] { moduleName + ".DLL" },
                    KeepStaging = true
                },
                Install = new ModulePipelineInstallOptions { Enabled = false },
                Segments = new IConfigurationSegment[]
                {
                    new ConfigurationBuildSegment
                    {
                        BuildModule = new BuildModuleConfiguration { Merge = true }
                    },
                    new ConfigurationArtefactSegment
                    {
                        ArtefactType = ArtefactType.Unpacked,
                        Configuration = new ArtefactConfiguration
                        {
                            Enabled = true,
                            Path = artefactsDir
                        }
                    }
                }
            };

            var runner = new ModulePipelineRunner(new NullLogger());
            var plan = runner.Plan(spec);
            var result = runner.Run(spec, plan);

            var stagingPsm1 = File.ReadAllText(Path.Combine(result.BuildResult.StagingPath, moduleName + ".psm1"));
            var deferredPayload = DecodeDeferredPayload(stagingPsm1);
            Assert.Contains("Auto-generated by PowerForge", stagingPsm1, StringComparison.Ordinal);
            Assert.Contains("function Get-Test", deferredPayload, StringComparison.Ordinal);
            Assert.Contains("function Invoke-Hidden", deferredPayload, StringComparison.Ordinal);
            Assert.Contains("$LibraryFileNames = @('TestModule.DLL')", stagingPsm1, StringComparison.Ordinal);
            Assert.Contains("Where-Object { $_.Name -ieq $LibraryFileName }", stagingPsm1, StringComparison.Ordinal);
            Assert.Contains("$ModuleAssemblyPath = $ResolvedModuleAssembly.Path", stagingPsm1, StringComparison.Ordinal);
            Assert.DoesNotContain("'Public', '*.ps1'", stagingPsm1, StringComparison.Ordinal);
            Assert.DoesNotContain("'Private', '*.ps1'", stagingPsm1, StringComparison.Ordinal);

            var stagingLibraries = File.ReadAllText(Path.Combine(result.BuildResult.StagingPath, moduleName + ".Libraries.ps1"));
            Assert.Contains("'Lib\\TestModule.DLL'", stagingLibraries, StringComparison.Ordinal);

            var artefactRoot = Path.Combine(artefactsDir, moduleName);
            Assert.True(File.Exists(Path.Combine(artefactRoot, moduleName + ".psm1")));
            Assert.True(File.Exists(Path.Combine(artefactRoot, moduleName + ".Libraries.ps1")));
            Assert.True(File.Exists(Path.Combine(artefactRoot, "Lib", moduleName + ".DLL")));
            Assert.False(Directory.Exists(Path.Combine(artefactRoot, "Public")));
            Assert.False(Directory.Exists(Path.Combine(artefactRoot, "Private")));
        }
        finally
        {
            try { tempRoot.Delete(recursive: true); } catch { }
        }
    }

    private static string DecodeDeferredPayload(string bootstrapper)
    {
        const string startMarker = "$PowerForgeMergedScriptPayloadBase64 = @'";
        const string endMarker = "'@";
        var start = bootstrapper.IndexOf(startMarker, StringComparison.Ordinal);
        Assert.True(start >= 0);
        start += startMarker.Length;
        var end = bootstrapper.IndexOf(endMarker, start, StringComparison.Ordinal);
        Assert.True(end > start);
        var encoded = bootstrapper.Substring(start, end - start);
        return Encoding.UTF8.GetString(Convert.FromBase64String(encoded));
    }

    [Fact]
    public void Run_MergedModule_IncludesGeneratedDeliveryCommandsInRootPsm1_AndUnpackedArtefact()
    {
        var tempRoot = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";

            var projectRoot = Directory.CreateDirectory(Path.Combine(tempRoot.FullName, "src"));
            var publicDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Public"));
            var privateDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Private"));
            var internalsDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Internals"));
            var artefactsDir = Path.Combine(tempRoot.FullName, "artefacts");

            File.WriteAllText(Path.Combine(projectRoot.FullName, $"{moduleName}.psd1"), "@{ ModuleVersion = '1.0.0'; RootModule = 'TestModule.psm1'; FunctionsToExport = @(); CmdletsToExport = @(); AliasesToExport = @() }");
            File.WriteAllText(Path.Combine(projectRoot.FullName, $"{moduleName}.psm1"), string.Empty);
            File.WriteAllText(Path.Combine(publicDir.FullName, "Get-Test.ps1"), "function Get-Test { 'ok' }");
            File.WriteAllText(Path.Combine(privateDir.FullName, "Invoke-Hidden.ps1"), "function Invoke-Hidden { 'ok' }");
            File.WriteAllText(Path.Combine(internalsDir.FullName, "tool.txt"), "hello");

            var spec = new ModulePipelineSpec
            {
                Build = new ModuleBuildSpec
                {
                    Name = moduleName,
                    SourcePath = projectRoot.FullName,
                    Version = "1.0.0",
                    KeepStaging = true
                },
                Install = new ModulePipelineInstallOptions { Enabled = false },
                Segments = new IConfigurationSegment[]
                {
                    new ConfigurationBuildSegment
                    {
                        BuildModule = new BuildModuleConfiguration
                        {
                            Merge = true
                        }
                    },
                    new ConfigurationOptionsSegment
                    {
                        Options = new ConfigurationOptions
                        {
                            Delivery = new DeliveryOptionsConfiguration
                            {
                                Enable = true,
                                InternalsPath = "Internals",
                                GenerateInstallCommand = true,
                                GenerateUpdateCommand = true
                            }
                        }
                    },
                    new ConfigurationArtefactSegment
                    {
                        ArtefactType = ArtefactType.Unpacked,
                        Configuration = new ArtefactConfiguration
                        {
                            Enabled = true,
                            Path = artefactsDir
                        }
                    }
                }
            };

            var runner = new ModulePipelineRunner(new NullLogger());
            var plan = runner.Plan(spec);
            var result = runner.Run(spec, plan);

            var stagingPsm1 = File.ReadAllText(Path.Combine(result.BuildResult.StagingPath, $"{moduleName}.psm1"));
            Assert.Contains("function Install-TestModule", stagingPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("function Update-TestModule", stagingPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("$FunctionsToExport = @(", stagingPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("Install-TestModule", stagingPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("Update-TestModule", stagingPsm1, StringComparison.OrdinalIgnoreCase);

            var artefactPsm1Path = Path.Combine(artefactsDir, moduleName, $"{moduleName}.psm1");
            Assert.True(File.Exists(artefactPsm1Path));

            var artefactPsm1 = File.ReadAllText(artefactPsm1Path);
            Assert.Contains("function Install-TestModule", artefactPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("function Update-TestModule", artefactPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.True(File.Exists(Path.Combine(artefactsDir, moduleName, "Internals", "tool.txt")));
            Assert.False(Directory.Exists(Path.Combine(artefactsDir, moduleName, "Public")));
            Assert.False(Directory.Exists(Path.Combine(artefactsDir, moduleName, "Private")));
        }
        finally
        {
            try { tempRoot.Delete(recursive: true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void Run_ReusedExistingPsm1_EmbedsGeneratedDeliveryCommands_WithoutLooseScriptFolders()
    {
        var tempRoot = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "PowerForge.Tests", Guid.NewGuid().ToString("N")));
        try
        {
            const string moduleName = "TestModule";

            var projectRoot = Directory.CreateDirectory(Path.Combine(tempRoot.FullName, "src"));
            var publicDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Public"));
            var privateDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Private"));
            var internalsDir = Directory.CreateDirectory(Path.Combine(projectRoot.FullName, "Internals"));
            var artefactsDir = Path.Combine(tempRoot.FullName, "artefacts");

            File.WriteAllText(Path.Combine(projectRoot.FullName, $"{moduleName}.psd1"), "@{ ModuleVersion = '1.0.0'; RootModule = 'TestModule.psm1'; FunctionsToExport = @(); CmdletsToExport = @(); AliasesToExport = @() }");
            File.WriteAllText(Path.Combine(projectRoot.FullName, $"{moduleName}.psm1"), "function Get-TestModule { 'ok' }");
            File.WriteAllText(Path.Combine(internalsDir.FullName, "tool.txt"), "hello");

            var spec = new ModulePipelineSpec
            {
                Build = new ModuleBuildSpec
                {
                    Name = moduleName,
                    SourcePath = projectRoot.FullName,
                    Version = "1.0.0",
                    KeepStaging = true
                },
                Install = new ModulePipelineInstallOptions { Enabled = false },
                Segments = new IConfigurationSegment[]
                {
                    new ConfigurationBuildSegment
                    {
                        BuildModule = new BuildModuleConfiguration
                        {
                            Merge = true
                        }
                    },
                    new ConfigurationOptionsSegment
                    {
                        Options = new ConfigurationOptions
                        {
                            Delivery = new DeliveryOptionsConfiguration
                            {
                                Enable = true,
                                InternalsPath = "Internals",
                                GenerateInstallCommand = true,
                                GenerateUpdateCommand = true
                            }
                        }
                    },
                    new ConfigurationArtefactSegment
                    {
                        ArtefactType = ArtefactType.Unpacked,
                        Configuration = new ArtefactConfiguration
                        {
                            Enabled = true,
                            Path = artefactsDir
                        }
                    }
                }
            };

            var runner = new ModulePipelineRunner(new NullLogger());
            var plan = runner.Plan(spec);
            var result = runner.Run(spec, plan);

            var stagingPsm1 = File.ReadAllText(Path.Combine(result.BuildResult.StagingPath, $"{moduleName}.psm1"));
            Assert.Contains("Auto-generated by PowerForge", stagingPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("function Install-TestModule", stagingPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("function Update-TestModule", stagingPsm1, StringComparison.OrdinalIgnoreCase);

            var artefactPsm1Path = Path.Combine(artefactsDir, moduleName, $"{moduleName}.psm1");
            Assert.True(File.Exists(artefactPsm1Path));

            var artefactPsm1 = File.ReadAllText(artefactPsm1Path);
            Assert.Contains("Auto-generated by PowerForge", artefactPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("function Install-TestModule", artefactPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("function Update-TestModule", artefactPsm1, StringComparison.OrdinalIgnoreCase);
            Assert.True(File.Exists(Path.Combine(artefactsDir, moduleName, "Internals", "tool.txt")));
            Assert.False(Directory.Exists(Path.Combine(artefactsDir, moduleName, "Public")));
            Assert.False(Directory.Exists(Path.Combine(artefactsDir, moduleName, "Private")));
        }
        finally
        {
            try { tempRoot.Delete(recursive: true); } catch { /* best effort */ }
        }
    }
}
