namespace PowerForge;

/// <summary>
/// Planned execution details computed from a <see cref="ModulePipelineSpec"/> and its configuration segments.
/// </summary>
public sealed class ModulePipelinePlan
{
    /// <summary>
    /// Module name resolved for the pipeline.
    /// </summary>
    public string ModuleName { get; }

    /// <summary>
    /// Source/project root directory used for staging.
    /// </summary>
    public string ProjectRoot { get; }

    /// <summary>
    /// Version input provided by configuration (can be an X-pattern like <c>2.0.X</c>).
    /// </summary>
    public string ExpectedVersion { get; }

    /// <summary>
    /// Resolved version after stepping.
    /// </summary>
    public string ResolvedVersion { get; }

    /// <summary>
    /// Optional prerelease tag (used for token replacements).
    /// </summary>
    public string? PreRelease { get; }

    /// <summary>
    /// Final build spec used for <see cref="ModuleBuildPipeline.BuildToStaging"/>.
    /// </summary>
    public ModuleBuildSpec BuildSpec { get; }

    /// <summary>
    /// Compatible PowerShell editions requested by configuration (used for manifest patching and install root derivation).
    /// </summary>
    public string[] CompatiblePSEditions { get; }

    /// <summary>
    /// Required module entries requested by configuration (used for manifest patching).
    /// </summary>
    public ManifestEditor.RequiredModule[] RequiredModules { get; }

    /// <summary>
    /// Required modules that should be packaged into artefacts when enabled (excludes ExternalModule dependencies).
    /// </summary>
    public ManifestEditor.RequiredModule[] RequiredModulesForPackaging { get; }

    /// <summary>
    /// Optional information configuration (include/exclude patterns) used for artefact packaging.
    /// </summary>
    public InformationConfiguration? Information { get; }

    /// <summary>
    /// Optional documentation configuration (docs folder + readme path).
    /// </summary>
    public DocumentationConfiguration? Documentation { get; }

    /// <summary>
    /// Optional documentation build configuration (enable/clean/tool).
    /// </summary>
    public BuildDocumentationConfiguration? DocumentationBuild { get; }

    /// <summary>
    /// Publish configuration segments enabled for this pipeline run.
    /// </summary>
    public ConfigurationPublishSegment[] Publishes { get; }

    /// <summary>
    /// Artefact configuration segments enabled for this pipeline run.
    /// </summary>
    public ConfigurationArtefactSegment[] Artefacts { get; }

    /// <summary>
    /// When true, installs the module after building.
    /// </summary>
    public bool InstallEnabled { get; }

    /// <summary>
    /// Installation strategy used when installing.
    /// </summary>
    public InstallationStrategy InstallStrategy { get; }

    /// <summary>
    /// Number of versions to keep per module root when installing.
    /// </summary>
    public int InstallKeepVersions { get; }

    /// <summary>
    /// Destination module roots used for install. When empty, defaults are used by the installer.
    /// </summary>
    public string[] InstallRoots { get; }

    /// <summary>
    /// When true, the staging directory was generated by the pipeline (not explicitly provided).
    /// </summary>
    public bool StagingWasGenerated { get; }

    /// <summary>
    /// When true, the pipeline should delete the generated staging folder after a successful run.
    /// </summary>
    public bool DeleteGeneratedStagingAfterRun { get; }

    /// <summary>
    /// Creates a new plan instance.
    /// </summary>
    public ModulePipelinePlan(
        string moduleName,
        string projectRoot,
        string expectedVersion,
        string resolvedVersion,
        string? preRelease,
        ModuleBuildSpec buildSpec,
        string[] compatiblePSEditions,
        ManifestEditor.RequiredModule[] requiredModules,
        ManifestEditor.RequiredModule[] requiredModulesForPackaging,
        InformationConfiguration? information,
        DocumentationConfiguration? documentation,
        BuildDocumentationConfiguration? documentationBuild,
        ConfigurationPublishSegment[] publishes,
        ConfigurationArtefactSegment[] artefacts,
        bool installEnabled,
        InstallationStrategy installStrategy,
        int installKeepVersions,
        string[] installRoots,
        bool stagingWasGenerated,
        bool deleteGeneratedStagingAfterRun)
    {
        ModuleName = moduleName;
        ProjectRoot = projectRoot;
        ExpectedVersion = expectedVersion;
        ResolvedVersion = resolvedVersion;
        PreRelease = preRelease;
        BuildSpec = buildSpec;
        CompatiblePSEditions = compatiblePSEditions;
        RequiredModules = requiredModules;
        RequiredModulesForPackaging = requiredModulesForPackaging;
        Information = information;
        Documentation = documentation;
        DocumentationBuild = documentationBuild;
        Publishes = publishes ?? Array.Empty<ConfigurationPublishSegment>();
        Artefacts = artefacts;
        InstallEnabled = installEnabled;
        InstallStrategy = installStrategy;
        InstallKeepVersions = installKeepVersions;
        InstallRoots = installRoots;
        StagingWasGenerated = stagingWasGenerated;
        DeleteGeneratedStagingAfterRun = deleteGeneratedStagingAfterRun;
    }
}
