#!/usr/bin/env bash
set -Eeuo pipefail

umask 022

state_dir="${POWERFORGE_CLOUDFLARE_STATE_DIR:-/var/lib/powerforge/cloudflare-origin}"
state_file="${state_dir}/cidrs.txt"
apache_conf_name="${POWERFORGE_CLOUDFLARE_APACHE_CONF_NAME:-powerforge-cloudflare-origin}"
apache_conf_file="/etc/apache2/conf-available/${apache_conf_name}.conf"
apache_service="${POWERFORGE_CLOUDFLARE_APACHE_SERVICE:-apache2}"
manage_ufw="${POWERFORGE_CLOUDFLARE_MANAGE_UFW:-1}"
lock_file="${POWERFORGE_CLOUDFLARE_LOCK_FILE:-/run/lock/powerforge-cloudflare-origin-sync.lock}"

fail() {
  echo "powerforge-cloudflare-origin-sync: $*" >&2
  exit 1
}

[[ "${EUID}" -eq 0 ]] || fail 'must run as root'
[[ "$state_dir" == /* && "$state_dir" != / ]] || fail 'POWERFORGE_CLOUDFLARE_STATE_DIR must be an absolute non-root path'
[[ "$lock_file" == /* ]] || fail 'POWERFORGE_CLOUDFLARE_LOCK_FILE must be an absolute path'
[[ "$apache_conf_name" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$ ]] || fail 'invalid Apache configuration name'
[[ "$apache_service" =~ ^[A-Za-z0-9_.@-]+$ ]] || fail 'invalid Apache service name'
[[ "$manage_ufw" == 0 || "$manage_ufw" == 1 ]] || fail 'POWERFORGE_CLOUDFLARE_MANAGE_UFW must be 0 or 1'

required_commands=(a2disconf a2enconf a2enmod apachectl curl flock install python3 systemctl)
if [[ "$manage_ufw" == 1 ]]; then
  required_commands+=(ufw)
fi
for command_name in "${required_commands[@]}"; do
  command -v "$command_name" >/dev/null 2>&1 || fail "required command not found: $command_name"
done

install -d -m 0755 "$state_dir" "$(dirname "$lock_file")"
exec 9>"$lock_file"
if ! flock -n 9; then
  echo 'powerforge-cloudflare-origin-sync: another synchronization is already running'
  exit 0
fi

tmp_dir="$(mktemp -d)"
trap 'rm -rf -- "$tmp_dir"' EXIT

download_ranges() {
  local url="$1"
  local output="$2"
  curl \
    --proto '=https' \
    --proto-redir '=https' \
    --tlsv1.2 \
    --fail \
    --silent \
    --show-error \
    --location \
    --connect-timeout 10 \
    --max-time 30 \
    --max-filesize 65536 \
    --retry 3 \
    --retry-all-errors \
    --output "$output" \
    "$url"
}

download_ranges 'https://www.cloudflare.com/ips-v4' "$tmp_dir/ips-v4"
download_ranges 'https://www.cloudflare.com/ips-v6' "$tmp_dir/ips-v6"

python3 - "$tmp_dir/ips-v4" "$tmp_dir/ips-v6" "$tmp_dir/cidrs.txt" <<'PY'
import ipaddress
import pathlib
import sys

sources = ((pathlib.Path(sys.argv[1]), 4, 5), (pathlib.Path(sys.argv[2]), 6, 2))
networks = set()

for source, expected_version, minimum_count in sources:
    parsed = set()
    for raw_line in source.read_text(encoding="ascii").splitlines():
        value = raw_line.strip()
        if not value:
            continue
        network = ipaddress.ip_network(value, strict=True)
        if network.version != expected_version or not network.is_global:
            raise SystemExit(f"Rejected non-public or wrong-family Cloudflare CIDR: {value}")
        parsed.add(network)
        networks.add(network)
    if len(parsed) < minimum_count:
        raise SystemExit(f"Cloudflare IPv{expected_version} response contained too few CIDRs")

ordered = sorted(networks, key=lambda item: (item.version, int(item.network_address), item.prefixlen))
pathlib.Path(sys.argv[3]).write_text("".join(f"{item}\n" for item in ordered), encoding="ascii")
PY

[[ -s "$tmp_dir/cidrs.txt" ]] || fail 'validated Cloudflare CIDR set is empty'

if [[ "$manage_ufw" == 1 ]]; then
  while IFS= read -r cidr; do
    [[ -n "$cidr" ]] || continue
    ufw allow proto tcp from "$cidr" to any port 80 comment 'PowerForge Cloudflare HTTP' >/dev/null
    ufw allow proto tcp from "$cidr" to any port 443 comment 'PowerForge Cloudflare HTTPS' >/dev/null
  done < "$tmp_dir/cidrs.txt"

  if [[ -s "$state_file" ]]; then
    while IFS= read -r cidr; do
      [[ -n "$cidr" ]] || continue
      if ! grep -Fxq "$cidr" "$tmp_dir/cidrs.txt"; then
        ufw --force delete allow proto tcp from "$cidr" to any port 80 >/dev/null 2>&1 || true
        ufw --force delete allow proto tcp from "$cidr" to any port 443 >/dev/null 2>&1 || true
      fi
    done < "$state_file"
  fi
fi

{
  echo '# Trust the Cloudflare client address header only from validated Cloudflare edge networks.'
  echo '# Generated by powerforge-cloudflare-origin-sync; do not edit manually.'
  echo '<IfModule mod_remoteip.c>'
  echo '    RemoteIPHeader CF-Connecting-IP'
  while IFS= read -r cidr; do
    [[ -n "$cidr" ]] || continue
    echo "    RemoteIPTrustedProxy $cidr"
  done < "$tmp_dir/cidrs.txt"
  echo '</IfModule>'
} > "$tmp_dir/apache.conf"

had_previous_conf=0
had_previous_enabled=0
if [[ -f "$apache_conf_file" ]]; then
  cp -- "$apache_conf_file" "$tmp_dir/apache.previous.conf"
  had_previous_conf=1
fi
if [[ -e "/etc/apache2/conf-enabled/${apache_conf_name}.conf" ]]; then
  had_previous_enabled=1
fi

restore_apache_configuration() {
  if [[ "$had_previous_conf" == 1 ]]; then
    install -m 0644 "$tmp_dir/apache.previous.conf" "$apache_conf_file"
  else
    rm -f -- "$apache_conf_file"
  fi
  if [[ "$had_previous_enabled" == 0 ]]; then
    a2disconf "$apache_conf_name" >/dev/null 2>&1 || true
  fi
  apachectl configtest >/dev/null 2>&1 && systemctl reload "$apache_service" >/dev/null 2>&1 || true
}

install -m 0644 "$tmp_dir/apache.conf" "$apache_conf_file"
if ! a2enmod remoteip >/dev/null || ! a2enconf "$apache_conf_name" >/dev/null; then
  restore_apache_configuration
  fail 'Apache module or configuration enablement failed; previous configuration restored'
fi
if ! apachectl configtest >/dev/null; then
  restore_apache_configuration
  fail 'Apache configuration validation failed; previous configuration restored'
fi
if ! systemctl reload "$apache_service"; then
  restore_apache_configuration
  fail 'Apache reload failed; previous configuration restored'
fi

install -m 0644 "$tmp_dir/cidrs.txt" "$state_file"
echo "powerforge-cloudflare-origin-sync: synchronized $(wc -l < "$state_file") Cloudflare networks"
