using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace PowerForge;

/// <summary>
/// Describes a Windows installer in host-neutral PowerForge terms before it is emitted as WiX source.
/// </summary>
public sealed class PowerForgeInstallerDefinition
{
    /// <summary>
    /// Product and package identity for the generated installer.
    /// </summary>
    public PowerForgeInstallerProduct Product { get; set; } = new();

    /// <summary>
    /// Directory id used by WiX UI and install-folder-aware components.
    /// </summary>
    public string InstallDirectoryId { get; set; } = "INSTALLFOLDER";

    /// <summary>
    /// Company folder name under Program Files.
    /// </summary>
    public string CompanyFolderName { get; set; } = "Evotec";

    /// <summary>
    /// Whether the install directory is nested below <see cref="CompanyFolderName"/>.
    /// </summary>
    public bool UseCompanyFolder { get; set; } = true;

    /// <summary>
    /// Application folder name under the company folder.
    /// </summary>
    public string InstallDirectoryName { get; set; } = "Application";

    /// <summary>
    /// Optional component group generated by the publish/harvest pipeline and referenced from the main feature.
    /// </summary>
    public string? PayloadComponentGroupId { get; set; }

    /// <summary>
    /// Property inputs exposed to UI, command-line, and custom actions.
    /// </summary>
    public List<PowerForgeInstallerInput> Inputs { get; set; } = new();

    /// <summary>
    /// Optional custom dialogs composed from installer inputs.
    /// </summary>
    public List<PowerForgeInstallerDialog> Dialogs { get; set; } = new();

    /// <summary>
    /// Additional directory trees required by installer components.
    /// </summary>
    public List<PowerForgeInstallerDirectoryTree> Directories { get; set; } = new();

    /// <summary>
    /// Components that are emitted into directory references and linked from the product feature.
    /// </summary>
    public List<PowerForgeInstallerComponent> Components { get; set; } = new();
}

/// <summary>
/// Product and package identity for a generated Windows installer.
/// </summary>
public sealed class PowerForgeInstallerProduct
{
    /// <summary>
    /// Product display name shown by Windows Installer.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Product manufacturer.
    /// </summary>
    public string Manufacturer { get; set; } = "Evotec";

    /// <summary>
    /// MSI-compatible product version.
    /// </summary>
    public string Version { get; set; } = "1.0.0";

    /// <summary>
    /// Stable upgrade code for major-upgrade detection.
    /// </summary>
    public string UpgradeCode { get; set; } = string.Empty;

    /// <summary>
    /// Installation scope for the package.
    /// </summary>
    public PowerForgeInstallerScope Scope { get; set; } = PowerForgeInstallerScope.PerMachine;

    /// <summary>
    /// Downgrade message shown when a newer version is installed.
    /// </summary>
    public string DowngradeErrorMessage { get; set; } = "A newer version of [ProductName] is already installed.";
}

/// <summary>
/// Installation scope emitted to the WiX package.
/// </summary>
public enum PowerForgeInstallerScope
{
    /// <summary>
    /// Install for all users.
    /// </summary>
    PerMachine,

    /// <summary>
    /// Install for the current user.
    /// </summary>
    PerUser
}

/// <summary>
/// User or silent-install input exposed as an MSI property.
/// </summary>
public sealed class PowerForgeInstallerInput
{
    /// <summary>
    /// Logical input id.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// MSI property name. Public properties should be uppercase for command-line use.
    /// </summary>
    public string PropertyName { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable label used by generated dialogs.
    /// </summary>
    public string Label { get; set; } = string.Empty;

    /// <summary>
    /// Optional description shown by generated dialogs.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Input kind used to choose generated UI controls.
    /// </summary>
    public PowerForgeInstallerInputKind Kind { get; set; } = PowerForgeInstallerInputKind.Text;

    /// <summary>
    /// Default property value.
    /// </summary>
    public string? DefaultValue { get; set; }

    /// <summary>
    /// Marks the property as secure so it can flow into deferred custom actions.
    /// </summary>
    public bool Secure { get; set; }

    /// <summary>
    /// Adds the property to MsiHiddenProperties to avoid logging sensitive values when possible.
    /// </summary>
    public bool Hidden { get; set; }

    /// <summary>
    /// Requires a non-empty value before a generated dialog can continue. Checkbox inputs follow MSI semantics:
    /// any non-empty property value is treated as checked. Required radio groups must set a default choice.
    /// </summary>
    public bool Required { get; set; }

    /// <summary>
    /// Optional message shown by generated dialogs when this is the only missing required input.
    /// </summary>
    public string? RequiredMessage { get; set; }

    /// <summary>
    /// Minimum accepted text length for authored validation metadata.
    /// </summary>
    public int? MinLength { get; set; }

    /// <summary>
    /// Maximum accepted text length for authored validation metadata.
    /// </summary>
    public int? MaxLength { get; set; }

    /// <summary>
    /// Optional .NET regular expression used to validate authored default values.
    /// </summary>
    public string? ValidationPattern { get; set; }

    /// <summary>
    /// Message to show when generated runtime validation is added for this input.
    /// </summary>
    public string? ValidationMessage { get; set; }

    /// <summary>
    /// Choices for radio or combo style inputs.
    /// </summary>
    public List<PowerForgeInstallerInputChoice> Choices { get; set; } = new();
}

/// <summary>
/// Input control shape for generated installer dialogs.
/// </summary>
public enum PowerForgeInstallerInputKind
{
    /// <summary>
    /// Free-form text input.
    /// </summary>
    Text,

    /// <summary>
    /// Sensitive text input.
    /// </summary>
    Password,

    /// <summary>
    /// File path input.
    /// </summary>
    FilePath,

    /// <summary>
    /// Folder path input.
    /// </summary>
    FolderPath,

    /// <summary>
    /// Checkbox input.
    /// </summary>
    Checkbox,

    /// <summary>
    /// Radio-button choice input.
    /// </summary>
    RadioGroup,

    /// <summary>
    /// License key or license token input.
    /// </summary>
    LicenseKey
}

/// <summary>
/// Choice for radio-button style installer inputs.
/// </summary>
public sealed class PowerForgeInstallerInputChoice
{
    /// <summary>
    /// Property value assigned when the choice is selected.
    /// </summary>
    public string Value { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable choice text.
    /// </summary>
    public string Text { get; set; } = string.Empty;
}

/// <summary>
/// Generated dialog composed from one or more installer inputs.
/// </summary>
public sealed class PowerForgeInstallerDialog
{
    /// <summary>
    /// WiX dialog id.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Dialog title.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Dialog description.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Input ids rendered by this dialog.
    /// </summary>
    public List<string> InputIds { get; set; } = new();
}

/// <summary>
/// Directory tree rooted under a WiX standard directory or an existing directory reference.
/// </summary>
public sealed class PowerForgeInstallerDirectoryTree
{
    /// <summary>
    /// WiX standard directory id such as CommonAppDataFolder or ProgramMenuFolder.
    /// </summary>
    public string StandardDirectoryId { get; set; } = string.Empty;

    /// <summary>
    /// Existing WiX directory id to attach the tree to, such as INSTALLFOLDER.
    /// </summary>
    public string? DirectoryRefId { get; set; }

    /// <summary>
    /// Ordered directory segments below the root directory.
    /// </summary>
    public List<PowerForgeInstallerDirectorySegment> Segments { get; set; } = new();
}

/// <summary>
/// Directory segment in a generated WiX directory tree.
/// </summary>
public sealed class PowerForgeInstallerDirectorySegment
{
    /// <summary>
    /// WiX directory id.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Folder name.
    /// </summary>
    public string Name { get; set; } = string.Empty;
}

/// <summary>
/// Base type for generated WiX components.
/// </summary>
[JsonConverter(typeof(PowerForgeInstallerComponentJsonConverter))]
public abstract class PowerForgeInstallerComponent
{
    /// <summary>
    /// WiX component id.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Directory reference where the component is emitted.
    /// </summary>
    public string DirectoryRefId { get; set; } = "INSTALLFOLDER";

    /// <summary>
    /// Optional explicit component GUID. Use "*" for auto-generated component GUIDs.
    /// </summary>
    public string Guid { get; set; } = "*";
}

/// <summary>
/// File component emitted into a directory reference.
/// </summary>
public sealed class PowerForgeInstallerFileComponent : PowerForgeInstallerComponent
{
    /// <summary>
    /// WiX file id.
    /// </summary>
    public string FileId { get; set; } = string.Empty;

    /// <summary>
    /// Source file path or preprocessor expression.
    /// </summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>
    /// Optional installed filename.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Whether the file is the component key path.
    /// </summary>
    public bool KeyPath { get; set; } = true;

    /// <summary>
    /// Marks the component as permanent.
    /// </summary>
    public bool Permanent { get; set; }

    /// <summary>
    /// Prevents overwriting an existing file.
    /// </summary>
    public bool NeverOverwrite { get; set; }
}

/// <summary>
/// Folder component emitted with CreateFolder.
/// </summary>
public sealed class PowerForgeInstallerFolderComponent : PowerForgeInstallerComponent
{
    /// <summary>
    /// Marks the folder component as permanent.
    /// </summary>
    public bool Permanent { get; set; }
}

/// <summary>
/// RemoveFolderEx component controlled by an installer property.
/// </summary>
public sealed class PowerForgeInstallerRemoveFolderComponent : PowerForgeInstallerComponent
{
    /// <summary>
    /// MSI condition required before removing the folder tree.
    /// </summary>
    public string Condition { get; set; } = string.Empty;

    /// <summary>
    /// RemoveFolderEx property containing the folder path.
    /// </summary>
    public string PropertyName { get; set; } = string.Empty;
}

/// <summary>
/// Windows service component with ServiceInstall and ServiceControl metadata.
/// </summary>
public sealed class PowerForgeInstallerServiceComponent : PowerForgeInstallerComponent
{
    /// <summary>
    /// WiX file id for the service executable.
    /// </summary>
    public string FileId { get; set; } = string.Empty;

    /// <summary>
    /// Service executable source path or preprocessor expression.
    /// </summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>
    /// Windows service name.
    /// </summary>
    public string ServiceName { get; set; } = string.Empty;

    /// <summary>
    /// Windows service display name.
    /// </summary>
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>
    /// Windows service description.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Service arguments.
    /// </summary>
    public string? Arguments { get; set; }

    /// <summary>
    /// Service account.
    /// </summary>
    public string Account { get; set; } = "LocalSystem";

    /// <summary>
    /// Service start mode.
    /// </summary>
    public string Start { get; set; } = "auto";

    /// <summary>
    /// Whether the service should use delayed auto-start.
    /// </summary>
    public bool DelayedAutoStart { get; set; }
}

/// <summary>
/// Registry value component, optionally populated from an MSI property.
/// </summary>
public sealed class PowerForgeInstallerRegistryValueComponent : PowerForgeInstallerComponent
{
    /// <summary>
    /// Registry root, for example HKLM or HKCU.
    /// </summary>
    public string Root { get; set; } = "HKLM";

    /// <summary>
    /// Registry key path below <see cref="Root"/>.
    /// </summary>
    public string Key { get; set; } = string.Empty;

    /// <summary>
    /// Registry value name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Literal registry value. Supports WiX formatted values such as <c>[INSTALLFOLDER]</c>.
    /// </summary>
    public string? Value { get; set; }

    /// <summary>
    /// MSI property whose value is written as the registry value.
    /// </summary>
    public string? ValueProperty { get; set; }

    /// <summary>
    /// WiX registry value type, for example string or integer.
    /// </summary>
    public string ValueType { get; set; } = "string";

    /// <summary>
    /// Whether the registry value is the component key path.
    /// </summary>
    public bool KeyPath { get; set; } = true;
}

/// <summary>
/// Shortcut component with a registry key path.
/// </summary>
public sealed class PowerForgeInstallerShortcutComponent : PowerForgeInstallerComponent
{
    /// <summary>
    /// WiX shortcut id.
    /// </summary>
    public string ShortcutId { get; set; } = string.Empty;

    /// <summary>
    /// Shortcut display name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Target file id.
    /// </summary>
    public string? TargetFileId { get; set; }

    /// <summary>
    /// Optional direct shortcut target such as <c>[INSTALLFOLDER]MyApp.exe</c>.
    /// </summary>
    public string? Target { get; set; }

    /// <summary>
    /// Working directory id.
    /// </summary>
    public string WorkingDirectoryId { get; set; } = "INSTALLFOLDER";

    /// <summary>
    /// Registry key used as component key path.
    /// </summary>
    public string RegistryKey { get; set; } = @"Software\Evotec\PowerForge";

    /// <summary>
    /// Registry value name used as component key path.
    /// </summary>
    public string RegistryValueName { get; set; } = "installed";
}
