using System.Text;

namespace PowerForge;

/// <summary>Owns CLR instance storage and transactional lifetime around canonically emitted methods.</summary>
internal static class PowerShellRuntimeFreeModuleSourceGenerator
{
    internal static string FieldName(PowerShellSymbolId symbol)
        => PowerShellCSharpSymbolRenderer.Identifier("__field_" + symbol.Name);

    internal static int[] SupportedParameterCounts(IEnumerable<PowerShellCompilationParameter> parameters)
    {
        var values = parameters.ToArray();
        var minimum = values.Length;
        while (minimum > 0 && values[minimum - 1].HasDefaultValue && !values[minimum - 1].IsMandatory) minimum--;
        return Enumerable.Range(minimum, values.Length - minimum + 1).ToArray();
    }

    internal static string Generate(string namespaceName, string typeName, IEnumerable<string> methods,
        PowerShellRuntimeFreeModuleDefinition module, PowerShellLoweredFunction initializer)
    {
        var parameters = string.Join(", ", initializer.Parameters.Select(static parameter =>
            PowerShellCSharpSymbolRenderer.TypeName(parameter.ClrType) + " " +
            PowerShellCSharpSymbolRenderer.Identifier(parameter.Symbol.Name)));
        var arguments = string.Join(", ", initializer.Parameters.Select(static parameter =>
            PowerShellCSharpSymbolRenderer.Identifier(parameter.Symbol.Name)));
        var requiresBoundParameters = initializer.RequiresPowerShellBoundParameters || initializer.Parameters.Any(parameter =>
            PowerShellParameterValidationPolicy.RequiresBoundParameterSet(parameter.Contract, PowerShellCompilationCapabilities.TypedLibrary));
        var bindingName = "__moduleBindings";
        while (initializer.Parameters.Any(parameter => PowerShellClrSymbolMapper.MapIdentifier(parameter.Symbol.Name) == bindingName)) bindingName += "_";
        var previousName = "__previousModuleState";
        while (initializer.Parameters.Any(parameter => PowerShellClrSymbolMapper.MapIdentifier(parameter.Symbol.Name) == previousName)) previousName += "_";
        var coreParameters = parameters + (requiresBoundParameters ?
            (parameters.Length == 0 ? string.Empty : ", ") + "global::System.Collections.Generic.ISet<string> " + bindingName : string.Empty);
        var coreArguments = arguments + (requiresBoundParameters ? (arguments.Length == 0 ? string.Empty : ", ") + bindingName : string.Empty);
        string InvocationArguments(int count)
        {
            var values = initializer.Parameters.Select((parameter, index) => index < count
                ? PowerShellCSharpSymbolRenderer.Identifier(parameter.Symbol.Name)
                : "default(" + PowerShellCSharpSymbolRenderer.TypeName(parameter.ClrType) + ")!").ToList();
            if (requiresBoundParameters)
                values.Add("new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.OrdinalIgnoreCase) { " +
                    string.Join(", ", initializer.Parameters.Take(count).Select(static parameter => PowerShellCSharpLiteral.QuoteString(parameter.Symbol.Name))) + " }");
            return string.Join(", ", values);
        }
        var builder = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine("#nullable disable warnings")
            .Append("namespace ").Append(namespaceName).AppendLine(";")
            .AppendLine("/// <summary>Owns the compiled module state and its deterministic lifetime.</summary>")
            .Append("public sealed class ").Append(typeName).AppendLine(" : global::System.IDisposable")
            .AppendLine("{")
            .AppendLine("    private sealed class __ModuleState")
            .AppendLine("    {");
        foreach (var field in module.Fields)
            builder.Append("        public ").Append(PowerShellCSharpSymbolRenderer.TypeName(field.Type.ClrType))
                .Append(' ').Append(FieldName(field.Symbol)).AppendLine(" = default!;");
        builder.AppendLine("    }")
            .AppendLine("    private readonly object __moduleSync = new object();")
            .AppendLine("    private __ModuleState __moduleState = new __ModuleState();")
            .AppendLine("    private bool __moduleDisposed;")
            .AppendLine("    private int __moduleActiveCalls;");
        AppendLifecycleDocumentation(builder, "Creates and initializes a compiled module instance.", initializer.Parameters);
        builder.Append("    public ").Append(typeName).Append('(').Append(parameters).AppendLine(")")
            .AppendLine("    {")
            .Append("        this.").Append(initializer.GeneratedName).Append('(').Append(InvocationArguments(initializer.Parameters.Length)).AppendLine(");")
            .AppendLine("    }");
        AppendLifecycleDocumentation(builder, "Atomically resets this module instance to newly initialized state.", initializer.Parameters);
        builder.Append("    public void Reset(").Append(parameters).AppendLine(")")
            .Append("        => this.__ResetCore(").Append(InvocationArguments(initializer.Parameters.Length)).AppendLine(");")
            .Append("    private void __ResetCore(").Append(coreParameters).AppendLine(")")
            .AppendLine("    {")
            .AppendLine("        lock (this.__moduleSync)")
            .AppendLine("        {")
            .AppendLine("            this.__ThrowIfDisposed();")
            .AppendLine("            this.__ThrowIfActive();")
            .Append("            var ").Append(previousName).AppendLine(" = this.__moduleState;")
            .AppendLine("            this.__moduleState = new __ModuleState();")
            .AppendLine("            try")
            .AppendLine("            {")
            .Append("                this.").Append(initializer.GeneratedName).Append('(').Append(coreArguments).AppendLine(");")
            .AppendLine("            }")
            .AppendLine("            catch")
            .AppendLine("            {")
            .Append("                this.__moduleState = ").Append(previousName).AppendLine(";")
            .AppendLine("                throw;")
            .AppendLine("            }")
            .AppendLine("        }")
            .AppendLine("    }")
            .AppendLine("    /// <summary>Disposes this module instance, clears its state, and rejects later calls.</summary>")
            .AppendLine("    public void Dispose()")
            .AppendLine("    {")
            .AppendLine("        lock (this.__moduleSync)")
            .AppendLine("        {")
            .AppendLine("            this.__ThrowIfActive();")
            .AppendLine("            this.__moduleDisposed = true;")
            .AppendLine("            this.__moduleState = null!;")
            .AppendLine("        }")
            .AppendLine("    }")
            .AppendLine("    private void __ThrowIfDisposed()")
            .AppendLine("    {")
            .Append("        if (this.__moduleDisposed) throw new global::System.ObjectDisposedException(nameof(").Append(typeName).AppendLine("));")
            .AppendLine("    }")
            .AppendLine("    private void __ThrowIfActive()")
            .AppendLine("    {")
            .AppendLine("        if (this.__moduleActiveCalls != 0) throw new global::System.InvalidOperationException(\"Module lifetime cannot change from inside an active module call.\");")
            .AppendLine("    }");
        foreach (var count in SupportedParameterCounts(initializer.Parameters.Select(static parameter => parameter.Contract))
                     .Where(count => count < initializer.Parameters.Length))
        {
            var prefixParameters = string.Join(", ", initializer.Parameters.Take(count).Select(static parameter =>
                PowerShellCSharpSymbolRenderer.TypeName(parameter.ClrType) + " " + PowerShellCSharpSymbolRenderer.Identifier(parameter.Symbol.Name)));
            var prefix = initializer.Parameters.Take(count).ToArray();
            AppendLifecycleDocumentation(builder, "Creates and initializes a compiled module instance using authored defaults for omitted trailing parameters.", prefix);
            builder.Append("    public ").Append(typeName).Append('(').Append(prefixParameters).AppendLine(")")
                .Append("        => this.").Append(initializer.GeneratedName).Append('(').Append(InvocationArguments(count)).AppendLine(");")
                ;
            AppendLifecycleDocumentation(builder, "Atomically resets this module instance using authored defaults for omitted trailing parameters.", prefix);
            builder.Append("    public void Reset(").Append(prefixParameters).AppendLine(")")
                .Append("        => this.__ResetCore(").Append(InvocationArguments(count)).AppendLine(");");
        }
        builder.AppendLine(string.Join(Environment.NewLine + Environment.NewLine, methods))
            .AppendLine("}");
        return builder.ToString();
    }

    private static void AppendLifecycleDocumentation(
        StringBuilder builder,
        string summary,
        IEnumerable<PowerShellLoweredParameter> parameters)
    {
        builder.Append("    /// <summary>")
            .Append(System.Security.SecurityElement.Escape(summary))
            .AppendLine("</summary>");
        foreach (var parameter in parameters)
        {
            var name = PowerShellCSharpSymbolRenderer.Identifier(parameter.Symbol.Name);
            if (name.Length > 0 && name[0] == '@') name = name.Substring(1);
            builder.Append("    /// <param name=\"")
                .Append(name)
                .Append("\">Value supplied to the module initializer parameter ")
                .Append(System.Security.SecurityElement.Escape(parameter.Symbol.Name))
                .AppendLine(".</param>");
        }
    }
}
