namespace PowerForge;

/// <summary>Execution owner for an advanced-function lifecycle.</summary>
public enum PowerShellCompilationLifecycleExecution
{
    /// <summary>No advanced lifecycle is present.</summary>
    None,
    /// <summary>A generated cmdlet delegates lifecycle execution to a PowerShell steppable pipeline.</summary>
    HostedSteppablePipeline
}

/// <summary>Explicit begin/process/end/clean contract for a generated cmdlet.</summary>
public sealed class PowerShellCompilationLifecycleContract
{
    /// <summary>Lifecycle schema version.</summary>
    public int SchemaVersion { get; set; } = 1;
    /// <summary>Execution owner.</summary>
    public PowerShellCompilationLifecycleExecution Execution { get; set; }
    /// <summary>Whether an authored begin block exists.</summary>
    public bool HasBegin { get; set; }
    /// <summary>Whether an authored process block exists.</summary>
    public bool HasProcess { get; set; }
    /// <summary>Whether an authored end block exists.</summary>
    public bool HasEnd { get; set; }
    /// <summary>Whether an authored clean block exists.</summary>
    public bool HasClean { get; set; }
    /// <summary>Whether the cmdlet accepts pipeline input by value.</summary>
    public bool ValueFromPipeline { get; set; }
    /// <summary>Whether the cmdlet accepts pipeline input by property name.</summary>
    public bool ValueFromPipelineByPropertyName { get; set; }
    /// <summary>Whether one parameter consumes remaining arguments.</summary>
    public bool ValueFromRemainingArguments { get; set; }
    /// <summary>Whether common parameters are generated by CmdletBinding metadata.</summary>
    public bool CommonParameters { get; set; }
    /// <summary>Whether ShouldProcess is enabled.</summary>
    public bool SupportsShouldProcess { get; set; }
    /// <summary>Declared confirmation impact.</summary>
    public string ConfirmImpact { get; set; } = string.Empty;
    /// <summary>SHA-256 of the authored lifecycle function embedded in the generated cmdlet.</summary>
    public string SourceSha256 { get; set; } = string.Empty;
    /// <summary>Pipeline parameters used to reconstruct the current input record.</summary>
    public string[] PipelineParameterNames { get; set; } = Array.Empty<string>();
    /// <summary>Why this lifecycle is hosted rather than certified runtime-free.</summary>
    public string HostingReason { get; set; } = string.Empty;
}
