namespace PowerForge.Web;

/// <summary>
/// Options for company portal documentation index generation.
/// </summary>
public sealed class WebPortalDocsOptions
{
    /// <summary>Output directory for generated portal documentation JSON files.</summary>
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>Optional base directory for resolving relative paths.</summary>
    public string? BaseDirectory { get; set; }

    /// <summary>Path to the portal sources configuration file.</summary>
    public string? SourcesPath { get; set; }

    /// <summary>Optional private gallery feed JSON generated by private-gallery-index.</summary>
    public string? PrivateGalleryPath { get; set; }

    /// <summary>Whether fetched or local markdown content should be included in the generated index.</summary>
    public bool IncludeContent { get; set; } = true;

    /// <summary>Maximum content bytes stored for one document.</summary>
    public int MaxContentBytes { get; set; } = 262144;

    /// <summary>HTTP request timeout in seconds for repository-backed sources.</summary>
    public int RequestTimeoutSeconds { get; set; } = 30;

    /// <summary>Optional token used for repository-backed sources.</summary>
    public string? Token { get; set; }

    /// <summary>Optional environment variable name containing a repository token.</summary>
    public string? TokenEnvironmentVariable { get; set; }
}

/// <summary>
/// Result returned by portal documentation index generation.
/// </summary>
public sealed class WebPortalDocsResult
{
    /// <summary>Path to docs.json.</summary>
    public string DocsPath { get; set; } = string.Empty;

    /// <summary>Path to search.json.</summary>
    public string SearchPath { get; set; } = string.Empty;

    /// <summary>Number of source declarations processed.</summary>
    public int SourceCount { get; set; }

    /// <summary>Number of portal documents emitted.</summary>
    public int DocumentCount { get; set; }

    /// <summary>Warnings emitted during generation.</summary>
    public string[] Warnings { get; set; } = Array.Empty<string>();
}

/// <summary>
/// Normalized company portal documentation index.
/// </summary>
public sealed class WebPortalDocsDocument
{
    /// <summary>Schema version for the portal docs data contract.</summary>
    public int SchemaVersion { get; set; } = 1;

    /// <summary>Document format identifier.</summary>
    public string Format { get; set; } = "powerforge.portal.docs";

    /// <summary>Generation timestamp in UTC.</summary>
    public string GeneratedAtUtc { get; set; } = string.Empty;

    /// <summary>Aggregated summary.</summary>
    public WebPortalDocsSummary Summary { get; set; } = new();

    /// <summary>Processed source declarations.</summary>
    public List<WebPortalDocsSource> Sources { get; set; } = new();

    /// <summary>Normalized portal documents.</summary>
    public List<WebPortalDocEntry> Documents { get; set; } = new();

    /// <summary>Warnings emitted during generation.</summary>
    public List<string> Warnings { get; set; } = new();
}

/// <summary>
/// Aggregated portal documentation counts.
/// </summary>
public sealed class WebPortalDocsSummary
{
    /// <summary>Total source declarations processed.</summary>
    public int SourceCount { get; set; }

    /// <summary>Total documents emitted.</summary>
    public int DocumentCount { get; set; }

    /// <summary>Total local documents emitted.</summary>
    public int LocalDocumentCount { get; set; }

    /// <summary>Total package document assets emitted.</summary>
    public int PackageDocumentCount { get; set; }

    /// <summary>Total repository documents emitted.</summary>
    public int RepositoryDocumentCount { get; set; }
}

/// <summary>
/// Processed portal documentation source.
/// </summary>
public sealed class WebPortalDocsSource
{
    /// <summary>Source id from the source contract.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Source kind, such as local, package, github, or azure-devops.</summary>
    public string Kind { get; set; } = string.Empty;

    /// <summary>Display title.</summary>
    public string? Title { get; set; }

    /// <summary>Source description.</summary>
    public string? Description { get; set; }

    /// <summary>Related module name.</summary>
    public string? Module { get; set; }

    /// <summary>Repository URL when available.</summary>
    public string? RepositoryUrl { get; set; }

    /// <summary>Processing status.</summary>
    public string Status { get; set; } = "ok";

    /// <summary>Warnings emitted for this source.</summary>
    public List<string> Warnings { get; set; } = new();
}

/// <summary>
/// Normalized portal documentation entry.
/// </summary>
public sealed class WebPortalDocEntry
{
    /// <summary>Stable document id.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Document title.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Document kind, such as readme, docs, changelog, example, sop, or license.</summary>
    public string Kind { get; set; } = "docs";

    /// <summary>Source id that emitted this document.</summary>
    public string SourceId { get; set; } = string.Empty;

    /// <summary>Source kind that emitted this document.</summary>
    public string SourceKind { get; set; } = string.Empty;

    /// <summary>Relative path within the source.</summary>
    public string Path { get; set; } = string.Empty;

    /// <summary>Related module name.</summary>
    public string? Module { get; set; }

    /// <summary>Related package name.</summary>
    public string? Package { get; set; }

    /// <summary>Related package or module version.</summary>
    public string? Version { get; set; }

    /// <summary>Related command name.</summary>
    public string? Command { get; set; }

    /// <summary>Portal surface where this document should appear.</summary>
    public string? Surface { get; set; }

    /// <summary>Navigation group hint for themes.</summary>
    public string? NavigationGroup { get; set; }

    /// <summary>Short document summary.</summary>
    public string? Summary { get; set; }

    /// <summary>Document content when IncludeContent is enabled and content is available.</summary>
    public string? Content { get; set; }

    /// <summary>Source browser URL when available.</summary>
    public string? Url { get; set; }

    /// <summary>Raw content URL when available.</summary>
    public string? RawUrl { get; set; }

    /// <summary>Document tags and facets.</summary>
    public List<string> Tags { get; set; } = new();

    /// <summary>Ordering hint for themes.</summary>
    public int Order { get; set; }
}

/// <summary>
/// Search document generated from portal documentation data.
/// </summary>
public sealed class WebPortalDocsSearchDocument
{
    /// <summary>Schema version for the search data contract.</summary>
    public int SchemaVersion { get; set; } = 1;

    /// <summary>Document format identifier.</summary>
    public string Format { get; set; } = "powerforge.portal.docs.search";

    /// <summary>Generation timestamp in UTC.</summary>
    public string GeneratedAtUtc { get; set; } = string.Empty;

    /// <summary>Search entries.</summary>
    public List<WebPortalDocsSearchEntry> Entries { get; set; } = new();
}

/// <summary>
/// Portal documentation search entry.
/// </summary>
public sealed class WebPortalDocsSearchEntry
{
    /// <summary>Stable search entry id.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Entry kind.</summary>
    public string Kind { get; set; } = "document";

    /// <summary>Entry title.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Entry summary.</summary>
    public string? Summary { get; set; }

    /// <summary>Related module name.</summary>
    public string? Module { get; set; }

    /// <summary>Related package or module version.</summary>
    public string? Version { get; set; }

    /// <summary>Document URL when available.</summary>
    public string? Url { get; set; }

    /// <summary>Entry tags/facets.</summary>
    public List<string> Tags { get; set; } = new();
}
