using System.Text;
using static PowerForge.Web.Cli.WebCliHelpers;

namespace PowerForge.Web.Cli;

internal static partial class WebCliCommandHandlers
{
    internal static void WriteBootstrapPlanScript(
        string path,
        IReadOnlyList<PowerForgeServerBootstrapPlanStep> steps,
        PowerForgeServerRecoveryManifest? manifest = null)
        => File.WriteAllText(path, RenderBootstrapPlanScript(steps, manifest));

    internal static string RenderBootstrapPlanScript(
        IReadOnlyList<PowerForgeServerBootstrapPlanStep> steps,
        PowerForgeServerRecoveryManifest? manifest = null,
        bool operationLocksHeldByCaller = false)
    {
        var builder = new StringBuilder();
        builder.AppendLine("#!/usr/bin/env bash");
        builder.AppendLine("set -Eeuo pipefail");
        builder.AppendLine("umask 022");
        builder.AppendLine();
        builder.AppendLine("# Generated by powerforge-web server bootstrap-plan.");
        builder.AppendLine("# Review before running. Manual/TODO steps intentionally remain comments.");
        builder.AppendLine();

        var exitTrap = BuildBootstrapDisabledUnitExitTrap(manifest?.Systemd);
        var locks = manifest?.OperationLocks ?? Array.Empty<string>();
        if (operationLocksHeldByCaller && locks.Length == 0)
            throw new InvalidOperationException("Caller-held bootstrap locking requires declared operation locks.");
        var acquireIndex = -1;
        if (exitTrap.Length > 0 && locks.Length > 0)
        {
            EnsureDisabledUnitBootstrapLockOwnership(manifest!);
            if (!operationLocksHeldByCaller)
            {
                var acquire = BuildBootstrapOperationLockAcquireCommand(locks);
                for (var index = 0; index < steps.Count; index++)
                {
                    if (string.Equals(steps[index].Command, acquire, StringComparison.Ordinal))
                    {
                        acquireIndex = index;
                        break;
                    }
                }
                if (acquireIndex < 0)
                    throw new InvalidOperationException("Disabled-unit bootstrap is missing its declared operation-lock acquisition step.");
            }
        }

        // Lock setup uses its own EXIT trap; execute it before installing the
        // reconciliation trap. Acquire in the parent so the lock remains held
        // while the parent's final reconciliation handler runs.
        for (var index = 0; index <= acquireIndex; index++)
            AppendBootstrapPlanStep(builder, steps[index]);

        if (exitTrap.Length > 0)
        {
            builder.AppendLine(exitTrap);
            builder.AppendLine();
            // Individual steps may replace their own EXIT traps. Keep them in
            // a child shell, with the parent retaining the operation lock.
            builder.AppendLine("(");
        }

        for (var index = acquireIndex + 1; index < steps.Count; index++)
        {
            if (operationLocksHeldByCaller && steps[index].Category == "locking")
            {
                var isPreparation = locks.Any(path => string.Equals(steps[index].Command,
                    BuildOperationLockInstallCommand(path), StringComparison.Ordinal));
                var isAcquire = string.Equals(steps[index].Command,
                    BuildBootstrapOperationLockAcquireCommand(locks), StringComparison.Ordinal);
                if (isPreparation || isAcquire)
                    continue;
                throw new InvalidOperationException("Caller-held bootstrap locks cannot include a release or reacquisition step.");
            }
            AppendBootstrapPlanStep(builder, steps[index]);
        }

        if (exitTrap.Length > 0)
            builder.AppendLine(")");

        return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static void AppendBootstrapPlanStep(StringBuilder builder, PowerForgeServerBootstrapPlanStep step)
    {
        builder.AppendLine($"# {step.Order}. [{step.Category}] {step.Title}");
        if (string.IsNullOrWhiteSpace(step.Command))
        {
            builder.AppendLine();
            return;
        }

        if (step.Manual || step.Sensitive || step.Command.TrimStart().StartsWith("#", StringComparison.Ordinal))
        {
            foreach (var line in step.Command.Split(new[] { '\r', '\n' }, StringSplitOptions.None))
                builder.AppendLine("# " + line);
            if (step.Manual)
            {
                builder.AppendLine($"echo {ShellQuote($"Manual bootstrap step required: {step.Title}")} >&2");
                builder.AppendLine("exit 3");
            }
        }
        else
        {
            builder.AppendLine(step.Command);
            // Non-final &&/|| commands are exempt from errexit; check the whole step's status too.
            builder.AppendLine("powerforge_step_status=$?");
            builder.AppendLine("if [ \"$powerforge_step_status\" -ne 0 ]; then exit \"$powerforge_step_status\"; fi");
        }

        builder.AppendLine();
    }
}
