using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace PowerForge.Web.Cli;

internal static partial class WebPipelineRunner
{
    private static readonly UTF8Encoding ApacheUtf8NoBom = new(encoderShouldEmitUTF8Identifier: false);
    private static readonly Regex ApacheLegacyPostIdRegex = new(@"^\s*/\?p=(\d+)\s*$", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex ApacheLegacyPageIdRegex = new(@"^\s*/\?page_id=(\d+)\s*$", RegexOptions.IgnoreCase | RegexOptions.Compiled);

    private static void ExecuteApacheRedirects(JsonElement step, string baseDir, WebPipelineStepResult stepResult)
    {
        var siteRoot = ResolvePath(baseDir, GetString(step, "siteRoot") ?? GetString(step, "site-root")) ?? baseDir;
        var strict = GetBool(step, "strict") ?? false;
        var includeHeader = GetBool(step, "includeHeader") ?? GetBool(step, "include-header") ?? true;
        var summaryPath = ResolvePath(baseDir, GetString(step, "summaryPath") ?? GetString(step, "summary-path"));
        var languageHostMap = GetApacheLanguageHostMap(step);
        var stripLanguagePrefixes = new HashSet<string>(languageHostMap.Keys, StringComparer.OrdinalIgnoreCase);

        var configuredSources = GetArrayOfStrings(step, "sources")
                                ?? GetArrayOfStrings(step, "sourcePaths")
                                ?? GetArrayOfStrings(step, "source-paths")
                                ?? GetArrayOfStrings(step, "redirectCsvPaths")
                                ?? GetArrayOfStrings(step, "redirect-csv-paths");
        if (configuredSources is null || configuredSources.Length == 0)
        {
            var singleSource = GetString(step, "source")
                               ?? GetString(step, "input")
                               ?? GetString(step, "path");
            if (!string.IsNullOrWhiteSpace(singleSource))
                configuredSources = new[] { singleSource };
        }

        var sourcePaths = (configuredSources is { Length: > 0 }
                ? configuredSources
                    .Where(static value => !string.IsNullOrWhiteSpace(value))
                    .Select(value => ResolvePath(baseDir, value) ?? value)
                    .ToList()
                : new List<string>
                {
                    Path.GetFullPath(Path.Combine(siteRoot, "data", "redirects", "legacy-wordpress-map.csv")),
                    Path.GetFullPath(Path.Combine(siteRoot, "data", "redirects", "legacy-wordpress-generated.csv"))
                })
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .Select(Path.GetFullPath)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var outputPath = ResolvePath(baseDir,
            GetString(step, "out") ??
            GetString(step, "output") ??
            GetString(step, "outputPath") ??
            GetString(step, "output-path") ??
            GetString(step, "destination") ??
            GetString(step, "dest"))
            ?? Path.GetFullPath(Path.Combine(siteRoot, "deploy", "apache", "wordpress-redirects.conf"));

        var usedSources = new List<string>();
        var missingSources = new List<string>();
        var rows = new List<ApacheRedirectRow>();
        foreach (var sourcePath in sourcePaths)
        {
            var resolvedSource = Path.GetFullPath(sourcePath);
            if (!File.Exists(resolvedSource))
            {
                missingSources.Add(resolvedSource);
                continue;
            }

            usedSources.Add(resolvedSource);
            rows.AddRange(ReadApacheRedirectRows(resolvedSource));
        }

        if (strict && usedSources.Count == 0)
            throw new InvalidOperationException("apache-redirects strict mode failed: no source CSV files were found.");

        var uniqueRows = rows
            .Where(static row => !string.IsNullOrWhiteSpace(row.LegacyUrl) && !string.IsNullOrWhiteSpace(row.TargetUrl))
            .Select(row => NormalizeApacheRedirectRow(row, languageHostMap, stripLanguagePrefixes))
            .GroupBy(static row => $"{row.LegacyUrl}|{row.TargetUrl}|{row.Status}", StringComparer.OrdinalIgnoreCase)
            .Select(static group => group.First())
            .OrderBy(static row => row.LegacyUrl, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static row => row.TargetUrl, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static row => row.Status)
            .ToList();

        var lines = new List<string>();
        if (includeHeader)
        {
            lines.Add("# Auto-generated by PowerForge.Web.Cli task: apache-redirects");
            lines.Add("# Include this file from your Apache vhost or .htaccess.");
            lines.Add("# Query-specific legacy rows are matched exactly and then redirected with QSD so stale WordPress query strings do not leak to canonical routes.");
        }
        lines.Add("RewriteEngine On");
        lines.Add(string.Empty);

        foreach (var row in uniqueRows)
        {
            var source = ParseApacheLegacySource(row.LegacyUrl);
            var hostCondition = source.HostPattern;
            var postMatch = ApacheLegacyPostIdRegex.Match(source.PathAndQuery);
            if (postMatch.Success)
            {
                var id = postMatch.Groups[1].Value;
                if (!string.IsNullOrWhiteSpace(hostCondition))
                    lines.Add($"RewriteCond %{{HTTP_HOST}} {hostCondition} [NC]");
                lines.Add($"RewriteCond %{{QUERY_STRING}} (^|&)p={id}(&|$)");
                lines.Add($"RewriteRule ^/?$ {row.TargetUrl} [R={row.Status},L,QSD]");
                lines.Add(string.Empty);
                continue;
            }

            var pageMatch = ApacheLegacyPageIdRegex.Match(source.PathAndQuery);
            if (pageMatch.Success)
            {
                var id = pageMatch.Groups[1].Value;
                if (!string.IsNullOrWhiteSpace(hostCondition))
                    lines.Add($"RewriteCond %{{HTTP_HOST}} {hostCondition} [NC]");
                lines.Add($"RewriteCond %{{QUERY_STRING}} (^|&)page_id={id}(&|$)");
                lines.Add($"RewriteRule ^/?$ {row.TargetUrl} [R={row.Status},L,QSD]");
                lines.Add(string.Empty);
                continue;
            }

            var path = source.RewriteRulePath.Trim();
            if (string.IsNullOrWhiteSpace(path))
                continue;
            if (!path.StartsWith("/", StringComparison.Ordinal))
                path = "/" + path;

            if (path.Equals("/", StringComparison.Ordinal))
            {
                if (!string.IsNullOrWhiteSpace(hostCondition))
                    lines.Add($"RewriteCond %{{HTTP_HOST}} {hostCondition} [NC]");
                AppendApacheLegacyQueryCondition(lines, source.SourceQuery);
                lines.Add($"RewriteRule ^/?$ {row.TargetUrl} [R={row.Status},L{(string.IsNullOrWhiteSpace(source.SourceQuery) ? string.Empty : ",QSD")}]");
                lines.Add(string.Empty);
                continue;
            }

            var escapedPath = Regex.Escape(path.TrimStart('/'));
            if (!string.IsNullOrWhiteSpace(hostCondition))
                lines.Add($"RewriteCond %{{HTTP_HOST}} {hostCondition} [NC]");
            AppendApacheLegacyQueryCondition(lines, source.SourceQuery);
            lines.Add($"RewriteRule ^{escapedPath}/?$ {row.TargetUrl} [R={row.Status},L{(string.IsNullOrWhiteSpace(source.SourceQuery) ? string.Empty : ",QSD")}]");
            lines.Add(string.Empty);
        }

        var outputDirectory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(outputDirectory))
            Directory.CreateDirectory(outputDirectory);
        File.WriteAllText(outputPath, string.Join(Environment.NewLine, lines), ApacheUtf8NoBom);

        if (!string.IsNullOrWhiteSpace(summaryPath))
        {
            var summaryDirectory = Path.GetDirectoryName(summaryPath);
            if (!string.IsNullOrWhiteSpace(summaryDirectory))
                Directory.CreateDirectory(summaryDirectory);

            var summary = new
            {
                generatedOn = DateTimeOffset.UtcNow.ToString("O"),
                outputPath = Path.GetFullPath(outputPath),
                rules = uniqueRows.Count,
                sourceCount = sourcePaths.Count,
                usedSourceCount = usedSources.Count,
                usedSources = usedSources.ToArray(),
                missingSourceCount = missingSources.Count,
                missingSources = missingSources.ToArray(),
                strict
            };
            File.WriteAllText(summaryPath, JsonSerializer.Serialize(summary, new JsonSerializerOptions { WriteIndented = true }));
        }

        stepResult.Success = true;
        stepResult.Message = $"apache-redirects ok: rules={uniqueRows.Count}; sources={usedSources.Count}/{sourcePaths.Count}";
    }

    private static List<ApacheRedirectRow> ReadApacheRedirectRows(string csvPath)
    {
        var rows = new List<ApacheRedirectRow>();
        var lines = File.ReadAllLines(csvPath);
        if (lines.Length <= 1)
            return rows;

        var header = SplitApacheCsvLine(lines[0]);
        var legacyIndex = Array.FindIndex(header, static h => h.Equals("legacy_url", StringComparison.OrdinalIgnoreCase));
        var targetIndex = Array.FindIndex(header, static h => h.Equals("target_url", StringComparison.OrdinalIgnoreCase));
        var statusIndex = Array.FindIndex(header, static h => h.Equals("status", StringComparison.OrdinalIgnoreCase));
        var languageIndex = Array.FindIndex(header, static h => h.Equals("language", StringComparison.OrdinalIgnoreCase));

        if (legacyIndex < 0 || targetIndex < 0)
            return rows;

        for (var i = 1; i < lines.Length; i++)
        {
            if (string.IsNullOrWhiteSpace(lines[i]))
                continue;

            var parts = SplitApacheCsvLine(lines[i]);
            if (parts.Length <= legacyIndex || parts.Length <= targetIndex)
                continue;

            var legacy = parts[legacyIndex].Trim();
            var target = parts[targetIndex].Trim();
            if (string.IsNullOrWhiteSpace(legacy) || string.IsNullOrWhiteSpace(target))
                continue;

            var status = 301;
            if (statusIndex >= 0 && statusIndex < parts.Length && int.TryParse(parts[statusIndex], out var parsedStatus) && parsedStatus > 0)
                status = parsedStatus;

            rows.Add(new ApacheRedirectRow
            {
                LegacyUrl = legacy,
                TargetUrl = target,
                Status = status,
                Language = languageIndex >= 0 && languageIndex < parts.Length ? parts[languageIndex].Trim() : string.Empty
            });
        }

        return rows;
    }

    private static Dictionary<string, string> GetApacheLanguageHostMap(JsonElement step)
    {
        if (!TryGetObject(step, "languageHostMap", out var mapElement) &&
            !TryGetObject(step, "language-host-map", out mapElement))
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var property in mapElement.EnumerateObject())
        {
            if (property.Value.ValueKind != JsonValueKind.String)
                continue;

            var language = property.Name?.Trim();
            var host = property.Value.GetString()?.Trim();
            if (string.IsNullOrWhiteSpace(language) || string.IsNullOrWhiteSpace(host))
                continue;

            map[language] = host;
        }

        return map;
    }

    private static ApacheRedirectRow NormalizeApacheRedirectRow(
        ApacheRedirectRow row,
        IReadOnlyDictionary<string, string> languageHostMap,
        ISet<string> stripLanguagePrefixes)
    {
        var legacy = row.LegacyUrl.Trim();
        var target = row.TargetUrl.Trim();
        var language = row.Language?.Trim() ?? string.Empty;

        if (!string.IsNullOrWhiteSpace(language))
        {
            if (!Uri.TryCreate(legacy, UriKind.Absolute, out _) &&
                languageHostMap.TryGetValue(language, out var host) &&
                !string.IsNullOrWhiteSpace(host) &&
                TryNormalizeRelativeApacheLegacyPath(legacy, out var relativeLegacy))
            {
                legacy = $"https://{host}{relativeLegacy}";
            }

            if (stripLanguagePrefixes.Contains(language))
                target = StripLeadingLanguagePrefix(target, language);
        }

        return new ApacheRedirectRow
        {
            LegacyUrl = legacy,
            TargetUrl = target,
            Status = row.Status > 0 ? row.Status : 301,
            Language = language
        };
    }

    private static string StripLeadingLanguagePrefix(string targetUrl, string language)
    {
        if (string.IsNullOrWhiteSpace(targetUrl) || string.IsNullOrWhiteSpace(language))
            return targetUrl;

        var prefix = "/" + language;
        if (targetUrl.Equals(prefix, StringComparison.OrdinalIgnoreCase) ||
            targetUrl.Equals(prefix + "/", StringComparison.OrdinalIgnoreCase))
            return "/";

        if (targetUrl.StartsWith(prefix + "/", StringComparison.OrdinalIgnoreCase))
        {
            var stripped = targetUrl.Substring(prefix.Length);
            return string.IsNullOrWhiteSpace(stripped) ? "/" : stripped;
        }

        return targetUrl;
    }

    private static bool TryNormalizeRelativeApacheLegacyPath(string legacy, out string relativePath)
    {
        relativePath = string.Empty;
        var trimmed = legacy.Trim();
        // Keep this conservative: CSV values are expected to be decoded route paths before Apache export.
        if (string.IsNullOrWhiteSpace(trimmed) ||
            trimmed.StartsWith("//", StringComparison.Ordinal) ||
            trimmed.Contains('\\', StringComparison.Ordinal) ||
            trimmed.Contains("..", StringComparison.Ordinal))
        {
            return false;
        }

        relativePath = trimmed.StartsWith("/", StringComparison.Ordinal) ? trimmed : "/" + trimmed.TrimStart('/');
        return Uri.TryCreate(relativePath, UriKind.Relative, out _);
    }

    private static void AppendApacheLegacyQueryCondition(List<string> lines, string sourceQuery)
    {
        if (!string.IsNullOrWhiteSpace(sourceQuery))
            lines.Add($"RewriteCond %{{QUERY_STRING}} ^{Regex.Escape(sourceQuery)}$");
    }

    private static string[] SplitApacheCsvLine(string line)
    {
        if (string.IsNullOrWhiteSpace(line))
            return Array.Empty<string>();

        var values = new List<string>();
        var sb = new StringBuilder();
        var inQuotes = false;
        for (var i = 0; i < line.Length; i++)
        {
            var c = line[i];
            if (c == '"' && (i + 1 >= line.Length || line[i + 1] != '"'))
            {
                inQuotes = !inQuotes;
                continue;
            }

            if (c == '"' && i + 1 < line.Length && line[i + 1] == '"')
            {
                sb.Append('"');
                i++;
                continue;
            }

            if (c == ',' && !inQuotes)
            {
                values.Add(sb.ToString().Trim());
                sb.Clear();
                continue;
            }

            sb.Append(c);
        }

        values.Add(sb.ToString().Trim());
        return values.ToArray();
    }

    private static ApacheLegacySource ParseApacheLegacySource(string value)
    {
        var trimmed = value?.Trim() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(trimmed))
            return new ApacheLegacySource();

        if (!Uri.TryCreate(trimmed, UriKind.Absolute, out var uri) ||
            (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps))
        {
            return new ApacheLegacySource
            {
                PathAndQuery = trimmed,
                RewriteRulePath = trimmed
            };
        }

        var path = string.IsNullOrWhiteSpace(uri.AbsolutePath) ? "/" : uri.AbsolutePath;
        if (path.Length > 1 && path.EndsWith("/", StringComparison.Ordinal))
            path = path.TrimEnd('/');

        var query = uri.Query ?? string.Empty;
        var pathAndQuery = path + query;
        var hostPattern = $"^(.+\\.)?{Regex.Escape(uri.Host)}$";

        return new ApacheLegacySource
        {
            PathAndQuery = pathAndQuery,
            RewriteRulePath = path,
            SourceQuery = query.TrimStart('?'),
            HostPattern = hostPattern
        };
    }

    private sealed class ApacheRedirectRow
    {
        public string LegacyUrl { get; set; } = string.Empty;
        public string TargetUrl { get; set; } = string.Empty;
        public int Status { get; set; }
        public string Language { get; set; } = string.Empty;
    }

    private sealed class ApacheLegacySource
    {
        public string PathAndQuery { get; set; } = string.Empty;
        // RewriteRule cannot match the query string; SourceQuery is emitted as a RewriteCond.
        public string RewriteRulePath { get; set; } = string.Empty;
        public string SourceQuery { get; set; } = string.Empty;
        public string HostPattern { get; set; } = string.Empty;
    }
}
