using System.IO;
using System.Linq;

namespace PowerForge;

public sealed partial class ModulePipelineRunner
{
    internal string? SyncBuildManifestToProjectRoot(
        ModulePipelinePlan plan,
        ModuleBuildResult? buildResult = null)
    {
        var projectManifestPath = GetProjectManifestPath(plan);
        if (!File.Exists(projectManifestPath))
            return null;

        RefreshProjectManifestFromPlan(plan, projectManifestPath);
        var syncedBinaryExports = buildResult is not null &&
                                  !plan.BuildSpec.RefreshManifestOnly &&
                                  SyncBinaryExportsToProjectRoot(plan, buildResult, projectManifestPath);

        var label = plan.BuildSpec.RefreshManifestOnly ? "RefreshPSD1Only" : "Build";
        var message = syncedBinaryExports
            ? $"{label}: refreshed project-root manifest and bootstrapper from staged binary exports."
            : $"{label}: refreshed project-root manifest from source manifest inputs.";
        _logger.Info(message);
        return message;
    }

    internal void SyncRefreshManifestToProjectRoot(
        ModulePipelinePlan plan)
    {
        if (!plan.BuildSpec.RefreshManifestOnly)
            return;

        _ = SyncBuildManifestToProjectRoot(plan);
    }

    internal void SyncPublishedManifestToProjectRoot(
        ModulePipelinePlan plan,
        IReadOnlyList<ModulePublishResult>? publishResults)
    {
        if (publishResults is null || publishResults.Count == 0)
            return;

        if (publishResults.Any(r => r is null || !r.Succeeded))
            return;

        var projectManifestPath = GetProjectManifestPath(plan);
        if (!File.Exists(projectManifestPath))
            return;

        RefreshProjectManifestFromPlan(plan, projectManifestPath);
        _logger.Info("Publish: refreshed project-root manifest from source manifest inputs.");
    }

    private static string GetProjectManifestPath(ModulePipelinePlan plan)
    {
        var projectRoot = Path.GetFullPath(plan.ProjectRoot)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        return Path.Combine(projectRoot, $"{plan.ModuleName}.psd1");
    }

    private bool SyncBinaryExportsToProjectRoot(
        ModulePipelinePlan plan,
        ModuleBuildResult buildResult,
        string projectManifestPath)
    {
        if (plan is null) throw new ArgumentNullException(nameof(plan));
        if (buildResult is null) throw new ArgumentNullException(nameof(buildResult));
        if (string.IsNullOrWhiteSpace(buildResult.ManifestPath) || !File.Exists(buildResult.ManifestPath))
            return false;

        var exports = ModuleManifestExportReader.ReadExports(buildResult.ManifestPath);
        _manifestMutator.TrySetManifestExports(projectManifestPath, exports.Functions, exports.Cmdlets, exports.Aliases);

        var sourcePsm1Path = Path.Combine(plan.BuildSpec.SourcePath, plan.ModuleName + ".psm1");
        var stagingPsm1Path = Path.Combine(buildResult.StagingPath, plan.ModuleName + ".psm1");
        if (File.Exists(stagingPsm1Path) && SourceCanUseGeneratedBuildBootstrapper(plan, sourcePsm1Path))
        {
            File.Copy(stagingPsm1Path, sourcePsm1Path, overwrite: true);
        }

        return true;
    }

    private static bool SourceCanUseGeneratedBuildBootstrapper(
        ModulePipelinePlan plan,
        string sourcePsm1Path)
    {
        var sourceHasCustomIncludeScripts = HasCustomIncludeScriptFiles(plan.BuildSpec.SourcePath, plan.Information);
        if (sourceHasCustomIncludeScripts)
            return false;

        var sourceIsSingleFileModule = IsSourceSingleFileModule(plan);
        return !sourceIsSingleFileModule || IsGeneratedSourceBootstrapper(sourcePsm1Path, plan.ModuleName);
    }

    private static bool IsGeneratedSourceBootstrapper(string sourcePsm1Path, string moduleName)
    {
        if (!File.Exists(sourcePsm1Path))
            return false;

        var content = File.ReadAllText(sourcePsm1Path);
        return IsGeneratedSourceDevelopmentBootstrapperContent(content, moduleName) ||
               IsGeneratedSourceBuildBootstrapperContent(content, moduleName);
    }

    private static bool IsGeneratedSourceBuildBootstrapperContent(string content, string moduleName)
        => content.Contains("# Auto-generated by PowerForge. Do not edit.", StringComparison.Ordinal) &&
           content.Contains("# " + moduleName + " bootstrapper", StringComparison.Ordinal);
}
