# {{ModuleName}} bootstrapper
# Auto-generated by PowerForge. Do not edit.

# PowerForge script preamble begin
{{ScriptPreambleBlock}}
# PowerForge script preamble end

{{ModuleRootCaptureBlock}}
{{BinaryLoaderBlock}}
# PowerForge script payload begin
{{ScriptLoaderBlock}}
# PowerForge script payload end
{{ExportBlock}}
