# {{ModuleName}} bootstrapper
# Auto-generated by PowerForge. Do not edit.

{{BinaryLoaderBlock}}
{{ScriptLoaderBlock}}
$FunctionsToExport = {{FunctionsToExport}}
$CmdletsToExport = {{CmdletsToExport}}
$AliasesToExport = {{AliasesToExport}}
Export-ModuleMember -Function $FunctionsToExport -Alias $AliasesToExport -Cmdlet $CmdletsToExport
