# {{ModuleName}}.Libraries.ps1
# Auto-generated by PowerForge. Do not edit.

{{LibrariesByFolderMap}}

$LibRoot = [IO.Path]::Combine($PSScriptRoot, 'Lib')
$AssemblyFolders = Get-ChildItem -LiteralPath $LibRoot -Directory -ErrorAction SilentlyContinue
$Root = @(Get-ChildItem -LiteralPath $LibRoot -File -ErrorAction SilentlyContinue | Where-Object Extension -IEQ '.dll').Count -gt 0

$Default = $false
$Core = $false
$Standard = $false
foreach ($A in $AssemblyFolders.Name) {
    if ($A -eq 'Default') {
        $Default = $true
    } elseif ($A -eq 'Core') {
        $Core = $true
    } elseif ($A -eq 'Standard') {
        $Standard = $true
    }
}
if ($Standard -and $Core -and $Default) {
    $FrameworkNet = 'Default'
    $Framework = 'Standard'
} elseif ($Standard -and $Core) {
    $Framework = 'Standard'
    $FrameworkNet = 'Standard'
} elseif ($Core -and $Default) {
    $Framework = 'Core'
    $FrameworkNet = 'Default'
} elseif ($Standard -and $Default) {
    $Framework = 'Standard'
    $FrameworkNet = 'Default'
} elseif ($Standard) {
    $Framework = 'Standard'
    $FrameworkNet = 'Standard'
} elseif ($Core) {
    $Framework = 'Core'
    $FrameworkNet = ''
} elseif ($Default) {
    $Framework = ''
    $FrameworkNet = 'Default'
} elseif ($Root) {
    $Framework = ''
    $FrameworkNet = ''
} else {
    #Write-Error -Message 'No assemblies found'
}

{{RuntimePayloadSelectorBlock}}
if ($PSEdition -eq 'Core') {
    $LibFolder = $Framework
} else {
    $LibFolder = $FrameworkNet
}

$LibraryFoldersToLoad = @($LibFolder)
if ($null -ne $ResolvePowerForgeModuleAssembly) {
    $PowerForgeLibrariesRoot = [IO.Path]::GetFullPath($LibRoot)
    $PowerForgeLibrariesRootPrefix = $PowerForgeLibrariesRoot
    if (-not $PowerForgeLibrariesRootPrefix.EndsWith([IO.Path]::DirectorySeparatorChar.ToString(), [StringComparison]::Ordinal)) {
        $PowerForgeLibrariesRootPrefix += [IO.Path]::DirectorySeparatorChar
    }
    foreach ($PowerForgeLibraryFileName in $LibraryFileNames) {
        try {
            $PowerForgeResolvedLibrary = & $ResolvePowerForgeModuleAssembly -LibraryFileName $PowerForgeLibraryFileName
        } catch {
            Write-Verbose "Skipping preload-folder discovery for '$PowerForgeLibraryFileName'. $($_.Exception.Message)"
            continue
        }
        $PowerForgeResolvedLibraryDirectory = [IO.Path]::GetFullPath($PowerForgeResolvedLibrary.Directory)
        $PowerForgeResolvedLibraryFolder = if ($PowerForgeResolvedLibraryDirectory -ieq $PowerForgeLibrariesRoot) {
            ''
        } elseif ($PowerForgeResolvedLibraryDirectory.StartsWith($PowerForgeLibrariesRootPrefix, [StringComparison]::OrdinalIgnoreCase)) {
            $PowerForgeResolvedLibraryDirectory.Substring($PowerForgeLibrariesRootPrefix.Length).Replace('\\', '/').Trim('/')
        }
        if ($null -ne $PowerForgeResolvedLibraryFolder -and
            $LibrariesByFolder.ContainsKey($PowerForgeResolvedLibraryFolder) -and
            $PowerForgeResolvedLibraryFolder -notin $LibraryFoldersToLoad) {
            $LibraryFoldersToLoad += $PowerForgeResolvedLibraryFolder
        }
    }
}

$LibrariesToLoad = @(
    foreach ($LibraryFolderToLoad in $LibraryFoldersToLoad) {
        if ($LibrariesByFolder.ContainsKey($LibraryFolderToLoad)) {
            $LibrariesByFolder[$LibraryFolderToLoad]
        }
    }
) | Select-Object -Unique
foreach ($L in $LibrariesToLoad) {
    try {
        $LibraryPathParts = @($PSScriptRoot) + @($L -split '[\\/]' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
        $LibraryPath = [IO.Path]::Combine([string[]] $LibraryPathParts)
        Add-Type -Path $LibraryPath -ErrorAction Stop
    } catch {
        if ($_.Exception.Message -like '*Assembly with same name is already loaded*') {
            Write-Warning -Message "Assembly with same name is already loaded. Ignoring '$L'."
        } else {
            throw $_
        }
    }
}
