using System.Text;

namespace PowerForge;

/// <summary>
/// Generates a runtime-independent console entry point for an eligible top-level PowerShell script.
/// </summary>
internal static class PowerShellTypedExecutableEmitter
{
    private const string ProgramTemplate = "PowerForge.PowerShell.Compilation.TypedExecutableProgram.cs.template";

    internal static PowerShellTypedExecutableEmission Emit(
        string sourcePath,
        IEnumerable<string> sourcePaths,
        PowerShellCompilationPlan plan,
        string targetFramework,
        string semanticProfileId = PowerShellCompilationSemanticOracleCatalog.PowerShell76ProfileId,
        IEnumerable<PowerShellCompilationCommandProviderContract>? commandProviders = null)
    {
        var compilation = PowerShellTypedExecutableCompiler.Compile(
            sourcePath,
            sourcePaths,
            plan,
            targetFramework,
            semanticProfileId,
            commandProviders);
        var contract = compilation.EntryPoint;
        var method = compilation.EntryPointMethod;
        PowerShellTypedExecutableOutputPolicy.EnsureSupported(method.ReturnType);
        var compiledSource = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("namespace PowerForge.Compiled;")
            .AppendLine()
            .AppendLine("public static class CompiledPowerShellScript")
            .AppendLine("{")
            .AppendLine(string.Join(Environment.NewLine, compilation.LocalMethods.Select(static local => local.Source)))
            .AppendLine(method.Source)
            .AppendLine("}")
            .ToString();

        var parameters = contract.Parameters;
        foreach (var parameter in parameters)
            PowerShellTypedExecutableParameterPolicy.EnsureSupported(parameter.Contract.Name, parameter.ClrType);
        var commandBinding = contract.Method.CommandBinding;
        PowerShellTypedExecutableParameterPolicy.EnsureBindingSupported(parameters, commandBinding);
        var hasExplicitPositions = parameters.Select(static parameter => parameter.Contract)
            .SelectMany(static parameter => parameter.Bindings)
            .Any(static binding => binding.Position.HasValue);
        var parameterSpecs = string.Join(Environment.NewLine, parameters.Select((parameter, index) =>
        {
            var metadata = parameter.Contract;
            var compiledType = parameter.ClrType;
            var acceptsRemainingArguments = metadata.Bindings.Any(static binding => binding.ValueFromRemainingArguments);
            var position = metadata.Bindings.Select(static binding => binding.Position).FirstOrDefault(static value => value.HasValue);
            if (!position.HasValue)
            {
                if (acceptsRemainingArguments)
                    position = hasExplicitPositions || !commandBinding.PositionalBinding ? int.MaxValue : index;
                else if (commandBinding.PositionalBinding && !hasExplicitPositions)
                    position = index;
            }
            return "        new ParameterSpec(" + PowerShellCSharpLiteral.QuoteString(metadata.Name) + ", " +
                   (compiledType.IsArray ? "true" : "false") + ", " +
                   (compiledType == typeof(string) ? "true" : "false") + ", " +
                   GenerateDefaultFactory(compiledType) + ", " +
                   GenerateValueParser(compiledType) + ", " +
                   (metadata.IsMandatory ? "true" : "false") + ", " +
                   (metadata.IsSwitch ? "true" : "false") + ", " +
                   (position.HasValue ? position.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : "null") + ", " +
                   (acceptsRemainingArguments ? "true" : "false") + ", " +
                   GenerateStringArray(metadata.Aliases) + ", " +
                   (metadata.AllowNull ? "true" : "false") + ", " +
                   (metadata.AllowEmptyString ? "true" : "false") + ", " +
                   (metadata.AllowEmptyCollection ? "true" : "false") + ", " +
                   GenerateValidations(metadata.Validations) + "),";
        }));
        var arguments = parameters.Select(parameter =>
            "(" + PowerShellCSharpSymbolRenderer.TypeName(parameter.ClrType) + ")values[" +
            PowerShellCSharpLiteral.QuoteString(parameter.Contract.Name) + "]").ToList();
        if (method.RequiresPowerShellStreams)
        {
            arguments.AddRange(new[]
            {
                "WritePowerShellOutput",
                "WritePowerShellVerbose",
                "WritePowerShellDebug",
                "WritePowerShellWarning",
                "WritePowerShellInformation",
                "WritePowerShellHost",
                "WritePowerShellError"
            });
        }
        if (method.RequiresProviderCancellation)
            arguments.Add("providerCancellation.Token");
        if (method.RequiresPowerShellBoundParameters)
            arguments.Add("boundParameters");
        var invocation = "CompiledPowerShellScript." + method.GeneratedName + "(" + string.Join(", ", arguments) + ")";
        var resultCardinality = method.OutputCardinality.Equals("Collection", StringComparison.Ordinal)
            ? "ResultCardinality.Collection"
            : "ResultCardinality.Scalar";
        var invocationSource = method.RequiresPowerShellStreams
            ? GenerateStreamInvocation(method, invocation, resultCardinality)
            : method.ReturnType == typeof(void)
            ? "            " + invocation + ";" + Environment.NewLine +
              "            WriteNoResult();" + Environment.NewLine + "            return 0;"
            : "            var result = " + invocation + ";" + Environment.NewLine +
              "            WriteResult(result, " + resultCardinality + ");" + Environment.NewLine + "            return 0;";
        var commonParameterNames = string.Join(Environment.NewLine,
            PowerShellCommonParameterPolicy.GetAvailable(commandBinding, targetFramework).Select(parameter =>
                "        new string[] { " + PowerShellCSharpLiteral.QuoteString(parameter.Name) + ", " +
                PowerShellCSharpLiteral.QuoteString(parameter.Alias) + " },"));
        var programSource = ReadTemplate(ProgramTemplate)
            .Replace("{{PARAMETER_SPECS}}", parameterSpecs)
            .Replace("{{COMMON_PARAMETER_NAMES}}", commonParameterNames)
            .Replace("{{ACCEPTS_SURPLUS_POSITIONAL_ARGUMENTS}}", commandBinding.IsAdvancedFunction ? "false" : "true")
            .Replace("{{INVOCATION}}", invocationSource);
        return new PowerShellTypedExecutableEmission(compiledSource, programSource, compilation.Methods, compilation.Optimization, compilation.IrSnapshots);
    }

    private static string GenerateStreamInvocation(
        PowerShellCSharpMethodEmission method,
        string invocation,
        string resultCardinality)
    {
        var builder = new StringBuilder();
        if (method.RequiresProviderCancellation)
        {
            builder.AppendLine("            using var providerCancellation = new global::System.Threading.CancellationTokenSource();")
                .AppendLine("            global::System.ConsoleCancelEventHandler cancellationHandler = (_, eventArgs) =>")
                .AppendLine("            {")
                .AppendLine("                eventArgs.Cancel = true;")
                .AppendLine("                providerCancellation.Cancel();")
                .AppendLine("            };")
                .AppendLine("            global::System.Console.CancelKeyPress += cancellationHandler;");
        }
        builder.AppendLine("            BeginPowerShellStreams();")
            .AppendLine("            try")
            .AppendLine("            {");
        if (method.ReturnType == typeof(void))
            builder.Append("                ").Append(invocation).AppendLine(";");
        else
            builder.Append("                var result = ").Append(invocation).AppendLine(";")
                .Append("                WritePowerShellResult(result, ").Append(resultCardinality).AppendLine(");");
        builder.AppendLine("                EndPowerShellStreams();")
            .AppendLine("                return 0;")
            .AppendLine("            }")
            .AppendLine("            finally")
            .AppendLine("            {");
        if (method.RequiresProviderCancellation)
            builder.AppendLine("                global::System.Console.CancelKeyPress -= cancellationHandler;");
        builder.Append("            }");
        return builder.ToString();
    }

    private static string GenerateStringArray(IEnumerable<string> values)
        => "new string[] { " + string.Join(", ", values.Select(PowerShellCSharpLiteral.QuoteString)) + " }";

    private static string GenerateValidations(IEnumerable<PowerShellCompilationValidation> validations)
        => "new ValidationSpec[] { " + string.Join(", ", validations.Select(validation =>
            "new ValidationSpec(ValidationKind." + validation.Kind + ", " + GenerateStringArray(validation.Arguments) + ")")) + " }";

    private static string GenerateDefaultFactory(Type type)
        => type.IsValueType
            ? "static () => default(" + PowerShellCSharpSymbolRenderer.TypeName(type) + ")"
            : "static () => null!";

    private static string GenerateValueParser(Type type)
    {
        var isArray = type.IsArray;
        var scalar = Nullable.GetUnderlyingType(isArray ? type.GetElementType()! : type) ??
                     (isArray ? type.GetElementType()! : type);
        var scalarTypeName = PowerShellCSharpSymbolRenderer.TypeName(isArray ? type.GetElementType()! : type);
        var parse = GetParserExpression(scalar);
        return isArray
            ? "static (values, name) => values.Select(value => (" + scalarTypeName + ")" + parse.Replace("{{VALUE}}", "value").Replace("{{NAME}}", "name") + ").ToArray()"
            : "static (values, name) => " + parse.Replace("{{VALUE}}", "values[0]").Replace("{{NAME}}", "name");
    }

    private static string GetParserExpression(Type scalar)
    {
        if (scalar.IsEnum)
            return "ParseEnum<" + PowerShellCSharpSymbolRenderer.TypeName(scalar) + ">({{VALUE}}, {{NAME}})";
        if (scalar == typeof(string)) return "{{VALUE}}";
        if (scalar == typeof(bool)) return "ParseBoolean({{VALUE}}, {{NAME}})";
        if (scalar == typeof(byte)) return "ParseByte({{VALUE}}, {{NAME}})";
        if (scalar == typeof(sbyte)) return "ParseSByte({{VALUE}}, {{NAME}})";
        if (scalar == typeof(short)) return "ParseInt16({{VALUE}}, {{NAME}})";
        if (scalar == typeof(ushort)) return "ParseUInt16({{VALUE}}, {{NAME}})";
        if (scalar == typeof(int)) return "ParseInt32({{VALUE}}, {{NAME}})";
        if (scalar == typeof(uint)) return "ParseUInt32({{VALUE}}, {{NAME}})";
        if (scalar == typeof(long)) return "ParseInt64({{VALUE}}, {{NAME}})";
        if (scalar == typeof(ulong)) return "ParseUInt64({{VALUE}}, {{NAME}})";
        if (scalar == typeof(float)) return "ParseSingle({{VALUE}}, {{NAME}})";
        if (scalar == typeof(double)) return "ParseDouble({{VALUE}}, {{NAME}})";
        if (scalar == typeof(decimal)) return "ParseDecimal({{VALUE}}, {{NAME}})";
        if (scalar == typeof(char)) return "ParseChar({{VALUE}}, {{NAME}})";
        if (scalar == typeof(DateTime)) return "ParseDateTime({{VALUE}}, {{NAME}})";
        if (scalar == typeof(DateTimeOffset)) return "ParseDateTimeOffset({{VALUE}}, {{NAME}})";
        if (scalar == typeof(TimeSpan)) return "ParseTimeSpan({{VALUE}}, {{NAME}})";
        if (scalar == typeof(Guid)) return "ParseGuid({{VALUE}}, {{NAME}})";
        if (scalar == typeof(Uri)) return "ParseUri({{VALUE}}, {{NAME}})";
        if (scalar == typeof(Version)) return "ParseVersion({{VALUE}}, {{NAME}})";
        throw new InvalidOperationException($"Strict executable parameter parser does not support CLR type '{scalar.FullName}'.");
    }

    private static string ReadTemplate(string resourceName)
    {
        using var stream = typeof(PowerShellTypedExecutableEmitter).Assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded compilation template '{resourceName}' was not found.");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}

internal sealed class PowerShellTypedExecutableEmission
{
    internal PowerShellTypedExecutableEmission(
        string compiledSource,
        string programSource,
        PowerShellCompiledMethod[] methods,
        PowerShellCompilationOptimizationEvidence optimization,
        PowerShellCompilationIrSnapshotBundle irSnapshots)
    {
        CompiledSource = compiledSource;
        ProgramSource = programSource;
        Methods = methods;
        Optimization = optimization;
        IrSnapshots = irSnapshots;
    }

    internal string CompiledSource { get; }
    internal string ProgramSource { get; }
    internal PowerShellCompiledMethod[] Methods { get; }
    internal PowerShellCompilationOptimizationEvidence Optimization { get; }
    internal PowerShellCompilationIrSnapshotBundle IrSnapshots { get; }
}
