using System.Management.Automation;
using System.Reflection;
using System.Text;

namespace PowerForge;

internal static class PowerShellBinaryCmdletSourceGenerator
{
    private static readonly HashSet<string> CommonParameterNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "Verbose", "Debug", "ErrorAction", "WarningAction", "InformationAction", "ProgressAction",
        "ErrorVariable", "WarningVariable", "InformationVariable", "OutVariable", "OutBuffer", "PipelineVariable",
        "WhatIf", "Confirm", "UseTransaction"
    };

    private static readonly HashSet<string> ReservedMemberNames = typeof(PSCmdlet)
        .GetMembers(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static)
        .Select(static member => member.Name)
        .Append("ProcessRecord")
        .ToHashSet(StringComparer.OrdinalIgnoreCase);

    internal static string Generate(PowerShellTypedCompilationResult typed, string[]? exportedFunctions = null)
    {
        var selected = exportedFunctions?.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var cmdlets = typed.Methods
            .Where(method => selected is null || selected.Contains(method.SourceName))
            .Select(CreateDescriptor)
            .ToArray();

        var duplicateClass = cmdlets
            .GroupBy(static cmdlet => cmdlet.ClassName, StringComparer.OrdinalIgnoreCase)
            .FirstOrDefault(static group => group.Count() > 1);
        if (duplicateClass is not null)
            throw new InvalidOperationException($"Functions {string.Join(", ", duplicateClass.Select(static cmdlet => $"'{cmdlet.Method.SourceName}'"))} generate duplicate binary-cmdlet class '{duplicateClass.Key}'.");
        var typeCollision = cmdlets.FirstOrDefault(cmdlet => cmdlet.ClassName.Equals(typed.TypeName, StringComparison.OrdinalIgnoreCase));
        if (typeCollision is not null)
            throw new InvalidOperationException($"Function '{typeCollision.Method.SourceName}' generates binary-cmdlet class '{typeCollision.ClassName}', which collides with compiled method container '{typed.TypeName}'.");

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Management.Automation;");
        builder.AppendLine();
        builder.AppendLine($"namespace {typed.NamespaceName};");
        builder.AppendLine();
        foreach (var cmdlet in cmdlets)
            AppendCmdlet(builder, typed, cmdlet);
        return builder.ToString();
    }

    private static CmdletDescriptor CreateDescriptor(PowerShellCompiledMethod method)
    {
        var separator = method.SourceName.IndexOf('-');
        if (separator < 1 || separator == method.SourceName.Length - 1)
            throw new InvalidOperationException($"Function '{method.SourceName}' cannot be exported as a binary cmdlet because it does not use Verb-Noun naming.");
        var verb = method.SourceName.Substring(0, separator);
        var noun = method.SourceName.Substring(separator + 1);
        return new CmdletDescriptor(method, verb, noun, PowerShellCSharpMethodEmitter.SanitizeIdentifier(verb + noun + "Command"));
    }

    private static void AppendCmdlet(StringBuilder builder, PowerShellTypedCompilationResult typed, CmdletDescriptor cmdlet)
    {
        var renamedParameter = cmdlet.Method.Parameters.FirstOrDefault(parameter =>
        {
            var memberName = PowerShellCSharpMethodEmitter.SanitizeIdentifier(parameter.Name);
            return !memberName.TrimStart('@').Equals(parameter.Name, StringComparison.OrdinalIgnoreCase);
        });
        if (renamedParameter is not null)
            throw new InvalidOperationException($"Function '{cmdlet.Method.SourceName}' parameter '${renamedParameter.Name}' cannot preserve its PowerShell name as binary-cmdlet metadata after CLR identifier normalization.");
        var commonParameter = cmdlet.Method.Parameters.FirstOrDefault(parameter => CommonParameterNames.Contains(parameter.Name));
        if (commonParameter is not null)
            throw new InvalidOperationException($"Function '{cmdlet.Method.SourceName}' parameter '${commonParameter.Name}' collides with a PowerShell common parameter and cannot be exported as a binary cmdlet.");
        var reservedParameter = cmdlet.Method.Parameters.FirstOrDefault(parameter =>
        {
            var memberName = PowerShellCSharpMethodEmitter.SanitizeIdentifier(parameter.Name);
            return ReservedMemberNames.Contains(memberName) || memberName.Equals(cmdlet.ClassName, StringComparison.OrdinalIgnoreCase);
        });
        if (reservedParameter is not null)
            throw new InvalidOperationException($"Function '{cmdlet.Method.SourceName}' parameter '${reservedParameter.Name}' collides with generated or inherited binary-cmdlet member '{PowerShellCSharpMethodEmitter.SanitizeIdentifier(reservedParameter.Name)}'.");

        builder.AppendLine($"[Cmdlet(\"{EscapeCSharpString(cmdlet.Verb)}\", \"{EscapeCSharpString(cmdlet.Noun)}\")]");
        var outputType = GetCmdletOutputTypeName(cmdlet.Method.ReturnType);
        if (outputType is not null)
            builder.AppendLine($"[OutputType(typeof({GetGeneratedTypeName(outputType)}))]");
        builder.AppendLine($"public sealed class {cmdlet.ClassName} : PSCmdlet");
        builder.AppendLine("{");
        for (var index = 0; index < cmdlet.Method.Parameters.Length; index++)
        {
            var parameter = cmdlet.Method.Parameters[index];
            builder.AppendLine($"    [Parameter(Position = {index})]");
            builder.AppendLine($"    public {GetGeneratedTypeName(parameter.TypeName)} {PowerShellCSharpMethodEmitter.SanitizeIdentifier(parameter.Name)} {{ get; set; }}{(parameter.TypeName == typeof(string).FullName ? " = string.Empty;" : string.Empty)}");
            builder.AppendLine();
        }
        builder.AppendLine("    protected override void ProcessRecord()");
        builder.AppendLine("    {");
        var arguments = string.Join(", ", cmdlet.Method.Parameters.Select(parameter => PowerShellCSharpMethodEmitter.SanitizeIdentifier(parameter.Name)));
        var invocation = $"{typed.TypeName}.{cmdlet.Method.GeneratedName}({arguments})";
        if (cmdlet.Method.ReturnType.Equals(typeof(void).FullName, StringComparison.Ordinal))
            builder.AppendLine($"        {invocation};");
        else
            builder.AppendLine($"        WriteObject({invocation}, enumerateCollection: true);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static string GetGeneratedTypeName(string fullName)
    {
        if (fullName.EndsWith("[]", StringComparison.Ordinal))
            return GetGeneratedTypeName(fullName.Substring(0, fullName.Length - 2)) + "[]";
        if (fullName == typeof(void).FullName) return "void";
        if (fullName == typeof(bool).FullName) return "bool";
        if (fullName == typeof(byte).FullName) return "byte";
        if (fullName == typeof(sbyte).FullName) return "sbyte";
        if (fullName == typeof(short).FullName) return "short";
        if (fullName == typeof(ushort).FullName) return "ushort";
        if (fullName == typeof(int).FullName) return "int";
        if (fullName == typeof(uint).FullName) return "uint";
        if (fullName == typeof(long).FullName) return "long";
        if (fullName == typeof(ulong).FullName) return "ulong";
        if (fullName == typeof(float).FullName) return "float";
        if (fullName == typeof(double).FullName) return "double";
        if (fullName == typeof(decimal).FullName) return "decimal";
        if (fullName == typeof(char).FullName) return "char";
        if (fullName == typeof(string).FullName) return "string";
        return "global::" + fullName.Replace('+', '.');
    }

    private static string? GetCmdletOutputTypeName(string returnType)
    {
        if (returnType.Equals(typeof(void).FullName, StringComparison.Ordinal))
            return null;
        if (returnType.EndsWith("[]", StringComparison.Ordinal))
            return returnType.Substring(0, returnType.Length - 2);
        var type = Type.GetType(returnType, throwOnError: false);
        return type is not null && type != typeof(string) && typeof(System.Collections.IEnumerable).IsAssignableFrom(type)
            ? typeof(object).FullName
            : returnType;
    }

    private static string EscapeCSharpString(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class CmdletDescriptor
    {
        internal CmdletDescriptor(PowerShellCompiledMethod method, string verb, string noun, string className)
        {
            Method = method;
            Verb = verb;
            Noun = noun;
            ClassName = className;
        }

        internal PowerShellCompiledMethod Method { get; }
        internal string Verb { get; }
        internal string Noun { get; }
        internal string ClassName { get; }
    }
}
