using System.Management.Automation.Language;
using System.Text;

namespace PowerForge;

/// <summary>
/// Composes the script side of a hybrid module while routing selected functions to generated binary cmdlets.
/// </summary>
internal static class PowerShellHybridModuleComposer
{
    internal static string ComposeRoot(
        string sourcePath,
        string assemblyFileName,
        PowerShellTypedCompilationResult typed,
        bool manifestControlsExports = false)
    {
        Token[] tokens;
        ParseError[] errors;
        var ast = Parser.ParseFile(sourcePath, out tokens, out errors);
        if (errors.Length > 0)
            throw new InvalidOperationException("Hybrid module source could not be parsed while composing fallback code.");

        var prologueEndOffset = ast.ParamBlock?.Extent.EndOffset ?? 0;
        foreach (var usingStatement in ast.FindAll(static node => node is UsingStatementAst, searchNestedScriptBlocks: false).Cast<UsingStatementAst>())
            prologueEndOffset = Math.Max(prologueEndOffset, usingStatement.Extent.EndOffset);
        var functions = ast.FindAll(static node => node is FunctionDefinitionAst, searchNestedScriptBlocks: false)
            .Cast<FunctionDefinitionAst>()
            .OrderByDescending(static function => function.Extent.StartOffset)
            .ToArray();
        var runtimeVariables = CreateRuntimeRegionVariableNames(ast);
        var source = new StringBuilder(ast.Extent.Text);
        var exportContract = PowerShellModuleExportContract.TryRead(ast);
        var wrapped = GetWrappedCompiledMethodKeys(sourcePath, typed);
        var removals = new List<(int Start, int Length)>();
        foreach (var function in functions)
        {
            if (!wrapped.Contains(GetCompiledMethodKey(sourcePath, function.Name, function.Body.Extent.StartLineNumber)))
                continue;
            if (function.Extent.StartOffset < prologueEndOffset)
                throw new InvalidOperationException($"Compiled function '{function.Name}' overlaps the module prologue and cannot be composed safely.");
            removals.Add((function.Extent.StartOffset, function.Extent.EndOffset - function.Extent.StartOffset));
        }
        if (exportContract is not null)
            removals.AddRange(exportContract.Commands.Select(static command =>
                (command.Extent.StartOffset, command.Extent.EndOffset - command.Extent.StartOffset)));
        foreach (var removal in removals.OrderByDescending(static removal => removal.Start))
            source.Remove(removal.Start, removal.Length);

        var fallbackFunctions = ReadModuleScopeFunctions(typed.SourcePaths)
            .Where(function => !wrapped.Contains(GetCompiledMethodKey(function.Path, function.Name, function.Line)))
            .Select(static function => function.Name)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var compiledCmdlets = typed.Methods
            .Select(static method => method.SourceName)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var exportedFallbackFunctions = (exportContract?.SelectFunctions(fallbackFunctions) ?? fallbackFunctions)
            .Concat(PowerShellCompiledModuleManifest.GetNestedModuleFunctionExportPatterns(sourcePath, fallbackFunctions))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var exportedCompiledCmdlets = exportContract?.SelectFunctions(compiledCmdlets) ?? compiledCmdlets;
        var additionalCmdlets = exportContract?.Cmdlets ?? Array.Empty<string>();
        var aliases = exportContract?.Aliases ?? new[] { "*" };
        var variables = exportContract?.Variables ?? Array.Empty<string>();
        var import = new StringBuilder();
        if (prologueEndOffset > 0 && source[prologueEndOffset - 1] is not '\r' and not '\n') import.AppendLine();
        import.AppendLine("# Generated by PowerForge hybrid PowerShell compilation.");
        import.AppendLine("Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '" + EscapePowerShellSingleQuotedString(assemblyFileName) + "') -Force -ErrorAction Stop");
        if (typed.Methods.Any(static method => method.RequiresPowerShellCommandRegions))
        {
            var hostType = "[" + typed.NamespaceName + "." + PowerShellBinaryCmdletSourceGenerator.GetRuntimeRegionHostTypeName(typed) + "]";
            import.Append('$').Append(runtimeVariables.RunspaceId).AppendLine(" = [System.Management.Automation.Runspaces.Runspace]::DefaultRunspace.InstanceId");
            import.Append(hostType).Append("::SetDispatcher($").Append(runtimeVariables.RunspaceId)
                .AppendLine(", { param($script, [object[]] $arguments) & ([scriptblock]::Create($script)) @arguments })");
        }
        import.AppendLine();
        source.Insert(prologueEndOffset, import.ToString());
        var builder = new StringBuilder(source.ToString());
        if (source.Length > 0 && source[source.Length - 1] != '\n') builder.AppendLine();
        AppendRuntimeRegionCleanup(builder, typed, runtimeVariables);
        if (manifestControlsExports)
            return builder.ToString();
        if (exportContract is not null && exportContract.Commands.Length == 0)
            return builder.ToString();
        builder.AppendLine();
        builder.Append("Export-ModuleMember -Function @(").Append(JoinPowerShellNames(exportedFallbackFunctions))
            .Append(") -Cmdlet @(").Append(JoinPowerShellNames(exportedCompiledCmdlets.Concat(additionalCmdlets).Distinct(StringComparer.OrdinalIgnoreCase)))
            .Append(") -Alias @(").Append(JoinPowerShellNames(aliases)).Append(')');
        if (variables.Length > 0)
            builder.Append(" -Variable @(").Append(JoinPowerShellNames(variables)).Append(')');
        builder.AppendLine();
        return builder.ToString();
    }

    private static void AppendRuntimeRegionCleanup(
        StringBuilder builder,
        PowerShellTypedCompilationResult typed,
        RuntimeRegionVariableNames variables)
    {
        if (!typed.Methods.Any(static method => method.RequiresPowerShellCommandRegions))
            return;
        var hostType = "[" + typed.NamespaceName + "." + PowerShellBinaryCmdletSourceGenerator.GetRuntimeRegionHostTypeName(typed) + "]";
        builder.Append('$').Append(variables.Module).AppendLine(" = $ExecutionContext.SessionState.Module");
        builder.Append('$').Append(variables.PreviousOnRemove).Append(" = $").Append(variables.Module).AppendLine(".OnRemove");
        builder.Append('$').Append(variables.Module).AppendLine(".OnRemove = {");
        builder.Append("    ").Append(hostType).Append("::ClearDispatcher($").Append(variables.RunspaceId).AppendLine(")");
        builder.Append("    if ($null -ne $").Append(variables.PreviousOnRemove).Append(") { & $").Append(variables.PreviousOnRemove).AppendLine(" }");
        builder.AppendLine("}.GetNewClosure()");
        builder.Append("Remove-Variable -Name ").Append(variables.RunspaceId).Append(", ").Append(variables.Module)
            .Append(", ").Append(variables.PreviousOnRemove).AppendLine(" -Scope Script -ErrorAction SilentlyContinue");
    }

    internal static string? ComposeDependency(
        string sourcePath,
        PowerShellTypedCompilationResult typed,
        ISet<string> wrappedCompiledMethods)
    {
        var compiled = typed.Methods
            .Where(method => PowerShellCompilationPathSafety.PathEquals(
                string.IsNullOrWhiteSpace(method.SourcePath) ? typed.SourcePath : method.SourcePath,
                sourcePath))
            .Select(method => GetCompiledMethodKey(sourcePath, method.SourceName, method.SourceLine))
            .Where(wrappedCompiledMethods.Contains)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        if (compiled.Count == 0)
            return null;

        Token[] tokens;
        ParseError[] errors;
        var ast = Parser.ParseFile(sourcePath, out tokens, out errors);
        if (errors.Length > 0)
            throw new InvalidOperationException($"Hybrid module dependency '{sourcePath}' could not be parsed while composing fallback code.");
        var source = new StringBuilder(ast.Extent.Text);
        foreach (var function in ast.FindAll(static node => node is FunctionDefinitionAst, searchNestedScriptBlocks: false)
                     .Cast<FunctionDefinitionAst>()
                     .Where(function => compiled.Contains(GetCompiledMethodKey(sourcePath, function.Name, function.Body.Extent.StartLineNumber)))
                     .OrderByDescending(static function => function.Extent.StartOffset))
        {
            source.Remove(function.Extent.StartOffset, function.Extent.EndOffset - function.Extent.StartOffset);
        }
        return source.ToString();
    }

    private static RuntimeRegionVariableNames CreateRuntimeRegionVariableNames(ScriptBlockAst ast)
    {
        var authoredNames = ast.FindAll(static node => node is VariableExpressionAst, searchNestedScriptBlocks: true)
            .OfType<VariableExpressionAst>()
            .Select(static variable => GetUnqualifiedVariableName(variable.VariablePath.UserPath))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        for (var index = 0; ; index++)
        {
            var suffix = index == 0 ? string.Empty : "_" + index.ToString(System.Globalization.CultureInfo.InvariantCulture);
            var names = new RuntimeRegionVariableNames(
                "__powerForgeRunspaceId" + suffix,
                "__powerForgeModule" + suffix,
                "__powerForgePreviousOnRemove" + suffix);
            if (!authoredNames.Contains(names.RunspaceId) &&
                !authoredNames.Contains(names.Module) &&
                !authoredNames.Contains(names.PreviousOnRemove))
                return names;
        }
    }

    private static string GetUnqualifiedVariableName(string userPath)
    {
        var separator = userPath.IndexOf(':');
        return separator < 0 ? userPath : userPath.Substring(separator + 1);
    }

    internal static HashSet<string> GetWrappedCompiledMethodKeys(string sourcePath, PowerShellTypedCompilationResult typed)
    {
        var exportContract = PowerShellModuleExportContract.TryRead(sourcePath);
        var wrappedFunctionNames = exportContract?.SelectFunctions(typed.Methods.Select(static method => method.SourceName))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        return typed.Methods
            .Where(method => wrappedFunctionNames is null || wrappedFunctionNames.Contains(method.SourceName))
            .Select(method => GetCompiledMethodKey(
                string.IsNullOrWhiteSpace(method.SourcePath) ? typed.SourcePath : method.SourcePath,
                method.SourceName,
                method.SourceLine))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    private static IEnumerable<ModuleScopeFunction> ReadModuleScopeFunctions(IEnumerable<string> sourcePaths)
    {
        foreach (var sourcePath in sourcePaths.Distinct(PowerShellCompilationPathSafety.PathComparer))
        {
            Token[] tokens;
            ParseError[] errors;
            var ast = Parser.ParseFile(sourcePath, out tokens, out errors);
            if (errors.Length > 0)
                throw new InvalidOperationException($"Module source '{sourcePath}' could not be parsed while composing fallback exports.");
            foreach (var function in ast.FindAll(static node => node is FunctionDefinitionAst, searchNestedScriptBlocks: false).Cast<FunctionDefinitionAst>())
                yield return new ModuleScopeFunction(sourcePath, function.Name, function.Body.Extent.StartLineNumber);
        }
    }

    private static string GetCompiledMethodKey(string sourcePath, string name, int line)
        => Path.GetFullPath(sourcePath) + "\0" + name + "\0" + line;

    private static string JoinPowerShellNames(IEnumerable<string> names)
        => string.Join(", ", names.Select(name => "'" + EscapePowerShellSingleQuotedString(name) + "'"));

    private static string EscapePowerShellSingleQuotedString(string value)
        => value.Replace("'", "''");

    private sealed class ModuleScopeFunction
    {
        internal ModuleScopeFunction(string path, string name, int line)
        {
            Path = path;
            Name = name;
            Line = line;
        }

        internal string Path { get; }
        internal string Name { get; }
        internal int Line { get; }
    }

    private sealed class RuntimeRegionVariableNames
    {
        internal RuntimeRegionVariableNames(string runspaceId, string module, string previousOnRemove)
        {
            RunspaceId = runspaceId;
            Module = module;
            PreviousOnRemove = previousOnRemove;
        }

        internal string RunspaceId { get; }
        internal string Module { get; }
        internal string PreviousOnRemove { get; }
    }
}
