using System.Management.Automation.Language;
using System.Text;

namespace PowerForge;

/// <summary>
/// Generates a runtime-independent console entry point for an eligible top-level PowerShell script.
/// </summary>
internal static class PowerShellTypedExecutableEmitter
{
    private const string ProgramTemplate = "PowerForge.PowerShell.Compilation.TypedExecutableProgram.cs.template";

    internal static PowerShellTypedExecutableEmission Emit(
        string sourcePath,
        IEnumerable<string> sourcePaths,
        PowerShellCompilationPlan plan,
        string targetFramework)
    {
        var compilation = PowerShellTypedExecutableCompiler.Compile(sourcePath, sourcePaths, plan, targetFramework);
        var ast = compilation.EntryPoint;
        var scriptUnit = compilation.EntryPointUnit;
        var method = compilation.EntryPointMethod;
        PowerShellTypedExecutableOutputPolicy.EnsureSupported(method.ReturnType);
        var compiledSource = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("namespace PowerForge.Compiled;")
            .AppendLine()
            .AppendLine("public static class CompiledPowerShellScript")
            .AppendLine("{")
            .AppendLine(string.Join(Environment.NewLine, compilation.LocalMethods.Select(static local => local.Source)))
            .AppendLine(method.Source)
            .AppendLine("}")
            .ToString();

        var parameters = ast.ParamBlock?.Parameters.ToArray() ?? Array.Empty<ParameterAst>();
        var analyzedParameters = scriptUnit.Parameters.ToDictionary(static parameter => parameter.Name, StringComparer.OrdinalIgnoreCase);
        var parameterSpecs = string.Join(Environment.NewLine, parameters.Select(parameter =>
        {
            var metadata = analyzedParameters[parameter.Name.VariablePath.UserPath];
            return "        new ParameterSpec(" + PowerShellCSharpLiteral.QuoteString(metadata.Name) + ", typeof(" +
                   PowerShellCSharpMethodEmitter.GetTypeName(GetCompiledParameterType(parameter)) + "), " +
                   (metadata.IsMandatory ? "true" : "false") + ", " +
                   (metadata.IsSwitch ? "true" : "false") + ", " +
                   GenerateStringArray(metadata.Aliases) + ", " +
                   (metadata.AllowNull ? "true" : "false") + ", " +
                   GenerateValidations(metadata.Validations) + "),";
        }));
        var arguments = string.Join(", ", parameters.Select(parameter =>
            "(" + PowerShellCSharpMethodEmitter.GetTypeName(GetCompiledParameterType(parameter)) + ")values[" +
            PowerShellCSharpLiteral.QuoteString(parameter.Name.VariablePath.UserPath) + "]"));
        var invocation = "CompiledPowerShellScript." + method.GeneratedName + "(" + arguments + ")";
        var invocationSource = method.ReturnType == typeof(void)
            ? "            " + invocation + ";" + Environment.NewLine + "            return 0;"
            : "            var result = " + invocation + ";" + Environment.NewLine +
              "            WriteResult(result);" + Environment.NewLine + "            return 0;";
        var programSource = ReadTemplate(ProgramTemplate)
            .Replace("{{PARAMETER_SPECS}}", parameterSpecs)
            .Replace("{{INVOCATION}}", invocationSource);
        return new PowerShellTypedExecutableEmission(compiledSource, programSource, compilation.Methods);
    }

    private static Type GetCompiledParameterType(ParameterAst parameter)
        => parameter.StaticType == typeof(System.Management.Automation.SwitchParameter)
            ? typeof(bool)
            : parameter.StaticType;

    private static string GenerateStringArray(IEnumerable<string> values)
        => "new string[] { " + string.Join(", ", values.Select(PowerShellCSharpLiteral.QuoteString)) + " }";

    private static string GenerateValidations(IEnumerable<PowerShellCompilationValidation> validations)
        => "new ValidationSpec[] { " + string.Join(", ", validations.Select(validation =>
            "new ValidationSpec(ValidationKind." + validation.Kind + ", " + GenerateStringArray(validation.Arguments) + ")")) + " }";

    private static string ReadTemplate(string resourceName)
    {
        using var stream = typeof(PowerShellTypedExecutableEmitter).Assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded compilation template '{resourceName}' was not found.");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}

internal sealed class PowerShellTypedExecutableEmission
{
    internal PowerShellTypedExecutableEmission(string compiledSource, string programSource, PowerShellCompiledMethod[] methods)
    {
        CompiledSource = compiledSource;
        ProgramSource = programSource;
        Methods = methods;
    }

    internal string CompiledSource { get; }
    internal string ProgramSource { get; }
    internal PowerShellCompiledMethod[] Methods { get; }
}
