using System.Management.Automation.Language;
using System.Runtime.InteropServices;
using System.Text;

namespace PowerForge;

/// <summary>
/// Composes the script side of a hybrid module while routing selected functions to generated binary cmdlets.
/// </summary>
internal static class PowerShellHybridModuleComposer
{
    internal static string ComposeRoot(
        string sourcePath,
        string assemblyFileName,
        PowerShellTypedCompilationResult typed,
        bool manifestControlsExports = false)
    {
        Token[] tokens;
        ParseError[] errors;
        var ast = Parser.ParseFile(sourcePath, out tokens, out errors);
        if (errors.Length > 0)
            throw new InvalidOperationException("Hybrid module source could not be parsed while composing fallback code.");

        var prologueEndOffset = ast.ParamBlock?.Extent.EndOffset ?? 0;
        foreach (var usingStatement in ast.FindAll(static node => node is UsingStatementAst, searchNestedScriptBlocks: false).Cast<UsingStatementAst>())
            prologueEndOffset = Math.Max(prologueEndOffset, usingStatement.Extent.EndOffset);
        var functions = ast.FindAll(static node => node is FunctionDefinitionAst, searchNestedScriptBlocks: false)
            .Cast<FunctionDefinitionAst>()
            .OrderByDescending(static function => function.Extent.StartOffset)
            .ToArray();
        var source = new StringBuilder(File.ReadAllText(sourcePath));
        var exportContract = PowerShellModuleExportContract.TryRead(ast);
        var wrapped = GetWrappedCompiledMethodKeys(sourcePath, typed);
        var removals = new List<(int Start, int Length)>();
        foreach (var function in functions)
        {
            if (!wrapped.Contains(GetCompiledMethodKey(sourcePath, function.Name, function.Extent.StartLineNumber)))
                continue;
            if (function.Extent.StartOffset < prologueEndOffset)
                throw new InvalidOperationException($"Compiled function '{function.Name}' overlaps the module prologue and cannot be composed safely.");
            removals.Add((function.Extent.StartOffset, function.Extent.EndOffset - function.Extent.StartOffset));
        }
        if (exportContract is not null)
            removals.AddRange(exportContract.Commands.Select(static command =>
                (command.Extent.StartOffset, command.Extent.EndOffset - command.Extent.StartOffset)));
        foreach (var removal in removals.OrderByDescending(static removal => removal.Start))
            source.Remove(removal.Start, removal.Length);

        var fallbackFunctions = ReadModuleScopeFunctions(typed.SourcePaths)
            .Where(function => !wrapped.Contains(GetCompiledMethodKey(function.Path, function.Name, function.Line)))
            .Select(static function => function.Name)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var compiledCmdlets = typed.Methods
            .Select(static method => method.SourceName)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var exportedFallbackFunctions = PowerShellCompiledModuleManifest.HasNestedModuleWildcardFunctionExports(sourcePath)
            ? new[] { "*" }
            : exportContract?.SelectFunctions(fallbackFunctions) ?? fallbackFunctions;
        var exportedCompiledCmdlets = exportContract?.SelectFunctions(compiledCmdlets) ?? compiledCmdlets;
        var additionalCmdlets = exportContract?.Cmdlets ?? Array.Empty<string>();
        var aliases = exportContract?.Aliases ?? new[] { "*" };
        var variables = exportContract?.Variables ?? Array.Empty<string>();
        var import = new StringBuilder();
        if (prologueEndOffset > 0 && source[prologueEndOffset - 1] is not '\r' and not '\n') import.AppendLine();
        import.AppendLine("# Generated by PowerForge hybrid PowerShell compilation.");
        import.AppendLine("Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '" + EscapePowerShellSingleQuotedString(assemblyFileName) + "') -Force -ErrorAction Stop");
        import.AppendLine();
        source.Insert(prologueEndOffset, import.ToString());
        var builder = new StringBuilder(source.ToString());
        if (source.Length > 0 && source[source.Length - 1] != '\n') builder.AppendLine();
        if (manifestControlsExports)
            return builder.ToString();
        if (exportContract is not null && exportContract.Commands.Length == 0)
            return builder.ToString();
        builder.AppendLine();
        builder.Append("Export-ModuleMember -Function @(").Append(JoinPowerShellNames(exportedFallbackFunctions))
            .Append(") -Cmdlet @(").Append(JoinPowerShellNames(exportedCompiledCmdlets.Concat(additionalCmdlets).Distinct(StringComparer.OrdinalIgnoreCase)))
            .Append(") -Alias @(").Append(JoinPowerShellNames(aliases)).Append(')');
        if (variables.Length > 0)
            builder.Append(" -Variable @(").Append(JoinPowerShellNames(variables)).Append(')');
        builder.AppendLine();
        return builder.ToString();
    }

    internal static string? ComposeDependency(
        string sourcePath,
        PowerShellTypedCompilationResult typed,
        ISet<string> wrappedCompiledMethods)
    {
        var compiled = typed.Methods
            .Where(method => (string.IsNullOrWhiteSpace(method.SourcePath) ? typed.SourcePath : method.SourcePath)
                .Equals(sourcePath, RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal))
            .Select(method => GetCompiledMethodKey(sourcePath, method.SourceName, method.SourceLine))
            .Where(wrappedCompiledMethods.Contains)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        if (compiled.Count == 0)
            return null;

        Token[] tokens;
        ParseError[] errors;
        var ast = Parser.ParseFile(sourcePath, out tokens, out errors);
        if (errors.Length > 0)
            throw new InvalidOperationException($"Hybrid module dependency '{sourcePath}' could not be parsed while composing fallback code.");
        var source = new StringBuilder(File.ReadAllText(sourcePath));
        foreach (var function in ast.FindAll(static node => node is FunctionDefinitionAst, searchNestedScriptBlocks: false)
                     .Cast<FunctionDefinitionAst>()
                     .Where(function => compiled.Contains(GetCompiledMethodKey(sourcePath, function.Name, function.Extent.StartLineNumber)))
                     .OrderByDescending(static function => function.Extent.StartOffset))
        {
            source.Remove(function.Extent.StartOffset, function.Extent.EndOffset - function.Extent.StartOffset);
        }
        return source.ToString();
    }

    internal static HashSet<string> GetWrappedCompiledMethodKeys(string sourcePath, PowerShellTypedCompilationResult typed)
    {
        var exportContract = PowerShellModuleExportContract.TryRead(sourcePath);
        var wrappedFunctionNames = exportContract?.SelectFunctions(typed.Methods.Select(static method => method.SourceName))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        return typed.Methods
            .Where(method => wrappedFunctionNames is null || wrappedFunctionNames.Contains(method.SourceName))
            .Select(method => GetCompiledMethodKey(
                string.IsNullOrWhiteSpace(method.SourcePath) ? typed.SourcePath : method.SourcePath,
                method.SourceName,
                method.SourceLine))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    private static IEnumerable<ModuleScopeFunction> ReadModuleScopeFunctions(IEnumerable<string> sourcePaths)
    {
        foreach (var sourcePath in sourcePaths.Distinct(RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? StringComparer.OrdinalIgnoreCase : StringComparer.Ordinal))
        {
            Token[] tokens;
            ParseError[] errors;
            var ast = Parser.ParseFile(sourcePath, out tokens, out errors);
            if (errors.Length > 0)
                throw new InvalidOperationException($"Module source '{sourcePath}' could not be parsed while composing fallback exports.");
            foreach (var function in ast.FindAll(static node => node is FunctionDefinitionAst, searchNestedScriptBlocks: false).Cast<FunctionDefinitionAst>())
                yield return new ModuleScopeFunction(sourcePath, function.Name, function.Extent.StartLineNumber);
        }
    }

    private static string GetCompiledMethodKey(string sourcePath, string name, int line)
        => Path.GetFullPath(sourcePath) + "\0" + name + "\0" + line;

    private static string JoinPowerShellNames(IEnumerable<string> names)
        => string.Join(", ", names.Select(name => "'" + EscapePowerShellSingleQuotedString(name) + "'"));

    private static string EscapePowerShellSingleQuotedString(string value)
        => value.Replace("'", "''");

    private sealed class ModuleScopeFunction
    {
        internal ModuleScopeFunction(string path, string name, int line)
        {
            Path = path;
            Name = name;
            Line = line;
        }

        internal string Path { get; }
        internal string Name { get; }
        internal int Line { get; }
    }
}
